/**
 * Generator: adapter.ts — plain TypeScript adapter interface.
 * Imports only from the sibling types.ts.
 */
import type { ResolvedEntityConfig } from '../types';

/**
 * Generate the TypeScript adapter interface source code for an entity.
 *
 * Produces a `{Name}Adapter` interface that extends the five core CRUD methods
 * (`create`, `getById`, `update`, `delete`, `list`) with any additional
 * operation signatures supplied by the caller (from `generateOperationSignatures()`).
 * Also exports the shared `PaginatedResult<T>` and `ListOptions` helper types
 * required by the interface.
 *
 * @param config - The resolved entity configuration describing the entity's
 *   name, primary key field and type.
 * @param operationSignatures - Optional array of pre-rendered TypeScript method
 *   signature strings (one per operation) to append after the CRUD methods. Pass
 *   the return value of `generateOperationSignatures()` here.
 * @returns A string containing the TypeScript source code for the adapter
 *   interface file, including the `PaginatedResult`, `ListOptions`, and
 *   `{Name}Adapter` exports.
 *
 * @remarks
 * The generated file imports only from the sibling `types.ts` file and has no
 * external dependencies. The `clear()` method is always included to support
 * test isolation.
 *
 * @example
 * ```ts
 * import { generateAdapter } from '@lastshotlabs/slingshot-entity';
 *
 * const source = generateAdapter(config, ['  bySlug(slug: string): Promise<Message | null>;']);
 * // Write source to adapter.ts in the entity output directory
 * ```
 */
export function generateAdapter(
  config: ResolvedEntityConfig,
  operationSignatures?: string[],
): string {
  const name = config.name;
  const pkDef = config.fields[config._pkField];
  const pkType = pkDef.type === 'string' ? 'string' : 'number';

  const opSigs =
    operationSignatures && operationSignatures.length > 0
      ? `\n  // --- Operations ---\n${operationSignatures.join('\n')}\n`
      : '';

  return `// Auto-generated by @lastshotlabs/slingshot-entity — do not edit manually.

import type { ${name}, Create${name}Input, Update${name}Input } from './types';

export interface PaginatedResult<T> {
  items: T[];
  nextCursor?: string;
  hasMore: boolean;
}

export interface ListOptions {
  limit?: number;
  cursor?: string;
  sortDir?: 'asc' | 'desc';
  [key: string]: unknown;
}

export interface ${name}Adapter {
  create(input: Create${name}Input): Promise<${name}>;
  getById(id: ${pkType}, filter?: Record<string, unknown>): Promise<${name} | null>;
  update(id: ${pkType}, input: Update${name}Input, filter?: Record<string, unknown>): Promise<${name} | null>;
  delete(id: ${pkType}, filter?: Record<string, unknown>): Promise<boolean>;
  list(opts?: ListOptions): Promise<PaginatedResult<${name}>>;
  clear(): Promise<void>;
${opSigs}}
`;
}
