/**
 * Event type declaration generator.
 *
 * Produces TypeScript module augmentation that extends SlingshotEventMap with
 * the entity-specific events declared in EntityRouteConfig.
 *
 * Pure function: config → source string.
 */
import type {
  EntityRouteConfig,
  ResolvedEntityConfig,
  RouteOperationConfig,
} from '@lastshotlabs/slingshot-core';
import type { FieldDef } from '../types';

/**
 * Generate TypeScript module augmentation source code declaring entity-specific
 * event types in `SlingshotEventMap`.
 *
 * Scans the entity's `routes` config for CRUD and operation-level `event`
 * declarations. For each event found, generates an interface entry in a
 * `declare module '@lastshotlabs/slingshot-core'` block with the event key mapped
 * to a typed payload object whose fields are derived from the entity's field
 * definitions. All payloads also include `tenantId?: string` and
 * `actorId?: string`.
 *
 * @param config - The resolved entity configuration. If `config.routes` has no
 *   event declarations, returns an empty string.
 * @returns A string containing the TypeScript module augmentation source code,
 *   or `''` when no events are declared.
 *
 * @remarks
 * The generated code uses `declare module` augmentation — it does not import
 * or export anything, and it is safe to include in any TypeScript project that
 * imports `@lastshotlabs/slingshot-core`.
 *
 * @example
 * ```ts
 * import { generateEvents } from '@lastshotlabs/slingshot-entity';
 *
 * const source = generateEvents(config);
 * if (source) {
 *   // Write source to events.d.ts in the entity output directory
 * }
 * ```
 */
export function generateEvents(config: ResolvedEntityConfig): string {
  const events = collectRouteEvents(config);
  if (events.length === 0) return '';

  const lines: string[] = [
    `// Auto-generated by @lastshotlabs/slingshot-entity — do not edit manually.`,
    ``,
    `declare module '@lastshotlabs/slingshot-core' {`,
    `  interface SlingshotEventMap {`,
  ];

  for (const { key, payloadFields } of events) {
    lines.push(`    '${key}': {`);
    for (const f of payloadFields) {
      const fieldDef = config.fields[f] as FieldDef | undefined;
      if (fieldDef) {
        lines.push(`      ${f}: ${fieldToTsType(fieldDef)};`);
      }
    }
    lines.push(`      tenantId?: string;`);
    lines.push(`      actorId?: string;`);
    lines.push(`    };`);
  }

  lines.push(`  }`);
  lines.push(`}`);
  lines.push(``);
  return lines.join('\n');
}

/**
 * Return `true` when the route config contains at least one event declaration.
 *
 * Checks CRUD operations (`create`, `get`, `list`, `update`, `delete`) and all
 * entries in `routeConfig.operations` for an `event` key.
 *
 * @param routeConfig - The entity route config to inspect.
 * @returns `true` if at least one event is declared; `false` otherwise.
 *
 * @example
 * ```ts
 * import { hasEvents } from '@lastshotlabs/slingshot-entity';
 *
 * if (hasEvents(config.routes)) {
 *   const eventSource = generateEvents(config);
 * }
 * ```
 */
export function hasEvents(routeConfig: EntityRouteConfig): boolean {
  return collectEventsFromRouteConfig(routeConfig).length > 0;
}

/**
 * Collect all event declarations from a resolved entity config's `routes`.
 *
 * Delegates to `collectEventsFromRouteConfig()` after checking that
 * `config.routes` is present.
 *
 * @param config - The resolved entity configuration to inspect.
 * @returns An array of `{ key, payloadFields }` entries for every event
 *   declared in the entity's route config, or `[]` when `config.routes`
 *   is absent.
 */
function collectRouteEvents(
  config: ResolvedEntityConfig,
): Array<{ key: string; payloadFields: string[] }> {
  if (!config.routes) return [];
  return collectEventsFromRouteConfig(config.routes);
}

/**
 * Scan an `EntityRouteConfig` and return every declared event.
 *
 * Inspects the five CRUD operations (`create`, `get`, `list`, `update`,
 * `delete`) and all entries in `rc.operations` for an `event` declaration.
 * Both shorthand strings (`event: 'my.event'`) and object forms
 * (`event: { key: 'my.event', payload: ['id'] }`) are normalised to
 * `{ key, payloadFields }`.
 *
 * @param rc - The `EntityRouteConfig` to scan.
 * @returns An array of `{ key, payloadFields }` entries, one per declared
 *   event across all operations, in declaration order.
 */
function collectEventsFromRouteConfig(
  rc: EntityRouteConfig,
): Array<{ key: string; payloadFields: string[] }> {
  const events: Array<{ key: string; payloadFields: string[] }> = [];
  const crudOps = ['create', 'get', 'list', 'update', 'delete'] as const;

  for (const op of crudOps) {
    const opConfig = rc[op];
    if (opConfig?.event) {
      const evt =
        typeof opConfig.event === 'string'
          ? { key: opConfig.event, payload: [] as string[] }
          : opConfig.event;
      events.push({ key: evt.key, payloadFields: evt.payload ?? [] });
    }
  }

  for (const opConfig of Object.values(rc.operations ?? {}) as RouteOperationConfig[]) {
    if (opConfig.event) {
      const evt =
        typeof opConfig.event === 'string'
          ? { key: opConfig.event, payload: [] as string[] }
          : opConfig.event;
      events.push({ key: evt.key, payloadFields: evt.payload ?? [] });
    }
  }

  return events;
}

/**
 * Map a `FieldDef` to its TypeScript type string for event payload declarations.
 *
 * @param field - The field definition to map.
 * @returns A TypeScript type string, e.g. `'string'`, `'number'`, `'boolean'`,
 *   `'Date'`, `'string[]'`, a union of enum values like `'\'a\' | \'b\''`,
 *   or `'unknown'` for `json` and unrecognised types. When `field.optional` is
 *   `true`, `' | undefined'` is appended.
 */
function fieldToTsType(field: FieldDef): string {
  const baseType = (() => {
    switch (field.type) {
      case 'string':
        return 'string';
      case 'number':
      case 'integer':
        return 'number';
      case 'boolean':
        return 'boolean';
      case 'date':
        return 'Date';
      case 'json':
        return 'unknown';
      case 'string[]':
        return 'string[]';
      case 'enum':
        return field.enumValues && field.enumValues.length > 0
          ? field.enumValues.map(v => `'${v}'`).join(' | ')
          : 'string';
      default:
        return 'unknown';
    }
  })();
  return field.optional ? `${baseType} | undefined` : baseType;
}
