/**
 * Generator: memory.ts — in-memory adapter. Imports nothing external.
 */
import { fieldEntries, isAutoDefault, memoryMaxEntries } from '../lib/naming';
import type { ResolvedEntityConfig } from '../types';

/**
 * Generate the in-memory adapter implementation source code for an entity.
 *
 * Produces a `createMemory{Name}Adapter(): {Name}Adapter` factory function
 * that stores entity records in a closure-owned `Map`. The generated file has
 * zero external imports and is fully self-contained.
 *
 * The implementation includes:
 * - An eviction strategy capped at `config.storage.memory.maxEntries` (default
 *   from `memoryMaxEntries()`) by removing the oldest entry when the store is full.
 * - TTL expiry via `MemoryEntry.expiresAt` and an `isAlive()` guard on every
 *   read path when `config.ttl` is set.
 * - Soft-delete visibility via a `recordVisible()` guard when
 *   `config.softDelete` is set.
 * - `applyDefaults()` and (when needed) `applyOnUpdate()` helpers.
 * - In-process filtering (`matchesFilter()`), multi-field sorting
 *   (`compareForSort()`), and cursor-based pagination via base64url-encoded
 *   JSON cursors.
 * - Per-field date handling in `parseCursorValues()` to restore `Date` objects
 *   from ISO-8601 strings in the cursor payload.
 *
 * @param config - The resolved entity configuration.
 * @returns A string containing the TypeScript source code for the in-memory
 *   adapter implementation file.
 *
 * @remarks
 * The `clear()` method calls `store.clear()` to remove all records. This is
 * the standard mechanism for test isolation between test cases.
 *
 * @example
 * ```ts
 * import { generateMemory } from '@lastshotlabs/slingshot-entity';
 *
 * const source = generateMemory(config);
 * // Write source to memory.ts in the entity output directory
 * ```
 */
export function generateMemory(config: ResolvedEntityConfig): string {
  const name = config.name;
  const pkField = config._pkField;
  const pkDef = config.fields[pkField];
  const pkType = pkDef.type === 'string' ? 'string' : 'number';
  const maxEntries = memoryMaxEntries(config);
  const ttlSeconds = config.ttl?.defaultSeconds;
  const ttlMs = ttlSeconds ? ttlSeconds * 1000 : undefined;
  const defaultLimit = config.pagination?.defaultLimit ?? 50;
  const maxLimit = config.pagination?.maxLimit ?? 200;
  const cursorFields = config.pagination?.cursor.fields ?? [pkField];
  const defaultSortDir = config.defaultSort?.direction ?? 'asc';
  const hasSoftDelete = !!config.softDelete;
  const sdNonNull = config.softDelete !== undefined && 'strategy' in config.softDelete;
  const sdValue =
    config.softDelete !== undefined && 'value' in config.softDelete ? config.softDelete.value : '';
  const fields = fieldEntries(config);

  // Determine which fields need auto-defaults
  const autoDefaultFields = fields.filter(([, def]) => isAutoDefault(def.default));
  const literalDefaultFields = fields.filter(
    ([, def]) => def.default !== undefined && !isAutoDefault(def.default),
  );
  const onUpdateFields = fields.filter(([, def]) => def.onUpdate === 'now');
  const dateFields = fields.filter(([, def]) => def.type === 'date');

  const lines: string[] = [
    '// Auto-generated by @lastshotlabs/slingshot-entity — do not edit manually.',
    '',
    `import type { ${name}, Create${name}Input, Update${name}Input } from './types';`,
    `import type { ${name}Adapter, PaginatedResult } from './adapter';`,
    '',
  ];

  // --- Helpers inlined ---
  lines.push('// --- Inlined helpers (no external dependencies) ---');
  lines.push('');

  // Cursor encode/decode
  lines.push(`function encodeCursor(values: Record<string, unknown>): string {`);
  lines.push(`  return Buffer.from(JSON.stringify(values)).toString('base64url');`);
  lines.push('}');
  lines.push('');
  lines.push(`function decodeCursor(cursor: string): Record<string, unknown> {`);
  lines.push(
    `  return JSON.parse(Buffer.from(cursor, 'base64url').toString('utf-8')) as Record<string, unknown>;`,
  );
  lines.push('}');
  lines.push('');

  // Entry type
  if (ttlMs) {
    lines.push('interface MemoryEntry {');
    lines.push(`  record: ${name};`);
    lines.push('  expiresAt: number;');
    lines.push('}');
  } else {
    lines.push('interface MemoryEntry {');
    lines.push(`  record: ${name};`);
    lines.push('}');
  }
  lines.push('');

  // --- Factory function ---
  lines.push(`export function createMemory${name}Adapter(): ${name}Adapter {`);
  lines.push(`  const store = new Map<${pkType}, MemoryEntry>();`);
  lines.push('');

  // isAlive
  if (ttlMs) {
    lines.push('  function isAlive(entry: MemoryEntry): boolean {');
    lines.push('    return Date.now() < entry.expiresAt;');
    lines.push('  }');
    lines.push('');
  }

  // recordVisible (soft-delete)
  if (config.softDelete) {
    const sdField = config.softDelete.field;
    lines.push(`  function recordVisible(record: ${name}): boolean {`);
    if (sdNonNull) {
      lines.push(
        `    const v = (record as Record<string, unknown>)['${sdField}']; return v === null || v === undefined;`,
      );
    } else {
      lines.push(`    return (record as Record<string, unknown>)['${sdField}'] !== '${sdValue}';`);
    }
    lines.push('  }');
    lines.push('');
  }

  // applyDefaults
  lines.push(`  function applyDefaults(input: Create${name}Input): ${name} {`);
  lines.push(`    const record = { ...input } as Record<string, unknown>;`);
  for (const [fieldName, def] of autoDefaultFields) {
    if (def.default === 'uuid') {
      lines.push(
        `    if (record['${fieldName}'] === undefined) record['${fieldName}'] = crypto.randomUUID();`,
      );
    } else if (def.default === 'cuid') {
      lines.push(
        `    if (record['${fieldName}'] === undefined) record['${fieldName}'] = 'c' + Date.now().toString(36) + Math.random().toString(36).slice(2, 8);`,
      );
    } else if (def.default === 'now') {
      lines.push(
        `    if (record['${fieldName}'] === undefined) record['${fieldName}'] = new Date();`,
      );
    }
  }
  for (const [fieldName, def] of literalDefaultFields) {
    const val = typeof def.default === 'string' ? `'${def.default}'` : def.default;
    lines.push(`    if (record['${fieldName}'] === undefined) record['${fieldName}'] = ${val};`);
  }
  lines.push(`    return record as ${name};`);
  lines.push('  }');
  lines.push('');

  // applyOnUpdate
  if (onUpdateFields.length > 0) {
    lines.push(
      `  function applyOnUpdate(input: Record<string, unknown>): Record<string, unknown> {`,
    );
    lines.push('    const result = { ...input };');
    for (const [fieldName] of onUpdateFields) {
      lines.push(`    result['${fieldName}'] = new Date();`);
    }
    lines.push('    return result;');
    lines.push('  }');
    lines.push('');
  }

  // matchesFilter
  lines.push(
    '  function matchesFilter(record: Record<string, unknown>, filter: Record<string, unknown>): boolean {',
  );
  lines.push('    for (const [key, val] of Object.entries(filter)) {');
  lines.push('      if (val === undefined) continue;');
  lines.push("      if (key === 'limit' || key === 'cursor' || key === 'sortDir') continue;");
  lines.push('      const rVal = record[key];');
  lines.push('      if (rVal instanceof Date && val instanceof Date) {');
  lines.push('        if (rVal.getTime() !== val.getTime()) return false;');
  lines.push('      } else if (rVal !== val) return false;');
  lines.push('    }');
  lines.push('    return true;');
  lines.push('  }');
  lines.push('');

  // compareForSort
  const cursorFieldsStr = cursorFields.map(f => `'${f}'`).join(', ');
  lines.push(`  const cursorFields = [${cursorFieldsStr}];`);
  lines.push('');
  lines.push(
    "  function compareForSort(a: Record<string, unknown>, b: Record<string, unknown>, sortDir: 'asc' | 'desc'): number {",
  );
  lines.push('    for (const f of cursorFields) {');
  lines.push('      const aVal = a[f]; const bVal = b[f];');
  lines.push('      if (aVal === bVal) continue;');
  lines.push('      let cmp = 0;');
  lines.push(
    '      if (aVal instanceof Date && bVal instanceof Date) { cmp = aVal.getTime() - bVal.getTime(); }',
  );
  lines.push(
    "      else if (typeof aVal === 'number' && typeof bVal === 'number') { cmp = aVal - bVal; }",
  );
  lines.push('      else { cmp = String(aVal) < String(bVal) ? -1 : 1; }');
  lines.push("      return sortDir === 'desc' ? -cmp : cmp;");
  lines.push('    }');
  lines.push('    return 0;');
  lines.push('  }');
  lines.push('');

  // buildCursorForRecord
  lines.push('  function buildCursorForRecord(record: Record<string, unknown>): string {');
  lines.push('    const values: Record<string, unknown> = {};');
  lines.push('    for (const f of cursorFields) {');
  lines.push('      const val = record[f];');
  lines.push('      values[f] = val instanceof Date ? val.toISOString() : val;');
  lines.push('    }');
  lines.push('    return encodeCursor(values);');
  lines.push('  }');
  lines.push('');

  // parseCursorValues
  const dateFieldNames = new Set(dateFields.map(([n]) => n));
  const cursorDateFields = cursorFields.filter(f => dateFieldNames.has(f));
  lines.push('  function parseCursorValues(cursor: string): Record<string, unknown> {');
  lines.push('    const raw = decodeCursor(cursor);');
  if (cursorDateFields.length > 0) {
    for (const f of cursorDateFields) {
      lines.push(
        `    { const v = raw['${f}']; if (typeof v === 'string') raw['${f}'] = new Date(v); }`,
      );
    }
  }
  lines.push('    return raw;');
  lines.push('  }');
  lines.push('');

  // --- Return adapter ---
  lines.push('  return {');

  // create
  lines.push('    async create(input) {');
  lines.push(`      if (store.size >= ${maxEntries}) {`);
  lines.push('        const firstKey = store.keys().next().value;');
  lines.push('        if (firstKey !== undefined) store.delete(firstKey);');
  lines.push('      }');
  if (ttlMs) {
    lines.push('      // Evict expired entries');
    lines.push('      for (const [pk, entry] of store) {');
    lines.push('        if (!isAlive(entry)) store.delete(pk);');
    lines.push('      }');
  }
  lines.push('      const record = applyDefaults(input);');
  lines.push(`      const pk = (record as Record<string, unknown>)['${pkField}'] as ${pkType};`);
  if (ttlMs) {
    lines.push(`      store.set(pk, { record, expiresAt: Date.now() + ${ttlMs} });`);
  } else {
    lines.push('      store.set(pk, { record });');
  }
  lines.push('      return { ...record };');
  lines.push('    },');
  lines.push('');

  // getById
  lines.push('    async getById(id, filter) {');
  lines.push('      const entry = store.get(id);');
  if (ttlMs) {
    lines.push(
      '      if (!entry || !isAlive(entry)) { if (entry) store.delete(id); return null; }',
    );
  } else {
    lines.push('      if (!entry) return null;');
  }
  if (hasSoftDelete) {
    lines.push('      if (!recordVisible(entry.record)) return null;');
  }
  lines.push(
    '      if (filter && !matchesFilter(entry.record as Record<string, unknown>, filter)) return null;',
  );
  lines.push('      return { ...entry.record };');
  lines.push('    },');
  lines.push('');

  // update
  lines.push('    async update(id, input, filter) {');
  lines.push('      const entry = store.get(id);');
  if (ttlMs) {
    lines.push('      if (!entry || !isAlive(entry)) {');
    lines.push('        if (entry) store.delete(id);');
    lines.push('        return null;');
    lines.push('      }');
  } else {
    lines.push('      if (!entry) return null;');
  }
  if (hasSoftDelete) {
    lines.push('      if (!recordVisible(entry.record)) return null;');
  }
  lines.push(
    '      if (filter && !matchesFilter(entry.record as Record<string, unknown>, filter)) return null;',
  );
  if (onUpdateFields.length > 0) {
    lines.push('      const updatePayload = applyOnUpdate(input as Record<string, unknown>);');
  } else {
    lines.push('      const updatePayload = input as Record<string, unknown>;');
  }
  lines.push('      Object.assign(entry.record, updatePayload);');
  if (ttlMs) {
    lines.push(`      entry.expiresAt = Date.now() + ${ttlMs};`);
  }
  lines.push('      return { ...entry.record };');
  lines.push('    },');
  lines.push('');

  // delete
  lines.push('    async delete(id, filter) {');
  if (config.softDelete) {
    const sdField = config.softDelete.field;
    lines.push('      const entry = store.get(id);');
    if (ttlMs) {
      lines.push(
        '      if (!entry || !isAlive(entry)) { if (entry) store.delete(id); return false; }',
      );
    } else {
      lines.push('      if (!entry) return false;');
    }
    lines.push('      if (!recordVisible(entry.record)) return false;');
    lines.push(
      '      if (filter && !matchesFilter(entry.record as Record<string, unknown>, filter)) return false;',
    );
    if (sdNonNull) {
      lines.push(`      (entry.record as Record<string, unknown>)['${sdField}'] = new Date();`);
    } else {
      lines.push(`      (entry.record as Record<string, unknown>)['${sdField}'] = '${sdValue}';`);
    }
    if (onUpdateFields.length > 0) {
      lines.push('      const onUpdate = applyOnUpdate({});');
      lines.push('      Object.assign(entry.record, onUpdate);');
    }
    lines.push('      return true;');
  } else {
    lines.push('      const entry = store.get(id);');
    if (ttlMs) {
      lines.push(
        '      if (!entry || !isAlive(entry)) { if (entry) store.delete(id); return false; }',
      );
    } else {
      lines.push('      if (!entry) return false;');
    }
    lines.push(
      '      if (filter && !matchesFilter(entry.record as Record<string, unknown>, filter)) return false;',
    );
    lines.push('      store.delete(id);');
    lines.push('      return true;');
  }
  lines.push('    },');
  lines.push('');

  // list
  lines.push('    async list(opts) {');
  lines.push(`      const sortDir = opts?.sortDir ?? '${defaultSortDir}';`);
  lines.push(`      const rawLimit = opts?.limit ?? ${defaultLimit};`);
  lines.push(`      const limit = Math.min(rawLimit, ${maxLimit});`);
  lines.push('');
  lines.push(`      const visible: Array<Record<string, unknown>> = [];`);
  lines.push('      for (const [pk, entry] of store) {');
  if (ttlMs) {
    lines.push('        if (!isAlive(entry)) { store.delete(pk); continue; }');
  }
  if (hasSoftDelete) {
    lines.push('        if (!recordVisible(entry.record)) continue;');
  }
  lines.push(
    '        if (opts && !matchesFilter(entry.record as Record<string, unknown>, opts as Record<string, unknown>)) continue;',
  );
  lines.push('        visible.push(entry.record as Record<string, unknown>);');
  lines.push('      }');
  lines.push('');
  lines.push('      visible.sort((a, b) => compareForSort(a, b, sortDir));');
  lines.push('');
  lines.push('      let startIdx = 0;');
  lines.push('      if (opts?.cursor) {');
  lines.push('        const cursorValues = parseCursorValues(opts.cursor);');
  lines.push('        const cursorIdx = visible.findIndex(r => {');
  lines.push('          for (const f of cursorFields) {');
  lines.push('            const rVal = r[f]; const cVal = cursorValues[f];');
  lines.push('            if (rVal instanceof Date && cVal instanceof Date) {');
  lines.push('              if (rVal.getTime() !== cVal.getTime()) return false;');
  lines.push('            } else if (rVal !== cVal) return false;');
  lines.push('          }');
  lines.push('          return true;');
  lines.push('        });');
  lines.push('        startIdx = cursorIdx >= 0 ? cursorIdx + 1 : 0;');
  lines.push('      }');
  lines.push('');
  lines.push('      const page = visible.slice(startIdx, startIdx + limit + 1);');
  lines.push('      const hasMore = page.length > limit;');
  lines.push(`      const items = page.slice(0, limit).map(r => ({ ...r }) as ${name});`);
  lines.push('');
  lines.push('      let nextCursor: string | undefined;');
  lines.push('      if (hasMore && items.length > 0) {');
  lines.push('        nextCursor = buildCursorForRecord(page[limit - 1]);');
  lines.push('      }');
  lines.push('');
  lines.push('      return { items, nextCursor, hasMore };');
  lines.push('    },');
  lines.push('');

  // clear
  lines.push('    async clear() { store.clear(); },');

  lines.push('  };');
  lines.push('}');
  lines.push('');

  return lines.join('\n');
}
