/**
 * Generator: mongo.ts — Mongoose adapter. Imports only `mongoose`.
 */
import { fieldEntries, isAutoDefault, storageName } from '../lib/naming';
import type { ResolvedEntityConfig } from '../types';

/**
 * Generate the Mongoose/MongoDB adapter implementation source code for an entity.
 *
 * Produces a `createMongo{Name}Adapter(conn: Connection, mongoose): {Name}Adapter`
 * factory function that implements all five CRUD methods using Mongoose models
 * on the provided connection. The generated file imports only `mongoose` type
 * stubs and the sibling `types.ts` and `adapter.ts` files.
 *
 * The implementation includes:
 * - Lazy `getModel()` that either reuses an existing model on the connection or
 *   builds one from an inlined schema definition (including indexes and TTL index).
 * - `applyDefaults()` and (when needed) `applyOnUpdate()` helpers.
 * - Cursor-based pagination via `$gt` / `$lt` query operators on cursor fields.
 * - Soft-delete filtering via a `notDeletedFilter()` helper merged into all
 *   read and write operations when `config.softDelete` is set.
 * - TTL expiry filtering via a `notExpiredFilter()` helper when `config.ttl`
 *   is set.
 * - Primary key mapping: the entity's `_pkField` maps to MongoDB's `_id`.
 * - Per-document conversion helpers (`toMongoDoc` / `fromMongoDoc`) to handle
 *   `_id` remapping and `Date` normalisation.
 *
 * @param config - The resolved entity configuration.
 * @returns A string containing the TypeScript source code for the MongoDB
 *   adapter implementation file.
 *
 * @remarks
 * The `clear()` method is always emitted to support test isolation. It calls
 * `Model.deleteMany({})` and silently swallows errors.
 *
 * @example
 * ```ts
 * import { generateMongo } from '@lastshotlabs/slingshot-entity';
 *
 * const source = generateMongo(config);
 * // Write source to mongo.ts in the entity output directory
 * ```
 */
export function generateMongo(config: ResolvedEntityConfig): string {
  const name = config.name;
  const pkField = config._pkField;
  const collectionName = storageName(config, 'mongo');
  const ttlSeconds = config.ttl?.defaultSeconds;
  const hasSoftDelete = !!config.softDelete;
  const sdNonNull = config.softDelete !== undefined && 'strategy' in config.softDelete;
  const sdValue =
    config.softDelete !== undefined && 'value' in config.softDelete ? config.softDelete.value : '';
  const defaultLimit = config.pagination?.defaultLimit ?? 50;
  const maxLimit = config.pagination?.maxLimit ?? 200;
  const cursorFields = config.pagination?.cursor.fields ?? [pkField];
  const defaultSortDir = config.defaultSort?.direction ?? 'asc';
  const fields = fieldEntries(config);
  const autoDefaultFields = fields.filter(([, def]) => isAutoDefault(def.default));
  const literalDefaultFields = fields.filter(
    ([, def]) => def.default !== undefined && !isAutoDefault(def.default),
  );
  const onUpdateFields = fields.filter(([, def]) => def.onUpdate === 'now');
  const dateFields = new Set(fields.filter(([, def]) => def.type === 'date').map(([n]) => n));

  // Model name from collection
  const modelName = collectionName
    .split(/[_\s-]/)
    .map(s => s.charAt(0).toUpperCase() + s.slice(1))
    .join('');

  const lines: string[] = [
    '// Auto-generated by @lastshotlabs/slingshot-entity — do not edit manually.',
    '',
    "import type { Connection, Schema as MongooseSchemaType } from 'mongoose';",
    `import type { ${name}, Create${name}Input, Update${name}Input } from './types';`,
    `import type { ${name}Adapter, PaginatedResult } from './adapter';`,
    '',
  ];

  // --- Inlined helpers ---
  lines.push('function encodeCursor(values: Record<string, unknown>): string {');
  lines.push("  return Buffer.from(JSON.stringify(values)).toString('base64url');");
  lines.push('}');
  lines.push('');
  lines.push('function decodeCursor(cursor: string): Record<string, unknown> {');
  lines.push(
    "  return JSON.parse(Buffer.from(cursor, 'base64url').toString('utf-8')) as Record<string, unknown>;",
  );
  lines.push('}');
  lines.push('');

  // toMongoDoc / fromMongoDoc
  lines.push(`function toMongoDoc(record: Record<string, unknown>): Record<string, unknown> {`);
  lines.push('  const doc: Record<string, unknown> = {};');
  for (const [fieldName, def] of fields) {
    if (def.primary) {
      lines.push(
        `  if (record['${fieldName}'] !== undefined) doc['_id'] = record['${fieldName}'];`,
      );
    } else if (def.type === 'date') {
      lines.push(
        `  if (record['${fieldName}'] !== undefined) doc['${fieldName}'] = record['${fieldName}'] instanceof Date ? record['${fieldName}'] : new Date(String(record['${fieldName}']));`,
      );
    } else {
      lines.push(
        `  if (record['${fieldName}'] !== undefined) doc['${fieldName}'] = record['${fieldName}'];`,
      );
    }
  }
  lines.push('  return doc;');
  lines.push('}');
  lines.push('');

  lines.push(`function fromMongoDoc(doc: Record<string, unknown>): ${name} {`);
  lines.push('  const record: Record<string, unknown> = {};');
  for (const [fieldName, def] of fields) {
    if (def.primary) {
      lines.push(`  record['${fieldName}'] = doc['_id'];`);
    } else {
      lines.push(
        `  if (doc['${fieldName}'] !== undefined && doc['${fieldName}'] !== null) record['${fieldName}'] = doc['${fieldName}'];`,
      );
    }
  }
  lines.push(`  return record as ${name};`);
  lines.push('}');
  lines.push('');

  // --- Factory function ---
  // Minimal Mongoose model interface — avoids importing full Mongoose types
  lines.push('interface MongoModel {');
  lines.push(
    '  findOne(filter: Record<string, unknown>): { lean(): Promise<Record<string, unknown> | null> };',
  );
  lines.push(
    '  find(filter: Record<string, unknown>): { sort(s: Record<string, number>): { limit(n: number): { lean(): Promise<Array<Record<string, unknown>>> } } };',
  );
  lines.push(
    '  updateOne(filter: Record<string, unknown>, update: Record<string, unknown>, opts?: Record<string, unknown>): Promise<{ modifiedCount: number; matchedCount: number }>;',
  );
  lines.push('  deleteOne(filter: Record<string, unknown>): Promise<{ deletedCount: number }>;');
  lines.push('  deleteMany(filter: Record<string, unknown>): Promise<{ deletedCount: number }>;');
  lines.push('}');
  lines.push('');

  lines.push(
    `export function createMongo${name}Adapter(conn: Connection, mongoose: { Schema: typeof MongooseSchemaType }): ${name}Adapter {`,
  );
  lines.push('  let cachedModel: MongoModel | null = null;');
  lines.push('');

  // getModel
  lines.push('  function getModel(): MongoModel {');
  lines.push(`    if (cachedModel) return cachedModel;`);
  lines.push(`    if ((conn.models as Record<string, MongoModel>)['${modelName}']) {`);
  lines.push(`      cachedModel = (conn.models as Record<string, MongoModel>)['${modelName}'];`);
  lines.push('      return cachedModel;');
  lines.push('    }');
  lines.push('');
  lines.push('    const schemaDef: Record<string, unknown> = {};');
  for (const [fieldName, def] of fields) {
    const mType = mongooseTypeStr(def.type);
    if (def.primary) {
      lines.push(`    schemaDef['_id'] = { type: ${mType}, required: true };`);
    } else {
      const schemaOpts: string[] = [`type: ${mType}`];
      if (!def.optional) schemaOpts.push('required: true');
      if (def.default !== undefined && !isAutoDefault(def.default)) {
        const val = typeof def.default === 'string' ? `'${def.default}'` : def.default;
        schemaOpts.push(`default: ${val}`);
      }
      if (def.enumValues) {
        schemaOpts.push(`enum: [${def.enumValues.map(v => `'${v}'`).join(', ')}]`);
      }
      lines.push(`    schemaDef['${fieldName}'] = { ${schemaOpts.join(', ')} };`);
    }
  }
  if (ttlSeconds) {
    lines.push("    schemaDef['_expiresAt'] = { type: Date, required: true };");
  }
  lines.push('');
  lines.push(
    `    const schema = new mongoose.Schema(schemaDef, { collection: '${collectionName}' });`,
  );

  // Indexes
  if (config.indexes) {
    for (const idx of config.indexes) {
      const spec = idx.fields.map(f => `'${f}': ${idx.direction === 'desc' ? -1 : 1}`).join(', ');
      const opts = idx.unique ? ', { unique: true }' : '';
      lines.push(`    schema.index({ ${spec} }${opts});`);
    }
  }
  if (config.uniques) {
    for (const uq of config.uniques) {
      const spec = uq.fields.map(f => `'${f}': 1`).join(', ');
      lines.push(`    schema.index({ ${spec} }, { unique: true });`);
    }
  }
  if (ttlSeconds) {
    lines.push('    schema.index({ _expiresAt: 1 }, { expireAfterSeconds: 0 });');
  }

  lines.push(`    cachedModel = conn.model('${modelName}', schema) as unknown as MongoModel;`);
  lines.push('    return cachedModel;');
  lines.push('  }');
  lines.push('');

  // applyDefaults
  lines.push(`  function applyDefaults(input: Create${name}Input): Record<string, unknown> {`);
  lines.push('    const record: Record<string, unknown> = { ...input };');
  for (const [fieldName, def] of autoDefaultFields) {
    if (def.default === 'uuid') {
      lines.push(
        `    if (record['${fieldName}'] === undefined) record['${fieldName}'] = crypto.randomUUID();`,
      );
    } else if (def.default === 'cuid') {
      lines.push(
        `    if (record['${fieldName}'] === undefined) record['${fieldName}'] = 'c' + Date.now().toString(36) + Math.random().toString(36).slice(2, 8);`,
      );
    } else if (def.default === 'now') {
      lines.push(
        `    if (record['${fieldName}'] === undefined) record['${fieldName}'] = new Date();`,
      );
    }
  }
  for (const [fieldName, def] of literalDefaultFields) {
    const val = typeof def.default === 'string' ? `'${def.default}'` : def.default;
    lines.push(`    if (record['${fieldName}'] === undefined) record['${fieldName}'] = ${val};`);
  }
  lines.push('    return record;');
  lines.push('  }');
  lines.push('');

  if (onUpdateFields.length > 0) {
    lines.push(
      '  function applyOnUpdate(input: Record<string, unknown>): Record<string, unknown> {',
    );
    lines.push('    const result = { ...input };');
    for (const [fieldName] of onUpdateFields) {
      lines.push(`    result['${fieldName}'] = new Date();`);
    }
    lines.push('    return result;');
    lines.push('  }');
    lines.push('');
  }

  // Base filter helpers
  if (config.softDelete) {
    const sdField = config.softDelete.field;
    lines.push(`  function notDeletedFilter(): Record<string, unknown> {`);
    if (sdNonNull) {
      lines.push(`    return { '${sdField}': null };`);
    } else {
      lines.push(`    return { '${sdField}': { $ne: '${sdValue}' } };`);
    }
    lines.push('  }');
    lines.push('');
  }
  if (ttlSeconds) {
    lines.push('  function notExpiredFilter(): Record<string, unknown> {');
    lines.push('    return { _expiresAt: { $gt: new Date() } };');
    lines.push('  }');
    lines.push('');
  }
  lines.push('  function baseFilter(): Record<string, unknown> {');
  const filterParts: string[] = [];
  if (hasSoftDelete) filterParts.push('...notDeletedFilter()');
  if (ttlSeconds) filterParts.push('...notExpiredFilter()');
  lines.push(`    return { ${filterParts.join(', ')} };`);
  lines.push('  }');
  lines.push('');

  // buildCursorForRecord
  const cursorFieldsStr = cursorFields.map(f => `'${f}'`).join(', ');
  lines.push(`  const cursorFieldNames = [${cursorFieldsStr}];`);
  lines.push('');
  lines.push('  function buildCursorForRecord(record: Record<string, unknown>): string {');
  lines.push('    const values: Record<string, unknown> = {};');
  lines.push('    for (const f of cursorFieldNames) {');
  lines.push('      const val = record[f];');
  lines.push('      values[f] = val instanceof Date ? val.toISOString() : val;');
  lines.push('    }');
  lines.push('    return encodeCursor(values);');
  lines.push('  }');
  lines.push('');

  // --- Return adapter ---
  lines.push('  return {');

  // create
  lines.push('    async create(input) {');
  lines.push('      const Model = getModel();');
  lines.push('      const record = applyDefaults(input);');
  lines.push('      const doc = toMongoDoc(record);');
  if (ttlSeconds) {
    lines.push(`      doc['_expiresAt'] = new Date(Date.now() + ${ttlSeconds * 1000});`);
  }
  lines.push('      await Model.updateOne({ _id: doc._id }, { $set: doc }, { upsert: true });');
  lines.push(`      return { ...record } as ${name};`);
  lines.push('    },');
  lines.push('');

  // getById
  lines.push('    async getById(id, filter) {');
  lines.push('      const Model = getModel();');
  lines.push('      const query: Record<string, unknown> = { _id: id, ...baseFilter() };');
  lines.push('      if (filter) Object.assign(query, filter);');
  lines.push('      const doc = await Model.findOne(query).lean();');
  lines.push('      if (!doc) return null;');
  lines.push('      return fromMongoDoc(doc as Record<string, unknown>);');
  lines.push('    },');
  lines.push('');

  // update
  lines.push('    async update(id, input, filter) {');
  lines.push('      const Model = getModel();');
  if (onUpdateFields.length > 0) {
    lines.push('      const updatePayload = applyOnUpdate(input as Record<string, unknown>);');
  } else {
    lines.push('      const updatePayload = input as Record<string, unknown>;');
  }
  lines.push('      const $set: Record<string, unknown> = {};');
  lines.push('      for (const [key, val] of Object.entries(updatePayload)) {');
  lines.push('        if (val === undefined) continue;');
  // Skip PK
  lines.push(`        if (key === '${pkField}') continue;`);
  lines.push('        $set[key] = val;');
  lines.push('      }');
  if (ttlSeconds) {
    lines.push(`      $set['_expiresAt'] = new Date(Date.now() + ${ttlSeconds * 1000});`);
  }
  lines.push('      const query: Record<string, unknown> = { _id: id, ...baseFilter() };');
  lines.push('      if (filter) Object.assign(query, filter);');
  lines.push(
    "      const result = await Model.findOneAndUpdate(query, { $set }, { returnDocument: 'after' });",
  );
  lines.push(
    '      return result.value ? fromMongoDoc(result.value as Record<string, unknown>) : null;',
  );
  lines.push('    },');
  lines.push('');

  // delete
  lines.push('    async delete(id, filter) {');
  lines.push('      const Model = getModel();');
  if (config.softDelete) {
    const sdField = config.softDelete.field;
    if (sdNonNull) {
      lines.push(`      const $set: Record<string, unknown> = { '${sdField}': new Date() };`);
    } else {
      lines.push(`      const $set: Record<string, unknown> = { '${sdField}': '${sdValue}' };`);
    }
    if (onUpdateFields.length > 0) {
      lines.push('      const onUpdate = applyOnUpdate({});');
      lines.push('      for (const [k, v] of Object.entries(onUpdate)) {');
      lines.push(`        if (k !== '${pkField}') $set[k] = v;`);
      lines.push('      }');
    }
    lines.push('      const query: Record<string, unknown> = { _id: id, ...baseFilter() };');
    lines.push('      if (filter) Object.assign(query, filter);');
    lines.push(
      "      const result = await Model.findOneAndUpdate(query, { $set }, { returnDocument: 'after' });",
    );
    lines.push('      return result.value != null;');
  } else {
    lines.push('      const query: Record<string, unknown> = { _id: id, ...baseFilter() };');
    lines.push('      if (filter) Object.assign(query, filter);');
    lines.push('      const result = await Model.findOneAndDelete(query);');
    lines.push('      return result.value != null;');
  }
  lines.push('    },');
  lines.push('');

  // list
  lines.push('    async list(opts) {');
  lines.push('      const Model = getModel();');
  lines.push(`      const sortDir = opts?.sortDir ?? '${defaultSortDir}';`);
  lines.push(`      const rawLimit = opts?.limit ?? ${defaultLimit};`);
  lines.push(`      const limit = Math.min(rawLimit, ${maxLimit});`);
  lines.push('      const query: Record<string, unknown> = { ...baseFilter() };');
  lines.push('');
  lines.push('      if (opts) {');
  lines.push('        for (const [key, val] of Object.entries(opts as Record<string, unknown>)) {');
  lines.push('          if (val === undefined) continue;');
  lines.push("          if (key === 'limit' || key === 'cursor' || key === 'sortDir') continue;");
  // Known fields check
  const knownFieldSet = fields.map(([n]) => `'${n}'`).join(', ');
  lines.push(`          if (![${knownFieldSet}].includes(key)) continue;`);
  lines.push(`          if (key === '${pkField}') { query['_id'] = val; }`);
  lines.push('          else { query[key] = val; }');
  lines.push('        }');
  lines.push('      }');
  lines.push('');

  // Cursor
  lines.push('      if (opts?.cursor) {');
  lines.push('        const cursorValues = decodeCursor(opts.cursor);');
  lines.push("        const op = sortDir === 'desc' ? '$lt' : '$gt';");
  if (cursorFields.length === 1) {
    const f = cursorFields[0];
    const mongoField = config.fields[f].primary ? '_id' : f;
    const isDate = dateFields.has(f);
    lines.push(`        let cv = cursorValues['${f}'];`);
    if (isDate) lines.push("        if (typeof cv === 'string') cv = new Date(cv);");
    lines.push(`        query['${mongoField}'] = { [op]: cv };`);
  } else {
    lines.push('        const orClauses: Array<Record<string, unknown>> = [];');
    for (let i = 0; i < cursorFields.length; i++) {
      lines.push('        {');
      lines.push('          const clause: Record<string, unknown> = {};');
      for (let j = 0; j < i; j++) {
        const f = cursorFields[j];
        const mongoField = config.fields[f].primary ? '_id' : f;
        const isDate = dateFields.has(f);
        lines.push(`          let cv${j} = cursorValues['${f}'];`);
        if (isDate)
          lines.push(`          if (typeof cv${j} === 'string') cv${j} = new Date(cv${j});`);
        lines.push(`          clause['${mongoField}'] = cv${j};`);
      }
      const f = cursorFields[i];
      const mongoField = config.fields[f].primary ? '_id' : f;
      const isDate = dateFields.has(f);
      lines.push(`          let cvI = cursorValues['${f}'];`);
      if (isDate) lines.push("          if (typeof cvI === 'string') cvI = new Date(cvI);");
      lines.push(`          clause['${mongoField}'] = { [op]: cvI };`);
      lines.push('          orClauses.push(clause);');
      lines.push('        }');
    }
    lines.push("        query['$or'] = orClauses;");
  }
  lines.push('      }');
  lines.push('');

  // Sort spec
  lines.push('      const sortSpec: Record<string, number> = {};');
  for (const f of cursorFields) {
    const mongoField = config.fields[f].primary ? '_id' : f;
    lines.push(`      sortSpec['${mongoField}'] = sortDir === 'desc' ? -1 : 1;`);
  }
  lines.push('');
  lines.push('      const docs = await Model.find(query).sort(sortSpec).limit(limit + 1).lean();');
  lines.push('      const hasMore = docs.length > limit;');
  lines.push('      const pageDocs = docs.slice(0, limit);');
  lines.push(
    '      const items = pageDocs.map((doc: Record<string, unknown>) => fromMongoDoc(doc));',
  );
  lines.push('');
  lines.push('      let nextCursor: string | undefined;');
  lines.push('      if (hasMore && pageDocs.length > 0) {');
  lines.push(
    '        nextCursor = buildCursorForRecord(fromMongoDoc(pageDocs[pageDocs.length - 1] as Record<string, unknown>) as Record<string, unknown>);',
  );
  lines.push('      }');
  lines.push('');
  lines.push('      return { items, nextCursor, hasMore };');
  lines.push('    },');
  lines.push('');

  // clear
  lines.push('    async clear() {');
  lines.push(
    '      try { await getModel().deleteMany({}); } catch { /* Best-effort teardown — collection may already be dropped */ }',
  );
  lines.push('    },');

  lines.push('  };');
  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

/**
 * Map a slingshot field type to its Mongoose schema type constructor string.
 *
 * @param fieldType - The slingshot `FieldDef.type` value (e.g. `'string'`,
 *   `'integer'`, `'json'`, `'string[]'`).
 * @returns The Mongoose constructor expression to embed in a schema definition,
 *   e.g. `'String'`, `'Number'`, `'Boolean'`, `'Date'`,
 *   `'mongoose.Schema.Types.Mixed'`, or `'[String]'`.
 *
 * @remarks
 * Mapping:
 * - `'string'`, `'enum'` → `String`
 * - `'number'`, `'integer'` → `Number`
 * - `'boolean'` → `Boolean`
 * - `'date'` → `Date`
 * - `'json'` → `mongoose.Schema.Types.Mixed`
 * - `'string[]'` → `[String]`
 * - Any unknown type → `String` (safe fallback; catches future field types)
 */
function mongooseTypeStr(fieldType: string): string {
  switch (fieldType) {
    case 'string':
    case 'enum':
      return 'String';
    case 'number':
    case 'integer':
      return 'Number';
    case 'boolean':
      return 'Boolean';
    case 'date':
      return 'Date';
    case 'json':
      return 'mongoose.Schema.Types.Mixed';
    case 'string[]':
      return '[String]';
    default:
      return 'String';
  }
}
