/**
 * Generator: postgres.ts — PostgreSQL adapter. Imports only `pg`.
 */
import { fieldEntries, isAutoDefault, pgColType, storageName, toSnakeCase } from '../lib/naming';
import type { ResolvedEntityConfig } from '../types';

/**
 * Generate the PostgreSQL adapter implementation source code for an entity.
 *
 * Produces a `createPostgres{Name}Adapter(pool: Pool): {Name}Adapter` factory
 * function that implements all five CRUD methods using the `pg` library's
 * connection pool. The generated file imports only `pg` and the sibling
 * `types.ts` and `adapter.ts` files.
 *
 * The implementation includes:
 * - Async `ensureTable()` that runs `CREATE TABLE IF NOT EXISTS` + index DDL
 *   statements once on first use.
 * - `applyDefaults()` and (when needed) `applyOnUpdate()` helpers.
 * - Cursor-based pagination with `$N`-positional parameters, supporting single
 *   or compound cursor fields.
 * - Soft-delete filtering via additional `WHERE` conditions when
 *   `config.softDelete` is set.
 * - TTL filtering on reads when `config.ttl` is set.
 * - Per-field conversion helpers (`domainToPg` / `pgToDomain`) for `date` and
 *   `json` field types.
 * - `INSERT … ON CONFLICT … DO UPDATE SET …` (upsert on PK conflict) for the
 *   `create` method.
 *
 * @param config - The resolved entity configuration.
 * @returns A string containing the TypeScript source code for the PostgreSQL
 *   adapter implementation file.
 *
 * @remarks
 * The `clear()` method is always emitted to support test isolation. It executes
 * `DELETE FROM <table>` without conditions using the pool.
 *
 * @example
 * ```ts
 * import { generatePostgres } from '@lastshotlabs/slingshot-entity';
 *
 * const source = generatePostgres(config);
 * // Write source to postgres.ts in the entity output directory
 * ```
 */
export function generatePostgres(config: ResolvedEntityConfig): string {
  const name = config.name;
  const pkField = config._pkField;
  const pkColumn = toSnakeCase(pkField);
  const table = storageName(config, 'postgres');
  const ttlSeconds = config.ttl?.defaultSeconds;
  const hasSoftDelete = !!config.softDelete;
  const sdConfig = config.softDelete ?? null;
  const sdField = sdConfig ? sdConfig.field : '';
  const sdNonNull = sdConfig !== null && 'strategy' in sdConfig;
  const sdValue = sdConfig !== null && 'value' in sdConfig ? sdConfig.value : '';
  const defaultLimit = config.pagination?.defaultLimit ?? 50;
  const maxLimit = config.pagination?.maxLimit ?? 200;
  const cursorFields = (config.pagination?.cursor != null
    ? config.pagination.cursor.fields
    : undefined) ?? [pkField];
  const defaultSortDir = config.defaultSort?.direction ?? 'asc';
  const fields = fieldEntries(config);
  const autoDefaultFields = fields.filter(([, def]) => isAutoDefault(def.default));
  const literalDefaultFields = fields.filter(
    ([, def]) => def.default !== undefined && !isAutoDefault(def.default),
  );
  const onUpdateFields = fields.filter(([, def]) => def.onUpdate === 'now');

  // Column definitions
  const colDefs: string[] = [];
  for (const [fieldName, def] of fields) {
    const col = toSnakeCase(fieldName);
    const pgType = pgColType(def.type);
    const notNull = !def.optional && !def.primary ? ' NOT NULL' : '';
    const pk = def.primary ? ' PRIMARY KEY NOT NULL' : '';
    colDefs.push(`${col} ${pgType}${pk}${notNull}`);
  }
  if (ttlSeconds) colDefs.push('_expires_at BIGINT NOT NULL');

  const lines: string[] = [
    '// Auto-generated by @lastshotlabs/slingshot-entity — do not edit manually.',
    '',
    "import type { Pool } from 'pg';",
    `import type { ${name}, Create${name}Input, Update${name}Input } from './types';`,
    `import type { ${name}Adapter, PaginatedResult } from './adapter';`,
    '',
  ];

  // --- Inlined helpers ---
  lines.push('function encodeCursor(values: Record<string, unknown>): string {');
  lines.push("  return Buffer.from(JSON.stringify(values)).toString('base64url');");
  lines.push('}');
  lines.push('');
  lines.push('function decodeCursor(cursor: string): Record<string, unknown> {');
  lines.push(
    "  return JSON.parse(Buffer.from(cursor, 'base64url').toString('utf-8')) as Record<string, unknown>;",
  );
  lines.push('}');
  lines.push('');

  // toRow / fromRow (domain ↔ pg)
  const fieldMap = fields.map(([camel, def]) => [camel, toSnakeCase(camel), def] as const);

  lines.push('function domainToPg(val: unknown, fieldName: string): unknown {');
  lines.push('  switch (fieldName) {');
  for (const [fieldName, def] of fields) {
    if (def.type === 'date') {
      lines.push(
        `    case '${fieldName}': return val instanceof Date ? val : typeof val === 'number' ? new Date(val) : typeof val === 'string' ? new Date(val) : val;`,
      );
    } else if (def.type === 'json') {
      lines.push(`    case '${fieldName}': return JSON.stringify(val);`);
    }
  }
  lines.push('    default: return val;');
  lines.push('  }');
  lines.push('}');
  lines.push('');

  lines.push('function pgToDomain(val: unknown, fieldName: string): unknown {');
  lines.push('  switch (fieldName) {');
  for (const [fieldName, def] of fields) {
    if (def.type === 'date') {
      lines.push(
        `    case '${fieldName}': return val instanceof Date ? val : typeof val === 'number' ? new Date(val) : typeof val === 'string' ? new Date(val) : val;`,
      );
    } else if (def.type === 'json') {
      lines.push(
        `    case '${fieldName}': return typeof val === 'string' ? JSON.parse(val) : val;`,
      );
    }
  }
  lines.push('    default: return val;');
  lines.push('  }');
  lines.push('}');
  lines.push('');

  lines.push('function toRow(record: Record<string, unknown>): Record<string, unknown> {');
  lines.push('  const row: Record<string, unknown> = {};');
  for (const [camel, snake] of fieldMap) {
    lines.push(
      `  if (record['${camel}'] !== undefined) row['${snake}'] = domainToPg(record['${camel}'], '${camel}');`,
    );
  }
  lines.push('  return row;');
  lines.push('}');
  lines.push('');

  lines.push(`function fromRow(row: Record<string, unknown>): ${name} {`);
  lines.push('  const record: Record<string, unknown> = {};');
  for (const [camel, snake] of fieldMap) {
    lines.push(
      `  if (row['${snake}'] !== undefined && row['${snake}'] !== null) record['${camel}'] = pgToDomain(row['${snake}'], '${camel}');`,
    );
  }
  lines.push(`  return record as ${name};`);
  lines.push('}');
  lines.push('');

  // --- Factory ---
  lines.push(`export function createPostgres${name}Adapter(pool: Pool): ${name}Adapter {`);
  lines.push(`  const table = '${table}';`);
  lines.push('  let initialized = false;');
  lines.push('  let initializationPromise: Promise<void> | null = null;');
  lines.push('');

  // ensureTable
  lines.push('  async function ensureTable(): Promise<void> {');
  lines.push('    if (initialized) return;');
  lines.push('    if (initializationPromise) return initializationPromise;');
  lines.push('    initializationPromise = (async () => {');
  lines.push("      const client = await pool.connect();");
  lines.push('      try {');
  lines.push("        await client.query('BEGIN');");
  lines.push(
    `        await client.query(\`CREATE TABLE IF NOT EXISTS \${table} (\\n  ${colDefs.join(',\\n  ')}\\n)\`);`,
  );
  if (config.indexes) {
    for (let i = 0; i < config.indexes.length; i++) {
      const idx = config.indexes[i];
      const colList = idx.fields.map(f => toSnakeCase(f)).join(', ');
      const unique = idx.unique ? 'UNIQUE ' : '';
      lines.push(
        `        await client.query(\`CREATE ${unique}INDEX IF NOT EXISTS idx_\${table}_${i} ON \${table} (${colList})\`);`,
      );
    }
  }
  if (config.uniques) {
    for (let i = 0; i < config.uniques.length; i++) {
      const uq = config.uniques[i];
      const colList = uq.fields.map(f => toSnakeCase(f)).join(', ');
      lines.push(
        `        await client.query(\`CREATE UNIQUE INDEX IF NOT EXISTS uidx_\${table}_${i} ON \${table} (${colList})\`);`,
      );
    }
  }
  lines.push("        await client.query('COMMIT');");
  lines.push('      } catch (error) {');
  lines.push('        try {');
  lines.push("          await client.query('ROLLBACK');");
  lines.push('        } catch {');
  lines.push('          // Preserve the original bootstrap failure.');
  lines.push('        }');
  lines.push('        throw error;');
  lines.push('      } finally {');
  lines.push('        client.release();');
  lines.push('      }');
  lines.push('      initialized = true;');
  lines.push('    })();');
  lines.push('    try {');
  lines.push('      await initializationPromise;');
  lines.push('    } finally {');
  lines.push('      initializationPromise = null;');
  lines.push('    }');
  lines.push('  }');
  lines.push('');

  // applyDefaults
  lines.push(`  function applyDefaults(input: Create${name}Input): Record<string, unknown> {`);
  lines.push('    const record: Record<string, unknown> = { ...input };');
  for (const [fieldName, def] of autoDefaultFields) {
    if (def.default === 'uuid') {
      lines.push(
        `    if (record['${fieldName}'] === undefined) record['${fieldName}'] = crypto.randomUUID();`,
      );
    } else if (def.default === 'cuid') {
      lines.push(
        `    if (record['${fieldName}'] === undefined) record['${fieldName}'] = 'c' + Date.now().toString(36) + Math.random().toString(36).slice(2, 8);`,
      );
    } else if (def.default === 'now') {
      lines.push(
        `    if (record['${fieldName}'] === undefined) record['${fieldName}'] = new Date();`,
      );
    }
  }
  for (const [fieldName, def] of literalDefaultFields) {
    const val = typeof def.default === 'string' ? `'${def.default}'` : def.default;
    lines.push(`    if (record['${fieldName}'] === undefined) record['${fieldName}'] = ${val};`);
  }
  lines.push('    return record;');
  lines.push('  }');
  lines.push('');

  if (onUpdateFields.length > 0) {
    lines.push(
      '  function applyOnUpdate(input: Record<string, unknown>): Record<string, unknown> {',
    );
    lines.push('    const result = { ...input };');
    for (const [fieldName] of onUpdateFields) {
      lines.push(`    result['${fieldName}'] = new Date();`);
    }
    lines.push('    return result;');
    lines.push('  }');
    lines.push('');
  }

  if (ttlSeconds) {
    lines.push(`  function expiresAt(): number { return Date.now() + ${ttlSeconds * 1000}; }`);
    lines.push('');
  }

  // buildCursorForRecord
  const cursorFieldsStr = cursorFields.map(f => `'${f}'`).join(', ');
  lines.push(`  const cursorFieldNames = [${cursorFieldsStr}];`);
  lines.push('');
  lines.push('  function buildCursorForRecord(record: Record<string, unknown>): string {');
  lines.push('    const values: Record<string, unknown> = {};');
  lines.push('    for (const f of cursorFieldNames) {');
  lines.push('      const val = record[f];');
  lines.push('      values[f] = val instanceof Date ? val.toISOString() : val;');
  lines.push('    }');
  lines.push('    return encodeCursor(values);');
  lines.push('  }');
  lines.push('');

  // --- Return adapter ---
  lines.push('  return {');

  // create
  lines.push('    async create(input) {');
  lines.push('      await ensureTable();');
  lines.push('      const record = applyDefaults(input);');
  lines.push('      const row = toRow(record);');
  if (ttlSeconds) lines.push("      row['_expires_at'] = expiresAt();");
  lines.push('      const columns = Object.keys(row);');
  lines.push("      const placeholders = columns.map((_, i) => `$${i + 1}`).join(', ');");
  lines.push('      const values = columns.map(c => row[c]);');
  lines.push(`      const nonPkCols = columns.filter(c => c !== '${pkColumn}');`);
  lines.push(`      const onConflict = nonPkCols.length > 0`);
  lines.push(
    `        ? \`ON CONFLICT (${pkColumn}) DO UPDATE SET \${nonPkCols.map(c => \`\${c} = EXCLUDED.\${c}\`).join(', ')}\``,
  );
  lines.push(`        : 'ON CONFLICT (${pkColumn}) DO NOTHING';`);
  lines.push(
    '      await pool.query(`INSERT INTO ${table} (${columns.join(", ")}) VALUES (${placeholders}) ${onConflict}`, values);',
  );
  lines.push(`      return { ...record } as ${name};`);
  lines.push('    },');
  lines.push('');

  // getById
  lines.push('    async getById(id, filter) {');
  lines.push('      await ensureTable();');
  lines.push(`      const conditions: string[] = ['${pkColumn} = $1'];`);
  lines.push('      const params: unknown[] = [id];');
  lines.push('      let paramIdx = 2;');
  if (hasSoftDelete) {
    if (sdNonNull) {
      lines.push(`      conditions.push('${toSnakeCase(sdField)} IS NULL');`);
    } else {
      lines.push(`      conditions.push(\`${toSnakeCase(sdField)} != $\${paramIdx++}\`);`);
      lines.push(`      params.push('${sdValue}');`);
    }
  }
  if (ttlSeconds) {
    lines.push('      conditions.push(`_expires_at > $${paramIdx++}`);');
    lines.push('      params.push(Date.now());');
  }
  lines.push('      if (filter) {');
  lines.push('        const filterRow = toRow(filter);');
  lines.push('        for (const [col, value] of Object.entries(filterRow)) {');
  lines.push('          conditions.push(`${col} = $${paramIdx++}`);');
  lines.push('          params.push(value);');
  lines.push('        }');
  lines.push('      }');
  lines.push("      const where = conditions.join(' AND ');");
  lines.push(
    '      const result = await pool.query(`SELECT * FROM ${table} WHERE ${where}`, params);',
  );
  lines.push('      const row = result.rows[0];');
  lines.push('      if (!row) return null;');
  lines.push('      return fromRow(row);');
  lines.push('    },');
  lines.push('');

  // update
  lines.push('    async update(id, input, filter) {');
  lines.push('      await ensureTable();');
  if (onUpdateFields.length > 0) {
    lines.push('      const updatePayload = applyOnUpdate(input as Record<string, unknown>);');
  } else {
    lines.push('      const updatePayload = input as Record<string, unknown>;');
  }
  lines.push('      const partial = toRow(updatePayload);');
  if (ttlSeconds) lines.push("      partial['_expires_at'] = expiresAt();");
  lines.push('      const entries = Object.entries(partial);');
  lines.push('      if (entries.length === 0) {');
  lines.push(
    `        const current = await pool.query(\`SELECT * FROM \${table} WHERE ${pkColumn} = $1\`, [id]);`,
  );
  lines.push('        const currentRow = current.rows[0];');
  lines.push('        if (!currentRow) return null;');
  lines.push('        if (filter) {');
  lines.push('          const filterRow = toRow(filter);');
  lines.push('          for (const [col, value] of Object.entries(filterRow)) {');
  lines.push(
    '            if ((currentRow as Record<string, unknown>)[col] !== value) return null;',
  );
  lines.push('          }');
  lines.push('        }');
  lines.push('        return fromRow(currentRow);');
  lines.push('      }');
  lines.push('      let paramIdx = 1;');
  lines.push(
    "      const setClauses = entries.map(([col]) => `${col} = $${paramIdx++}`).join(', ');",
  );
  lines.push('      const values: unknown[] = entries.map(([, v]) => v);');
  lines.push(`      const conditions: string[] = [\`${pkColumn} = $\${paramIdx++}\`];`);
  lines.push('      values.push(id);');
  if (hasSoftDelete) {
    if (sdNonNull) {
      lines.push(`      conditions.push('${toSnakeCase(sdField)} IS NULL');`);
    } else {
      lines.push(`      conditions.push(\`${toSnakeCase(sdField)} != $\${paramIdx++}\`);`);
      lines.push(`      values.push('${sdValue}');`);
    }
  }
  if (ttlSeconds) {
    lines.push('      conditions.push(`_expires_at > $${paramIdx++}`);');
    lines.push('      values.push(Date.now());');
  }
  lines.push('      if (filter) {');
  lines.push('        const filterRow = toRow(filter);');
  lines.push('        for (const [col, value] of Object.entries(filterRow)) {');
  lines.push('          conditions.push(`${col} = $${paramIdx++}`);');
  lines.push('          values.push(value);');
  lines.push('        }');
  lines.push('      }');
  lines.push("      const where = conditions.join(' AND ');");
  lines.push(
    '      const result = await pool.query(`UPDATE ${table} SET ${setClauses} WHERE ${where} RETURNING *`, values);',
  );
  lines.push('      const updated = result.rows[0];');
  lines.push('      return updated ? fromRow(updated) : null;');
  lines.push('    },');
  lines.push('');

  // delete
  lines.push('    async delete(id, filter) {');
  lines.push('      await ensureTable();');
  if (hasSoftDelete) {
    if (onUpdateFields.length > 0) {
      lines.push('      const partial = toRow(applyOnUpdate({}));');
    } else {
      lines.push('      const partial: Record<string, unknown> = {};');
    }
    const sdCol = toSnakeCase(sdField);
    if (sdNonNull) {
      lines.push(`      partial['${sdCol}'] = new Date();`);
    } else {
      lines.push(`      partial['${sdCol}'] = '${sdValue}';`);
    }
    lines.push('      const entries = Object.entries(partial);');
    lines.push('      let paramIdx = 1;');
    lines.push(
      "      const setClauses = entries.map(([col]) => `${col} = $${paramIdx++}`).join(', ');",
    );
    lines.push('      const values: unknown[] = entries.map(([, v]) => v);');
    lines.push('      const conditions: string[] = [`' + pkColumn + ' = ${paramIdx++}`];');
    lines.push('      values.push(id);');
    if (sdNonNull) {
      lines.push(`      conditions.push('${sdCol} IS NULL');`);
    } else {
      lines.push("      conditions.push('" + sdCol + " != ${paramIdx++}');");
      lines.push(`      values.push('${sdValue}');`);
    }
    if (ttlSeconds) {
      lines.push('      conditions.push(`_expires_at > $${paramIdx++}`);');
      lines.push('      values.push(Date.now());');
    }
    lines.push('      if (filter) {');
    lines.push('        const filterRow = toRow(filter);');
    lines.push('        for (const [col, value] of Object.entries(filterRow)) {');
    lines.push('          conditions.push(`${col} = $${paramIdx++}`);');
    lines.push('          values.push(value);');
    lines.push('        }');
    lines.push('      }');
    lines.push('      const where = conditions.join(" AND ");');
    lines.push(
      '      const result = await pool.query(`UPDATE ${table} SET ${setClauses} WHERE ${where} RETURNING *`, values);',
    );
    lines.push('      return (result.rows[0] != null);');
  } else {
    lines.push(`      const conditions: string[] = [\`${pkColumn} = $1\`];`);
    lines.push('      const values: unknown[] = [id];');
    if (ttlSeconds) {
      lines.push('      conditions.push(`_expires_at > $2`);');
      lines.push('      values.push(Date.now());');
    }
    lines.push('      if (filter) {');
    lines.push('        const filterRow = toRow(filter);');
    lines.push('        let paramIdx = values.length + 1;');
    lines.push('        for (const [col, value] of Object.entries(filterRow)) {');
    lines.push('          conditions.push(`${col} = $${paramIdx++}`);');
    lines.push('          values.push(value);');
    lines.push('        }');
    lines.push('      }');
    lines.push('      const where = conditions.join(" AND ");');
    lines.push(
      '      const result = await pool.query(`DELETE FROM ${table} WHERE ${where} RETURNING *`, values);',
    );
    lines.push('      return (result.rows[0] != null);');
  }
  lines.push('    },');
  lines.push('');

  // list
  lines.push('    async list(opts) {');
  lines.push('      await ensureTable();');
  lines.push(`      const sortDir = opts?.sortDir ?? '${defaultSortDir}';`);
  lines.push(`      const rawLimit = opts?.limit ?? ${defaultLimit};`);
  lines.push(`      const limit = Math.min(rawLimit, ${maxLimit});`);
  lines.push('      const conditions: string[] = [];');
  lines.push('      const params: unknown[] = [];');
  lines.push('      let paramIdx = 1;');
  if (hasSoftDelete) {
    if (sdNonNull) {
      lines.push(`      conditions.push('${toSnakeCase(sdField)} IS NULL');`);
    } else {
      lines.push(`      conditions.push(\`${toSnakeCase(sdField)} != $\${paramIdx++}\`);`);
      lines.push(`      params.push('${sdValue}');`);
    }
  }
  if (ttlSeconds) {
    lines.push('      conditions.push(`_expires_at > $${paramIdx++}`);');
    lines.push('      params.push(Date.now());');
  }

  // Filter
  lines.push('      if (opts) {');
  lines.push('        for (const [key, val] of Object.entries(opts as Record<string, unknown>)) {');
  lines.push('          if (val === undefined) continue;');
  lines.push("          if (key === 'limit' || key === 'cursor' || key === 'sortDir') continue;");
  lines.push('          const fieldMeta: Record<string, { col: string; type: string }> = {');
  for (const [fieldName, def] of fields) {
    lines.push(
      `            '${fieldName}': { col: '${toSnakeCase(fieldName)}', type: '${def.type}' },`,
    );
  }
  lines.push('          };');
  lines.push('          const meta = fieldMeta[key];');
  lines.push('          if (!meta) continue;');
  lines.push('          conditions.push(`${meta.col} = $${paramIdx++}`);');
  lines.push("          if (meta.type === 'json') params.push(JSON.stringify(val));");
  lines.push(
    "          else if (meta.type === 'date') params.push(val instanceof Date ? val : new Date(String(val)));",
  );
  lines.push('          else params.push(val);');
  lines.push('        }');
  lines.push('      }');

  // Cursor
  lines.push('      if (opts?.cursor) {');
  lines.push('        const cursorValues = decodeCursor(opts.cursor);');
  lines.push("        const op = sortDir === 'desc' ? '<' : '>';");
  if (cursorFields.length === 1) {
    const f = cursorFields[0];
    const col = toSnakeCase(f);
    const isDate = config.fields[f].type === 'date';
    lines.push(`        conditions.push(\`${col} \${op} $\${paramIdx++}\`);`);
    lines.push(`        let cv = cursorValues['${f}'];`);
    if (isDate) {
      lines.push("        if (typeof cv === 'string') cv = new Date(cv);");
    }
    lines.push('        params.push(cv);');
  } else {
    lines.push('        const orClauses: string[] = [];');
    for (let i = 0; i < cursorFields.length; i++) {
      lines.push('        {');
      lines.push('          const parts: string[] = [];');
      for (let j = 0; j < i; j++) {
        const f = cursorFields[j];
        const col = toSnakeCase(f);
        const isDate = config.fields[f].type === 'date';
        lines.push(`          parts.push(\`${col} = $\${paramIdx++}\`);`);
        lines.push(`          let cv${j} = cursorValues['${f}'];`);
        if (isDate)
          lines.push(`          if (typeof cv${j} === 'string') cv${j} = new Date(cv${j});`);
        lines.push(`          params.push(cv${j});`);
      }
      const f = cursorFields[i];
      const col = toSnakeCase(f);
      const isDate = config.fields[f].type === 'date';
      lines.push(`          parts.push(\`${col} \${op} $\${paramIdx++}\`);`);
      lines.push(`          let cvI = cursorValues['${f}'];`);
      if (isDate) lines.push("          if (typeof cvI === 'string') cvI = new Date(cvI);");
      lines.push('          params.push(cvI);');
      lines.push("          orClauses.push(`(${parts.join(' AND ')})`);");
      lines.push('        }');
    }
    lines.push("        conditions.push(`(${orClauses.join(' OR ')})`);");
  }
  lines.push('      }');

  // Query
  lines.push(
    "      const where = conditions.length > 0 ? `WHERE ${conditions.join(' AND ')}` : '';",
  );
  const pgSortCols = cursorFields
    .map(f => `${toSnakeCase(f)} \${sortDir === 'desc' ? 'DESC' : 'ASC'}`)
    .join(', ');
  lines.push('      params.push(limit + 1);');
  lines.push(
    `      const result = await pool.query(\`SELECT * FROM \${table} \${where} ORDER BY ${pgSortCols} LIMIT $\${paramIdx}\`, params);`,
  );
  lines.push('');
  lines.push('      const hasMore = result.rows.length > limit;');
  lines.push('      const pageRows = result.rows.slice(0, limit);');
  lines.push('      const items = pageRows.map((row: Record<string, unknown>) => fromRow(row));');
  lines.push('');
  lines.push('      let nextCursor: string | undefined;');
  lines.push('      if (hasMore && pageRows.length > 0) {');
  lines.push(
    '        nextCursor = buildCursorForRecord(fromRow(pageRows[pageRows.length - 1]) as Record<string, unknown>);',
  );
  lines.push('      }');
  lines.push('');
  lines.push('      return { items, nextCursor, hasMore };');
  lines.push('    },');
  lines.push('');

  // clear
  lines.push('    async clear() {');
  lines.push('      await ensureTable();');
  lines.push('      await pool.query(`DELETE FROM ${table}`);');
  lines.push('    },');

  lines.push('  };');
  lines.push('}');
  lines.push('');

  return lines.join('\n');
}
