/**
 * Generator: redis.ts — Redis adapter with SCAN-based listing.
 * Imports nothing external — expects a minimal Redis client interface.
 */
import { fieldEntries, isAutoDefault, storageName } from '../lib/naming';
import type { ResolvedEntityConfig } from '../types';

/**
 * Generate the Redis adapter implementation source code for an entity.
 *
 * Produces a `createRedis{Name}Adapter(redis: RedisClient, appName: string): {Name}Adapter`
 * factory function that stores entity records as JSON strings keyed by
 * `{prefix}:{appName}:{pk}`. Also exports a minimal `RedisClient` interface
 * that any Redis client (ioredis, Upstash, etc.) can satisfy.
 *
 * The implementation includes:
 * - Namespaced key helpers (`rkey(pk)`) using the entity's storage name and
 *   `appName` to prevent cross-entity key collisions.
 * - `storeRecord()` / `loadRecord()` helpers for serialisation with optional
 *   `EX {ttlSeconds}` when `config.ttl` is set.
 * - `scanAllKeys()` that pages through `SCAN … MATCH {prefix}*` to enumerate
 *   all records for list/filter operations.
 * - In-process filtering and sorting for `list()` (all records are loaded,
 *   sorted, then paginated client-side via cursor).
 * - Soft-delete visibility check via `isVisible()` when `config.softDelete`
 *   is set.
 * - Per-field serialisation helpers (`toRedisRecord` / `fromRedisRecord`) to
 *   convert `Date` fields to/from ISO-8601 strings.
 * - `applyDefaults()` and (when needed) `applyOnUpdate()` helpers.
 *
 * @param config - The resolved entity configuration.
 * @returns A string containing the TypeScript source code for the Redis adapter
 *   implementation file.
 *
 * @remarks
 * Redis listing is inherently O(N) because there is no server-side query.
 * This adapter is appropriate for small-to-medium datasets or use-cases where
 * Redis is specifically desired (e.g. TTL-based tokens).
 *
 * The `clear()` method scans all keys with the entity prefix and deletes them.
 *
 * @example
 * ```ts
 * import { generateRedis } from '@lastshotlabs/slingshot-entity';
 *
 * const source = generateRedis(config);
 * // Write source to redis.ts in the entity output directory
 * ```
 */
export function generateRedis(config: ResolvedEntityConfig): string {
  const name = config.name;
  const pkField = config._pkField;
  const pkType = config.fields[pkField].type === 'string' ? 'string' : 'number';
  const prefix = storageName(config, 'redis');
  const ttlSeconds = config.ttl?.defaultSeconds;
  const hasSoftDelete = !!config.softDelete;
  const sdConfig = config.softDelete ?? null;
  const sdField = sdConfig ? sdConfig.field : '';
  const sdNonNull = sdConfig !== null && 'strategy' in sdConfig;
  const sdValue = sdConfig !== null && 'value' in sdConfig ? sdConfig.value : '';
  const defaultLimit = config.pagination?.defaultLimit ?? 50;
  const maxLimit = config.pagination?.maxLimit ?? 200;
  const cursorFields = (config.pagination?.cursor != null
    ? config.pagination.cursor.fields
    : undefined) ?? [pkField];
  const defaultSortDir = config.defaultSort?.direction ?? 'asc';
  const fields = fieldEntries(config);
  const autoDefaultFields = fields.filter(([, def]) => isAutoDefault(def.default));
  const literalDefaultFields = fields.filter(
    ([, def]) => def.default !== undefined && !isAutoDefault(def.default),
  );
  const onUpdateFields = fields.filter(([, def]) => def.onUpdate === 'now');
  const dateFieldNames = new Set(fields.filter(([, def]) => def.type === 'date').map(([n]) => n));

  const lines: string[] = [
    '// Auto-generated by @lastshotlabs/slingshot-entity — do not edit manually.',
    '',
    `import type { ${name}, Create${name}Input, Update${name}Input } from './types';`,
    `import type { ${name}Adapter, PaginatedResult } from './adapter';`,
    '',
  ];

  // Redis client interface
  lines.push('export interface RedisClient {');
  lines.push('  get(key: string): Promise<string | null>;');
  lines.push(
    '  set(key: string, value: string, ...args: Array<string | number>): Promise<unknown>;',
  );
  lines.push(
    '  eval(script: string, numKeys: number, ...args: Array<string | number>): Promise<unknown>;',
  );
  lines.push('  del(...keys: string[]): Promise<number>;');
  lines.push(
    '  scan(cursor: string | number, ...args: Array<string | number>): Promise<[string, string[]]>;',
  );
  lines.push('}');
  lines.push('');

  // --- Inlined helpers ---
  lines.push('function encodeCursor(values: Record<string, unknown>): string {');
  lines.push("  return Buffer.from(JSON.stringify(values)).toString('base64url');");
  lines.push('}');
  lines.push('');
  lines.push('function decodeCursor(cursor: string): Record<string, unknown> {');
  lines.push(
    "  return JSON.parse(Buffer.from(cursor, 'base64url').toString('utf-8')) as Record<string, unknown>;",
  );
  lines.push('}');
  lines.push('');

  // toRedisRecord / fromRedisRecord
  lines.push('function toRedisRecord(record: Record<string, unknown>): Record<string, unknown> {');
  lines.push('  const out: Record<string, unknown> = {};');
  for (const [fieldName, def] of fields) {
    if (def.type === 'date') {
      lines.push(
        `  if (record['${fieldName}'] !== undefined) { const v = record['${fieldName}']; out['${fieldName}'] = v instanceof Date ? v.toISOString() : v; }`,
      );
    } else {
      lines.push(
        `  if (record['${fieldName}'] !== undefined) out['${fieldName}'] = record['${fieldName}'];`,
      );
    }
  }
  lines.push('  return out;');
  lines.push('}');
  lines.push('');

  lines.push(`function fromRedisRecord(raw: Record<string, unknown>): ${name} {`);
  lines.push('  const record: Record<string, unknown> = {};');
  for (const [fieldName, def] of fields) {
    if (def.type === 'date') {
      lines.push(
        `  { const v = raw['${fieldName}']; if (v !== undefined && v !== null) record['${fieldName}'] = typeof v === 'string' ? new Date(v) : v; }`,
      );
    } else {
      lines.push(
        `  if (raw['${fieldName}'] !== undefined && raw['${fieldName}'] !== null) record['${fieldName}'] = raw['${fieldName}'];`,
      );
    }
  }
  lines.push(`  return record as ${name};`);
  lines.push('}');
  lines.push('');

  // --- Factory function ---
  lines.push(
    `export function createRedis${name}Adapter(redis: RedisClient, appName: string): ${name}Adapter {`,
  );
  lines.push(`  const keyPrefix = '${prefix}:' + appName + ':';`);
  lines.push('');
  lines.push(`  function rkey(pk: ${pkType}): string { return keyPrefix + pk; }`);
  lines.push('');

  // storeRecord / loadRecord
  lines.push('  async function storeRecord(record: Record<string, unknown>): Promise<void> {');
  lines.push(`    const pk = record['${pkField}'] as ${pkType};`);
  lines.push('    const serialised = JSON.stringify(toRedisRecord(record));');
  if (ttlSeconds) {
    lines.push(`    await redis.set(rkey(pk), serialised, 'EX', ${ttlSeconds});`);
  } else {
    lines.push('    await redis.set(rkey(pk), serialised);');
  }
  lines.push('  }');
  lines.push('');

  lines.push(
    `  async function loadRecord(pk: ${pkType}): Promise<Record<string, unknown> | null> {`,
  );
  lines.push('    const raw = await redis.get(rkey(pk));');
  lines.push('    if (!raw) return null;');
  lines.push(
    '    return fromRedisRecord(JSON.parse(raw) as Record<string, unknown>) as Record<string, unknown>;',
  );
  lines.push('  }');
  lines.push('');

  if (hasSoftDelete) {
    lines.push('  function isVisible(record: Record<string, unknown>): boolean {');
    if (sdNonNull) {
      lines.push(`    const v = record['${sdField}']; return v === null || v === undefined;`);
    } else {
      lines.push(`    return record['${sdField}'] !== '${sdValue}';`);
    }
    lines.push('  }');
    lines.push('');
  }

  // applyDefaults
  lines.push(`  function applyDefaults(input: Create${name}Input): Record<string, unknown> {`);
  lines.push('    const record: Record<string, unknown> = { ...input };');
  for (const [fieldName, def] of autoDefaultFields) {
    if (def.default === 'uuid') {
      lines.push(
        `    if (record['${fieldName}'] === undefined) record['${fieldName}'] = crypto.randomUUID();`,
      );
    } else if (def.default === 'cuid') {
      lines.push(
        `    if (record['${fieldName}'] === undefined) record['${fieldName}'] = 'c' + Date.now().toString(36) + Math.random().toString(36).slice(2, 8);`,
      );
    } else if (def.default === 'now') {
      lines.push(
        `    if (record['${fieldName}'] === undefined) record['${fieldName}'] = new Date();`,
      );
    }
  }
  for (const [fieldName, def] of literalDefaultFields) {
    const val = typeof def.default === 'string' ? `'${def.default}'` : def.default;
    lines.push(`    if (record['${fieldName}'] === undefined) record['${fieldName}'] = ${val};`);
  }
  lines.push('    return record;');
  lines.push('  }');
  lines.push('');

  if (onUpdateFields.length > 0) {
    lines.push(
      '  function applyOnUpdate(input: Record<string, unknown>): Record<string, unknown> {',
    );
    lines.push('    const result = { ...input };');
    for (const [fieldName] of onUpdateFields) {
      lines.push(`    result['${fieldName}'] = new Date();`);
    }
    lines.push('    return result;');
    lines.push('  }');
    lines.push('');
  }

  lines.push(
    '  function matchesFilter(record: Record<string, unknown>, filter: Record<string, unknown>): boolean {',
  );
  lines.push('    for (const [key, val] of Object.entries(filter)) {');
  lines.push('      if (val === undefined) continue;');
  lines.push("      if (key === 'limit' || key === 'cursor' || key === 'sortDir') continue;");
  lines.push('      const rVal = record[key];');
  lines.push('      if (rVal instanceof Date && val instanceof Date) {');
  lines.push('        if (rVal.getTime() !== val.getTime()) return false;');
  lines.push('      } else if (rVal !== val) return false;');
  lines.push('    }');
  lines.push('    return true;');
  lines.push('  }');
  lines.push('');

  lines.push(
    `  async function loadMatchingRecord(pk: ${pkType}, filter: Record<string, unknown>): Promise<Record<string, unknown> | null> {`,
  );
  lines.push('    const raw = await redis.eval(');
  lines.push('      \'local raw = redis.call("GET", KEYS[1])\\n\' +');
  lines.push("      'if not raw then return nil end\\n' +");
  lines.push("      'local record = cjson.decode(raw)\\n' +");
  lines.push("      'local filter = cjson.decode(ARGV[1])\\n' +");
  lines.push("      'for key, value in pairs(filter) do\\n' +");
  lines.push("      '  if value ~= cjson.null and record[key] ~= value then\\n' +");
  lines.push("      '    return nil\\n' +");
  lines.push("      '  end\\n' +");
  lines.push("      'end\\n' +");
  lines.push("      'return raw',");
  lines.push('      1,');
  lines.push('      rkey(pk),');
  lines.push('      JSON.stringify(filter),');
  lines.push('    );');
  lines.push('    if (raw === null || raw === undefined) return null;');
  lines.push(
    '    return fromRedisRecord(JSON.parse(String(raw)) as Record<string, unknown>) as Record<string, unknown>;',
  );
  lines.push('  }');
  lines.push('');

  // scanAllKeys
  lines.push('  async function scanAllKeys(): Promise<string[]> {');
  lines.push('    const allKeys: string[] = [];');
  lines.push("    let cursor = '0';");
  lines.push('    do {');
  lines.push(
    "      const [nextCursor, keys] = await redis.scan(cursor, 'MATCH', keyPrefix + '*', 'COUNT', 200);",
  );
  lines.push('      cursor = nextCursor;');
  lines.push('      allKeys.push(...keys);');
  lines.push("    } while (cursor !== '0');");
  lines.push('    return allKeys;');
  lines.push('  }');
  lines.push('');

  // compareForSort
  const cursorFieldsStr = cursorFields.map(f => `'${f}'`).join(', ');
  lines.push(`  const cursorFieldNames = [${cursorFieldsStr}];`);
  lines.push('');
  lines.push(
    "  function compareForSort(a: Record<string, unknown>, b: Record<string, unknown>, sortDir: 'asc' | 'desc'): number {",
  );
  lines.push('    for (const f of cursorFieldNames) {');
  lines.push('      const aVal = a[f]; const bVal = b[f];');
  lines.push('      if (aVal === bVal) continue;');
  lines.push('      let cmp = 0;');
  lines.push(
    '      if (aVal instanceof Date && bVal instanceof Date) { cmp = aVal.getTime() - bVal.getTime(); }',
  );
  lines.push(
    "      else if (typeof aVal === 'number' && typeof bVal === 'number') { cmp = aVal - bVal; }",
  );
  lines.push('      else { cmp = String(aVal) < String(bVal) ? -1 : 1; }');
  lines.push("      return sortDir === 'desc' ? -cmp : cmp;");
  lines.push('    }');
  lines.push('    return 0;');
  lines.push('  }');
  lines.push('');

  lines.push('  function buildCursorForRecord(record: Record<string, unknown>): string {');
  lines.push('    const values: Record<string, unknown> = {};');
  lines.push('    for (const f of cursorFieldNames) {');
  lines.push('      const val = record[f];');
  lines.push('      values[f] = val instanceof Date ? val.toISOString() : val;');
  lines.push('    }');
  lines.push('    return encodeCursor(values);');
  lines.push('  }');
  lines.push('');

  // --- Return adapter ---
  lines.push('  return {');

  // create
  lines.push('    async create(input) {');
  lines.push('      const record = applyDefaults(input);');
  lines.push('      await storeRecord(record);');
  lines.push(`      return { ...record } as ${name};`);
  lines.push('    },');
  lines.push('');

  // getById
  lines.push('    async getById(id, filter) {');
  lines.push(
    '      const record = filter ? await loadMatchingRecord(id, filter) : await loadRecord(id);',
  );
  if (hasSoftDelete) {
    lines.push('      if (!record || !isVisible(record)) return null;');
  } else {
    lines.push('      if (!record) return null;');
  }
  lines.push(`      return { ...record } as ${name};`);
  lines.push('    },');
  lines.push('');

  // update
  lines.push('    async update(id, input, filter) {');
  if (onUpdateFields.length > 0) {
    lines.push('      const updatePayload = applyOnUpdate(input as Record<string, unknown>);');
  } else {
    lines.push('      const updatePayload = input as Record<string, unknown>;');
  }
  lines.push('      if (!filter) {');
  lines.push('        const existing = await loadRecord(id);');
  if (hasSoftDelete) {
    lines.push('        if (!existing || !isVisible(existing)) return null;');
  } else {
    lines.push('        if (!existing) return null;');
  }
  lines.push('        Object.assign(existing, updatePayload);');
  lines.push('        await storeRecord(existing);');
  lines.push(`        return { ...existing } as ${name};`);
  lines.push('      }');
  lines.push('      const raw = await redis.eval(');
  lines.push('        \'local raw = redis.call("GET", KEYS[1])\\n\' +');
  lines.push("        'if not raw then return nil end\\n' +");
  lines.push("        'local record = cjson.decode(raw)\\n' +");
  lines.push("        'local filter = cjson.decode(ARGV[1])\\n' +");
  lines.push("        'for key, value in pairs(filter) do\\n' +");
  lines.push("        '  if value ~= cjson.null and record[key] ~= value then\\n' +");
  lines.push("        '    return nil\\n' +");
  lines.push("        '  end\\n' +");
  lines.push("        'end\\n' +");
  lines.push("        'local patch = cjson.decode(ARGV[2])\\n' +");
  lines.push("        'for key, value in pairs(patch) do\\n' +");
  lines.push("        '  record[key] = value\\n' +");
  lines.push("        'end\\n' +");
  if (ttlSeconds) {
    lines.push(
      `        'redis.call("SET", KEYS[1], cjson.encode(record), "EX", ${ttlSeconds})\\n' +`,
    );
  } else {
    lines.push('        \'redis.call("SET", KEYS[1], cjson.encode(record))\\n\' +');
  }
  lines.push("        'return cjson.encode(record)',");
  lines.push('        1,');
  lines.push('        rkey(id),');
  lines.push('        JSON.stringify(filter),');
  lines.push('        JSON.stringify(updatePayload),');
  lines.push('      );');
  lines.push('      if (raw === null || raw === undefined) return null;');
  lines.push(
    `      return fromRedisRecord(JSON.parse(String(raw)) as Record<string, unknown>) as ${name};`,
  );
  lines.push('    },');
  lines.push('');

  // delete
  lines.push('    async delete(id, filter) {');
  if (hasSoftDelete) {
    lines.push('      if (!filter) {');
    lines.push('        const existing = await loadRecord(id);');
    lines.push('        if (!existing || !isVisible(existing)) return false;');
    if (sdNonNull) {
      lines.push(`        existing['${sdField}'] = new Date().toISOString();`);
    } else {
      lines.push(`        existing['${sdField}'] = '${sdValue}';`);
    }
    if (onUpdateFields.length > 0) {
      lines.push('        const onUpdate = applyOnUpdate({});');
      lines.push('        Object.assign(existing, onUpdate);');
    }
    lines.push('        await storeRecord(existing);');
    lines.push('        return true;');
    lines.push('      }');
    lines.push('      const removed = await redis.eval(');
    lines.push('        \'local raw = redis.call("GET", KEYS[1])\\n\' +');
    lines.push("        'if not raw then return 0 end\\n' +");
    lines.push("        'local record = cjson.decode(raw)\\n' +");
    lines.push("        'local filter = cjson.decode(ARGV[1])\\n' +");
    lines.push("        'for key, value in pairs(filter) do\\n' +");
    lines.push("        '  if value ~= cjson.null and record[key] ~= value then\\n' +");
    lines.push("        '    return 0\\n' +");
    lines.push("        '  end\\n' +");
    lines.push("        'end\\n' +");
    lines.push(`        'record["${sdField}"] = ARGV[2]\\n' +`);
    if (onUpdateFields.length > 0) {
      lines.push("        'local onUpdate = cjson.decode(ARGV[3])\\n' +");
      lines.push("        'for key, value in pairs(onUpdate) do\\n' +");
      lines.push("        '  record[key] = value\\n' +");
      lines.push("        'end\\n' +");
    }
    if (ttlSeconds) {
      lines.push(
        `        'redis.call("SET", KEYS[1], cjson.encode(record), "EX", ${ttlSeconds})\\n' +`,
      );
    } else {
      lines.push('        \'redis.call("SET", KEYS[1], cjson.encode(record))\\n\' +');
    }
    lines.push("        'return 1',");
    lines.push('        1,');
    lines.push('        rkey(id),');
    lines.push('        JSON.stringify(filter),');
    lines.push(`        ${sdNonNull ? 'new Date().toISOString()' : `'${sdValue}'`},`);
    if (onUpdateFields.length > 0) {
      lines.push('        JSON.stringify(applyOnUpdate({}) as Record<string, unknown>),');
    }
    lines.push('      );');
    lines.push('      return Number(removed) === 1;');
  } else {
    lines.push('      if (!filter) {');
    lines.push('        const existing = await loadRecord(id);');
    lines.push('        if (!existing) return false;');
    lines.push('        await redis.del(rkey(id));');
    lines.push('        return true;');
    lines.push('      }');
    lines.push('      const removed = await redis.eval(');
    lines.push('        \'local raw = redis.call("GET", KEYS[1])\\n\' +');
    lines.push("        'if not raw then return 0 end\\n' +");
    lines.push("        'local record = cjson.decode(raw)\\n' +");
    lines.push("        'local filter = cjson.decode(ARGV[1])\\n' +");
    lines.push("        'for key, value in pairs(filter) do\\n' +");
    lines.push("        '  if value ~= cjson.null and record[key] ~= value then\\n' +");
    lines.push("        '    return 0\\n' +");
    lines.push("        '  end\\n' +");
    lines.push("        'end\\n' +");
    lines.push('        \'return redis.call("DEL", KEYS[1])\',');
    lines.push('        1,');
    lines.push('        rkey(id),');
    lines.push('        JSON.stringify(filter),');
    lines.push('      );');
    lines.push('      return Number(removed) > 0;');
  }
  lines.push('    },');
  lines.push('');

  // list
  lines.push('    async list(opts) {');
  lines.push(`      const sortDir = opts?.sortDir ?? '${defaultSortDir}';`);
  lines.push(`      const rawLimit = opts?.limit ?? ${defaultLimit};`);
  lines.push(`      const limit = Math.min(rawLimit, ${maxLimit});`);
  lines.push('');
  lines.push('      const allKeys = await scanAllKeys();');
  lines.push('      const records: Array<Record<string, unknown>> = [];');
  lines.push('');
  lines.push('      for (const key of allKeys) {');
  lines.push('        const raw = await redis.get(key);');
  lines.push('        if (!raw) continue;');
  lines.push(
    '        const record = fromRedisRecord(JSON.parse(raw) as Record<string, unknown>) as Record<string, unknown>;',
  );
  if (hasSoftDelete) {
    lines.push('        if (!isVisible(record)) continue;');
  }
  lines.push('        if (opts) {');
  lines.push('          let matches = true;');
  lines.push(
    '          for (const [key, val] of Object.entries(opts as Record<string, unknown>)) {',
  );
  lines.push('            if (val === undefined) continue;');
  lines.push("            if (key === 'limit' || key === 'cursor' || key === 'sortDir') continue;");
  lines.push('            const rVal = record[key];');
  lines.push('            if (rVal instanceof Date && val instanceof Date) {');
  lines.push('              if (rVal.getTime() !== val.getTime()) { matches = false; break; }');
  lines.push('            } else if (rVal !== val) { matches = false; break; }');
  lines.push('          }');
  lines.push('          if (!matches) continue;');
  lines.push('        }');
  lines.push('        records.push(record);');
  lines.push('      }');
  lines.push('');
  lines.push('      records.sort((a, b) => compareForSort(a, b, sortDir));');
  lines.push('');
  lines.push('      let startIdx = 0;');
  lines.push('      if (opts?.cursor) {');
  lines.push('        const cursorValues = decodeCursor(opts.cursor);');
  // Restore dates in cursor
  const cursorDateFields = cursorFields.filter(f => dateFieldNames.has(f));
  if (cursorDateFields.length > 0) {
    for (const f of cursorDateFields) {
      lines.push(
        `        { const v = cursorValues['${f}']; if (typeof v === 'string') cursorValues['${f}'] = new Date(v); }`,
      );
    }
  }
  lines.push('        const cursorIdx = records.findIndex(r => {');
  lines.push('          for (const f of cursorFieldNames) {');
  lines.push('            const rVal = r[f]; const cVal = cursorValues[f];');
  lines.push('            if (rVal instanceof Date && cVal instanceof Date) {');
  lines.push('              if (rVal.getTime() !== cVal.getTime()) return false;');
  lines.push('            } else if (rVal !== cVal) return false;');
  lines.push('          }');
  lines.push('          return true;');
  lines.push('        });');
  lines.push('        startIdx = cursorIdx >= 0 ? cursorIdx + 1 : 0;');
  lines.push('      }');
  lines.push('');
  lines.push('      const page = records.slice(startIdx, startIdx + limit + 1);');
  lines.push('      const hasMore = page.length > limit;');
  lines.push(`      const items = page.slice(0, limit).map(r => ({ ...r }) as ${name});`);
  lines.push('');
  lines.push('      let nextCursor: string | undefined;');
  lines.push('      if (hasMore && items.length > 0) {');
  lines.push('        nextCursor = buildCursorForRecord(page[limit - 1]);');
  lines.push('      }');
  lines.push('');
  lines.push('      return { items, nextCursor, hasMore };');
  lines.push('    },');
  lines.push('');

  // clear
  lines.push('    async clear() {');
  lines.push('      const allKeys = await scanAllKeys();');
  lines.push('      if (allKeys.length > 0) await redis.del(...allKeys);');
  lines.push('    },');

  lines.push('  };');
  lines.push('}');
  lines.push('');

  return lines.join('\n');
}
