/**
 * Route generator — produces Hono route source code from entity + operations.
 *
 * Pure function: (entityConfig, operations?) → route source code string.
 *
 * The generated file exports a factory function that accepts the adapter
 * and returns an OpenAPIHono router with CRUD + operation routes.
 */
import type { OperationConfig, ResolvedEntityConfig } from '@lastshotlabs/slingshot-core';
import { entityTag, entityToPath, getOpParams, opNameToPath, schemaNames } from './routeHelpers';

/**
 * Generate the Hono route factory source code for an entity.
 *
 * Produces a `create{Name}Routes(adapter)` function that, when called, returns
 * an `OpenAPIHono` router pre-wired with the five standard CRUD endpoints plus
 * one endpoint for each entry in `operations`. The generated code imports only
 * from `@hono/zod-openapi`, `zod`, `@lastshotlabs/slingshot-core`, and the
 * sibling `adapter.ts` and `schemas.ts` files.
 *
 * At module scope (before the factory), the generated file calls `registerSchemas`
 * to register the entity, create-input, and update-input schemas as named OpenAPI
 * components (`{Name}`, `Create{Name}Input`, `Update{Name}Input`). This ensures they
 * appear as `$ref` entries in `components/schemas` rather than being duplicated inline
 * across every route that references them.
 *
 * @param config - The resolved entity configuration (name, primary key, route
 *   config, pagination config).
 * @param operations - Optional map of operation name to `OperationConfig`. Each
 *   entry is delegated to `generateOpRoute()` to produce the appropriate HTTP
 *   endpoint (GET, POST, PATCH, DELETE, HEAD) with validated request/response
 *   schemas.
 * @param options - Optional generation overrides.
 * @param options.routePath - URL path segment override. When set, replaces
 *   `entityToPath(config.name)` in the generated code. Mirrors the runtime
 *   `EntityPluginEntry.routePath` field so generated files reflect actual routes.
 * @returns A string containing the TypeScript source code for the routes file,
 *   including all CRUD routes and any operation routes.
 *
 * @remarks
 * Operations with `kind` `'computedAggregate'`, `'derive'`, `'collection'`, or
 * `'custom'` are emitted as comment placeholders only — these have complex
 * signatures that must be wired manually by plugin authors.
 *
 * @example
 * ```ts
 * import { generateRoutes } from '@lastshotlabs/slingshot-entity';
 *
 * const source = generateRoutes(config, operations, { routePath: 'versions' });
 * // Write source to routes.ts in the entity output directory
 * ```
 */
export function generateRoutes(
  config: ResolvedEntityConfig,
  operations?: Record<string, OperationConfig>,
  options?: { routePath?: string },
): string {
  const name = config.name;
  const path = options?.routePath ?? entityToPath(name);
  const tag = entityTag(name);
  const schemas = schemaNames(name);
  const pkField = config._pkField;
  const pkDef = config.fields[pkField];
  const pkType = pkDef.type === 'string' ? 'z.string()' : 'z.number()';

  const lines: string[] = [];

  // Header
  lines.push(`// Auto-generated by @lastshotlabs/slingshot-entity — do not edit manually.`);
  lines.push(``);
  lines.push(`import { OpenAPIHono } from '@hono/zod-openapi';`);
  lines.push(`import { z } from 'zod';`);
  lines.push(`import { createRoute, registerSchemas } from '@lastshotlabs/slingshot-core';`);
  lines.push(`import type { ${name}Adapter } from './adapter';`);
  lines.push(
    `import { ${schemas.entity}, ${schemas.create}, ${schemas.update}, ${schemas.listOptions} } from './schemas';`,
  );
  lines.push(``);

  // Error schema
  lines.push(
    `const errorSchema = z.object({ error: z.string(), code: z.string().optional(), fields: z.array(z.string()).optional(), requestId: z.string().optional() });`,
  );
  lines.push(``);
  lines.push(`function isDuplicateConstraintError(error: unknown): boolean {`);
  lines.push(`  const err = error as { code?: unknown; message?: unknown };`);
  lines.push(`  const code = typeof err.code === 'string' ? err.code : undefined;`);
  lines.push(`  const message = typeof err.message === 'string' ? err.message : '';`);
  lines.push(
    `  return code === '23505' || code === 'SQLITE_CONSTRAINT' || code === 'SQLITE_CONSTRAINT_UNIQUE' || code === 'SQLITE_CONSTRAINT_PRIMARYKEY' || code === 'SQLITE_CONSTRAINT_PRIMARY_KEY' || code === 'E11000' || /duplicate key value violates unique constraint/i.test(message) || /UNIQUE constraint failed/i.test(message) || /duplicate key error/i.test(message);`,
  );
  lines.push(`}`);
  lines.push(``);
  lines.push(`function duplicateConstraintFields(error: unknown): string[] {`);
  lines.push(
    `  const err = error as { keyPattern?: Record<string, unknown>; keyValue?: Record<string, unknown>; message?: unknown };`,
  );
  lines.push(
    `  if (err.keyPattern && typeof err.keyPattern === 'object') return Object.keys(err.keyPattern);`,
  );
  lines.push(
    `  if (err.keyValue && typeof err.keyValue === 'object') return Object.keys(err.keyValue);`,
  );
  lines.push(`  const message = typeof err.message === 'string' ? err.message : '';`);
  lines.push(`  const sqliteMatch = message.match(/UNIQUE constraint failed:\\s*(.+)$/i);`);
  lines.push(
    `  if (sqliteMatch) return sqliteMatch[1].split(',').map(part => part.trim().replace(/^.*\\./, ''));`,
  );
  lines.push(`  const pgMatch = message.match(/Key \\((.+?)\\)=\\(.+?\\) already exists\\./i);`);
  lines.push(`  if (pgMatch) return pgMatch[1].split(',').map(part => part.trim());`);
  lines.push(`  return [];`);
  lines.push(`}`);
  lines.push(``);
  lines.push(
    `function duplicateConstraintResponse(c: { get: (key: string) => string | undefined; json: (body: unknown, status: number) => unknown }, error: unknown) {`,
  );
  lines.push(`  const requestId = c.get('requestId');`);
  lines.push(`  const fields = duplicateConstraintFields(error);`);
  lines.push(
    `  return c.json({ error: 'Duplicate', code: 'duplicate', fields, ...(requestId ? { requestId } : {}) }, 409);`,
  );
  lines.push(`}`);
  lines.push(``);

  // Register named OpenAPI components so createRoute emits $ref instead of duplicating shapes.
  // Must be at module scope (not inside the factory) so registration happens once at import time.
  lines.push(`registerSchemas({`);
  lines.push(`  ${name}: ${schemas.entity},`);
  lines.push(`  Create${name}Input: ${schemas.create},`);
  lines.push(`  Update${name}Input: ${schemas.update},`);
  lines.push(`});`);
  lines.push(``);

  // Factory function
  lines.push(`export function create${name}Routes(adapter: ${name}Adapter): OpenAPIHono {`);
  lines.push(`  const router = new OpenAPIHono();`);
  lines.push(``);

  // CRUD routes
  generateCrudRoutes(lines, config, name, path, tag, schemas, pkType);

  // Operation routes
  if (operations) {
    for (const [opName, op] of Object.entries(operations)) {
      generateOpRoute(lines, config, opName, op, name, path, tag, schemas);
    }
  }

  lines.push(`  return router;`);
  lines.push(`}`);
  lines.push(``);

  return lines.join('\n');
}

/**
 * Append the five standard CRUD route blocks to `lines`.
 *
 * Generates `POST /{entity}` (create), `GET /{entity}/{id}` (getById),
 * `PATCH /{entity}/{id}` (update), `DELETE /{entity}/{id}` (delete), and
 * `GET /{entity}` (list). Each route uses `router.openapi()` with full
 * request/response Zod schemas.
 *
 * @param lines - Mutable array of source lines to append to.
 * @param config - Resolved entity config (used for field metadata).
 * @param name - Entity name (e.g. `'Message'`).
 * @param path - URL-path segment for the entity (e.g. `'messages'`).
 * @param tag - OpenAPI tag for grouping the routes.
 * @param schemas - Pre-computed schema variable name references.
 * @param pkType - Zod type expression for the primary key (e.g. `'z.string()'`).
 */
function generateCrudRoutes(
  lines: string[],
  config: ResolvedEntityConfig,
  name: string,
  path: string,
  tag: string,
  schemas: ReturnType<typeof schemaNames>,
  pkType: string,
): void {
  // POST /{entity} — create
  lines.push(`  // CRUD: Create`);
  lines.push(`  router.openapi(`);
  lines.push(`    createRoute({`);
  lines.push(`      method: 'post',`);
  lines.push(`      path: '/${path}',`);
  lines.push(`      tags: ['${tag}'],`);
  lines.push(`      summary: 'Create ${name}',`);
  lines.push(
    `      request: { body: { content: { 'application/json': { schema: ${schemas.create} } } } },`,
  );
  lines.push(`      responses: {`);
  lines.push(
    `        201: { content: { 'application/json': { schema: ${schemas.entity} } }, description: 'Created' },`,
  );
  lines.push(
    `        409: { content: { 'application/json': { schema: errorSchema } }, description: 'Conflict' },`,
  );
  lines.push(`      },`);
  lines.push(`    }),`);
  lines.push(`    async c => {`);
  lines.push(`      const input = c.req.valid('json');`);
  lines.push(`      try {`);
  lines.push(`        const result = await adapter.create(input);`);
  lines.push(`        return c.json(result, 201);`);
  lines.push(`      } catch (error) {`);
  lines.push(
    `        if (isDuplicateConstraintError(error)) return duplicateConstraintResponse(c, error);`,
  );
  lines.push(`        throw error;`);
  lines.push(`      }`);
  lines.push(`    },`);
  lines.push(`  );`);
  lines.push(``);

  // GET /{entity}/{id} — getById
  lines.push(`  // CRUD: Get by ID`);
  lines.push(`  router.openapi(`);
  lines.push(`    createRoute({`);
  lines.push(`      method: 'get',`);
  lines.push(`      path: '/${path}/{id}',`);
  lines.push(`      tags: ['${tag}'],`);
  lines.push(`      summary: 'Get ${name} by ID',`);
  lines.push(`      request: { params: z.object({ id: ${pkType} }) },`);
  lines.push(`      responses: {`);
  lines.push(
    `        200: { content: { 'application/json': { schema: ${schemas.entity} } }, description: '${name} found' },`,
  );
  lines.push(
    `        404: { content: { 'application/json': { schema: errorSchema } }, description: 'Not found' },`,
  );
  lines.push(
    `        409: { content: { 'application/json': { schema: errorSchema } }, description: 'Conflict' },`,
  );
  lines.push(`      },`);
  lines.push(`    }),`);
  lines.push(`    async c => {`);
  lines.push(`      const { id } = c.req.valid('param');`);
  lines.push(`      const result = await adapter.getById(id);`);
  lines.push(`      if (!result) return c.json({ error: 'Not found' }, 404);`);
  lines.push(`      return c.json(result);`);
  lines.push(`    },`);
  lines.push(`  );`);
  lines.push(``);

  // PATCH /{entity}/{id} — update
  lines.push(`  // CRUD: Update`);
  lines.push(`  router.openapi(`);
  lines.push(`    createRoute({`);
  lines.push(`      method: 'patch',`);
  lines.push(`      path: '/${path}/{id}',`);
  lines.push(`      tags: ['${tag}'],`);
  lines.push(`      summary: 'Update ${name}',`);
  lines.push(`      request: {`);
  lines.push(`        params: z.object({ id: ${pkType} }),`);
  lines.push(`        body: { content: { 'application/json': { schema: ${schemas.update} } } },`);
  lines.push(`      },`);
  lines.push(`      responses: {`);
  lines.push(
    `        200: { content: { 'application/json': { schema: ${schemas.entity} } }, description: 'Updated' },`,
  );
  lines.push(
    `        404: { content: { 'application/json': { schema: errorSchema } }, description: 'Not found' },`,
  );
  lines.push(`      },`);
  lines.push(`    }),`);
  lines.push(`    async c => {`);
  lines.push(`      const { id } = c.req.valid('param');`);
  lines.push(`      const input = c.req.valid('json');`);
  lines.push(`      try {`);
  lines.push(`        const result = await adapter.update(id, input);`);
  lines.push(`        return c.json(result);`);
  lines.push(`      } catch (error) {`);
  lines.push(
    `        if (isDuplicateConstraintError(error)) return duplicateConstraintResponse(c, error);`,
  );
  lines.push(`        throw error;`);
  lines.push(`      }`);
  lines.push(`    },`);
  lines.push(`  );`);
  lines.push(``);

  // DELETE /{entity}/{id} — delete
  lines.push(`  // CRUD: Delete`);
  lines.push(`  router.openapi(`);
  lines.push(`    createRoute({`);
  lines.push(`      method: 'delete',`);
  lines.push(`      path: '/${path}/{id}',`);
  lines.push(`      tags: ['${tag}'],`);
  lines.push(`      summary: 'Delete ${name}',`);
  lines.push(`      request: { params: z.object({ id: ${pkType} }) },`);
  lines.push(`      responses: {`);
  lines.push(`        204: { description: 'Deleted' },`);
  lines.push(`      },`);
  lines.push(`    }),`);
  lines.push(`    async c => {`);
  lines.push(`      const { id } = c.req.valid('param');`);
  lines.push(`      await adapter.delete(id);`);
  lines.push(`      return c.body(null, 204);`);
  lines.push(`    },`);
  lines.push(`  );`);
  lines.push(``);

  // GET /{entity} — list
  lines.push(`  // CRUD: List`);
  lines.push(`  router.openapi(`);
  lines.push(`    createRoute({`);
  lines.push(`      method: 'get',`);
  lines.push(`      path: '/${path}',`);
  lines.push(`      tags: ['${tag}'],`);
  lines.push(`      summary: 'List ${name}',`);
  lines.push(`      request: { query: ${schemas.listOptions} },`);
  lines.push(`      responses: {`);
  lines.push(
    `        200: { content: { 'application/json': { schema: z.object({ items: z.array(${schemas.entity}), nextCursor: z.string().optional(), hasMore: z.boolean() }) } }, description: 'List result' },`,
  );
  lines.push(`      },`);
  lines.push(`    }),`);
  lines.push(`    async c => {`);
  lines.push(`      const opts = c.req.valid('query');`);
  lines.push(`      const result = await adapter.list(opts);`);
  lines.push(`      return c.json(result);`);
  lines.push(`    },`);
  lines.push(`  );`);
  lines.push(``);
}

/**
 * Append a single operation route block to `lines`.
 *
 * Dispatches on `op.kind` to generate the correct HTTP method, path, request
 * schema, and response schema for the operation type:
 * - `lookup` (one) → `GET /{entity}/{op}/{params}` returning entity or 404.
 * - `lookup` (many) → `GET /{entity}/{op}/{params}` returning paginated list.
 * - `exists` → `HEAD /{entity}/{op}/{params}` returning 200 or 404.
 * - `transition` → `POST /{entity}/{op}` returning entity or 409.
 * - `fieldUpdate` → `PATCH /{entity}/{op}` returning entity or 404.
 * - `batch` → `DELETE` or `POST /{entity}/batch/{op}` returning count.
 * - `search` → `GET /{entity}/search` returning array or paginated list.
 * - `aggregate` → `GET /{entity}/aggregate/{op}` returning unknown.
 * - `upsert` → `PUT /{entity}/{op}` returning entity.
 * - `consume` → `POST /{entity}/consume/{op}` returning entity or boolean.
 *
 * Operations with kinds `'computedAggregate'`, `'derive'`, `'collection'`, and
 * `'custom'` are emitted as comment placeholders only.
 *
 * @param lines - Mutable array of source lines to append to.
 * @param config - Resolved entity config.
 * @param opName - Operation name as declared in the entity config.
 * @param op - The discriminated-union operation config.
 * @param name - Entity name.
 * @param basePath - URL path segment for the entity.
 * @param tag - OpenAPI tag.
 * @param schemas - Pre-computed schema variable name references.
 */
function generateOpRoute(
  lines: string[],
  config: ResolvedEntityConfig,
  opName: string,
  op: OperationConfig,
  name: string,
  basePath: string,
  tag: string,
  schemas: ReturnType<typeof schemaNames>,
): void {
  const opPath = opNameToPath(opName);
  const params = getOpParams(op);

  switch (op.kind) {
    case 'lookup': {
      const paramSchema = params.map(p => `${p}: z.string()`).join(', ');
      if (op.returns === 'one') {
        lines.push(`  // Operation: ${opName} (lookup one)`);
        lines.push(`  router.openapi(`);
        lines.push(`    createRoute({`);
        lines.push(`      method: 'get',`);
        lines.push(`      path: '/${basePath}/${opPath}/{${params.join('}/{')}}',`);
        lines.push(`      tags: ['${tag}'],`);
        lines.push(`      summary: '${opName}',`);
        lines.push(`      request: { params: z.object({ ${paramSchema} }) },`);
        lines.push(`      responses: {`);
        lines.push(
          `        200: { content: { 'application/json': { schema: ${schemas.entity} } }, description: 'Found' },`,
        );
        lines.push(
          `        404: { content: { 'application/json': { schema: errorSchema } }, description: 'Not found' },`,
        );
        lines.push(`      },`);
        lines.push(`    }),`);
        lines.push(`    async c => {`);
        lines.push(`      const params = c.req.valid('param');`);
        lines.push(`      const result = await adapter.${opName}(params);`);
        lines.push(`      if (!result) return c.json({ error: 'Not found' }, 404);`);
        lines.push(`      return c.json(result);`);
        lines.push(`    },`);
        lines.push(`  );`);
      } else {
        lines.push(`  // Operation: ${opName} (lookup many)`);
        lines.push(`  router.openapi(`);
        lines.push(`    createRoute({`);
        lines.push(`      method: 'get',`);
        lines.push(`      path: '/${basePath}/${opPath}/{${params.join('}/{')}}',`);
        lines.push(`      tags: ['${tag}'],`);
        lines.push(`      summary: '${opName}',`);
        lines.push(`      request: { params: z.object({ ${paramSchema} }) },`);
        lines.push(`      responses: {`);
        lines.push(
          `        200: { content: { 'application/json': { schema: z.object({ items: z.array(${schemas.entity}), nextCursor: z.string().optional(), hasMore: z.boolean() }) } }, description: 'List result' },`,
        );
        lines.push(`      },`);
        lines.push(`    }),`);
        lines.push(`    async c => {`);
        lines.push(`      const params = c.req.valid('param');`);
        lines.push(`      const result = await adapter.${opName}(params);`);
        lines.push(`      return c.json(result);`);
        lines.push(`    },`);
        lines.push(`  );`);
      }
      break;
    }

    case 'exists': {
      const paramSchema = params.map(p => `${p}: z.string()`).join(', ');
      lines.push(`  // Operation: ${opName} (exists)`);
      lines.push(`  router.openapi(`);
      lines.push(`    createRoute({`);
      lines.push(`      method: 'head',`);
      lines.push(`      path: '/${basePath}/${opPath}/{${params.join('}/{')}}',`);
      lines.push(`      tags: ['${tag}'],`);
      lines.push(`      summary: '${opName}',`);
      lines.push(`      request: { params: z.object({ ${paramSchema} }) },`);
      lines.push(`      responses: {`);
      lines.push(`        200: { description: 'Exists' },`);
      lines.push(`        404: { description: 'Not found' },`);
      lines.push(`      },`);
      lines.push(`    }),`);
      lines.push(`    async c => {`);
      lines.push(`      const params = c.req.valid('param');`);
      lines.push(`      const exists = await adapter.${opName}(params);`);
      lines.push(`      return exists ? c.body(null, 200) : c.body(null, 404);`);
      lines.push(`    },`);
      lines.push(`  );`);
      break;
    }

    case 'transition': {
      const paramSchema = params.map(p => `${p}: z.string()`).join(', ');
      lines.push(`  // Operation: ${opName} (transition: ${String(op.from)} → ${String(op.to)})`);
      lines.push(`  router.openapi(`);
      lines.push(`    createRoute({`);
      lines.push(`      method: 'post',`);
      lines.push(`      path: '/${basePath}/${opPath}',`);
      lines.push(`      tags: ['${tag}'],`);
      lines.push(`      summary: '${opName}',`);
      lines.push(
        `      request: { body: { content: { 'application/json': { schema: z.object({ ${paramSchema} }) } } } },`,
      );
      lines.push(`      responses: {`);
      lines.push(
        `        200: { content: { 'application/json': { schema: ${schemas.entity} } }, description: 'Transitioned' },`,
      );
      lines.push(
        `        409: { content: { 'application/json': { schema: errorSchema } }, description: 'Precondition failed' },`,
      );
      lines.push(`      },`);
      lines.push(`    }),`);
      lines.push(`    async c => {`);
      lines.push(`      const params = c.req.valid('json');`);
      lines.push(`      try {`);
      lines.push(`        const result = await adapter.${opName}(params);`);
      lines.push(`        if (!result) return c.json({ error: 'Precondition failed' }, 409);`);
      lines.push(`        return c.json(result);`);
      lines.push(`      } catch (error) {`);
      lines.push(
        `        if (isDuplicateConstraintError(error)) return duplicateConstraintResponse(c, error);`,
      );
      lines.push(`        throw error;`);
      lines.push(`      }`);
      lines.push(`    },`);
      lines.push(`  );`);
      break;
    }

    case 'fieldUpdate': {
      const matchParams = params.map(p => `${p}: z.string()`).join(', ');
      const setFields = op.set.map(f => `${f}: z.unknown().optional()`).join(', ');
      lines.push(`  // Operation: ${opName} (fieldUpdate)`);
      lines.push(`  router.openapi(`);
      lines.push(`    createRoute({`);
      lines.push(`      method: 'patch',`);
      lines.push(`      path: '/${basePath}/${opPath}',`);
      lines.push(`      tags: ['${tag}'],`);
      lines.push(`      summary: '${opName}',`);
      lines.push(
        `      request: { body: { content: { 'application/json': { schema: z.object({ ${matchParams}, ${setFields} }) } } } },`,
      );
      lines.push(`      responses: {`);
      lines.push(
        `        200: { content: { 'application/json': { schema: ${schemas.entity} } }, description: 'Updated' },`,
      );
      lines.push(
        `        404: { content: { 'application/json': { schema: errorSchema } }, description: 'Not found' },`,
      );
      lines.push(
        `        409: { content: { 'application/json': { schema: errorSchema } }, description: 'Conflict' },`,
      );
      lines.push(`      },`);
      lines.push(`    }),`);
      lines.push(`    async c => {`);
      lines.push(`      const body = c.req.valid('json');`);
      lines.push(`      const params = { ${params.map(p => `${p}: body.${p}`).join(', ')} };`);
      lines.push(`      const input = { ${op.set.map(f => `${f}: body.${f}`).join(', ')} };`);
      lines.push(`      try {`);
      lines.push(`        const result = await adapter.${opName}(params, input);`);
      lines.push(`        return c.json(result);`);
      lines.push(`      } catch (error) {`);
      lines.push(
        `        if (isDuplicateConstraintError(error)) return duplicateConstraintResponse(c, error);`,
      );
      lines.push(`        throw error;`);
      lines.push(`      }`);
      lines.push(`    },`);
      lines.push(`  );`);
      break;
    }

    case 'batch': {
      const method = op.action === 'delete' ? 'delete' : 'post';
      const paramSchema = params.length > 0 ? params.map(p => `${p}: z.string()`).join(', ') : '';
      lines.push(`  // Operation: ${opName} (batch ${op.action})`);
      lines.push(`  router.openapi(`);
      lines.push(`    createRoute({`);
      lines.push(`      method: '${method}',`);
      lines.push(`      path: '/${basePath}/batch/${opPath}',`);
      lines.push(`      tags: ['${tag}'],`);
      lines.push(`      summary: '${opName}',`);
      if (paramSchema) {
        lines.push(
          `      request: { body: { content: { 'application/json': { schema: z.object({ ${paramSchema} }) } } } },`,
        );
      }
      lines.push(`      responses: {`);
      lines.push(
        `        200: { content: { 'application/json': { schema: z.object({ count: z.number() }) } }, description: 'Batch result' },`,
      );
      lines.push(
        `        409: { content: { 'application/json': { schema: errorSchema } }, description: 'Conflict' },`,
      );
      lines.push(`      },`);
      lines.push(`    }),`);
      lines.push(`    async c => {`);
      if (paramSchema) {
        lines.push(`      const params = c.req.valid('json');`);
      } else {
        lines.push(`      const params = {};`);
      }
      lines.push(`      try {`);
      lines.push(`        const count = await adapter.${opName}(params);`);
      lines.push(`        return c.json({ count });`);
      lines.push(`      } catch (error) {`);
      lines.push(
        `        if (isDuplicateConstraintError(error)) return duplicateConstraintResponse(c, error);`,
      );
      lines.push(`        throw error;`);
      lines.push(`      }`);
      lines.push(`    },`);
      lines.push(`  );`);
      break;
    }

    case 'search': {
      const filterParams = op.filter ? getOpParams(op) : [];
      const queryFields = [`q: z.string()`, `limit: z.coerce.number().optional()`];
      if (op.paginate) queryFields.push(`cursor: z.string().optional()`);
      for (const p of filterParams) queryFields.push(`${p}: z.string().optional()`);
      const responseSchema = op.paginate
        ? `z.object({ items: z.array(${schemas.entity}), nextCursor: z.string().optional(), hasMore: z.boolean() })`
        : `z.array(${schemas.entity})`;
      lines.push(
        `  // Operation: ${opName} (search${op.paginate ? ', paginated' : ''}${filterParams.length > 0 ? ', filtered' : ''})`,
      );
      lines.push(`  router.openapi(`);
      lines.push(`    createRoute({`);
      lines.push(`      method: 'get',`);
      lines.push(`      path: '/${basePath}/search',`);
      lines.push(`      tags: ['${tag}'],`);
      lines.push(`      summary: '${opName}',`);
      lines.push(`      request: { query: z.object({ ${queryFields.join(', ')} }) },`);
      lines.push(`      responses: {`);
      lines.push(
        `        200: { content: { 'application/json': { schema: ${responseSchema} } }, description: 'Search results' },`,
      );
      lines.push(`      },`);
      lines.push(`    }),`);
      lines.push(`    async c => {`);
      lines.push(`      const query = c.req.valid('query');`);
      if (filterParams.length > 0) {
        lines.push(
          `      const filterParams = { ${filterParams.map(p => `${p}: query.${p}`).join(', ')} };`,
        );
        lines.push(
          `      const results = await adapter.${opName}(query.q, filterParams, query.limit${op.paginate ? ', query.cursor' : ''});`,
        );
      } else {
        lines.push(
          `      const results = await adapter.${opName}(query.q, {}${op.paginate ? `, query.limit, query.cursor` : `, query.limit`});`,
        );
      }
      lines.push(`      return c.json(results);`);
      lines.push(`    },`);
      lines.push(`  );`);
      break;
    }

    case 'aggregate': {
      const paramSchema =
        params.length > 0 ? params.map(p => `${p}: z.string().optional()`).join(', ') : '';
      lines.push(`  // Operation: ${opName} (aggregate)`);
      lines.push(`  router.openapi(`);
      lines.push(`    createRoute({`);
      lines.push(`      method: 'get',`);
      lines.push(`      path: '/${basePath}/aggregate/${opPath}',`);
      lines.push(`      tags: ['${tag}'],`);
      lines.push(`      summary: '${opName}',`);
      if (paramSchema) {
        lines.push(`      request: { query: z.object({ ${paramSchema} }) },`);
      }
      lines.push(`      responses: {`);
      lines.push(
        `        200: { content: { 'application/json': { schema: z.unknown() } }, description: 'Aggregate result' },`,
      );
      lines.push(`      },`);
      lines.push(`    }),`);
      lines.push(`    async c => {`);
      if (paramSchema) {
        lines.push(`      const params = c.req.valid('query');`);
      } else {
        lines.push(`      const params = {};`);
      }
      lines.push(`      const result = await adapter.${opName}(params);`);
      lines.push(`      return c.json(result);`);
      lines.push(`    },`);
      lines.push(`  );`);
      break;
    }

    case 'upsert': {
      lines.push(`  // Operation: ${opName} (upsert)`);
      lines.push(`  router.openapi(`);
      lines.push(`    createRoute({`);
      lines.push(`      method: 'put',`);
      lines.push(`      path: '/${basePath}/${opPath}',`);
      lines.push(`      tags: ['${tag}'],`);
      lines.push(`      summary: '${opName}',`);
      lines.push(
        `      request: { body: { content: { 'application/json': { schema: z.record(z.string(), z.unknown()) } } } },`,
      );
      lines.push(`      responses: {`);
      lines.push(
        `        200: { content: { 'application/json': { schema: ${schemas.entity} } }, description: 'Upserted' },`,
      );
      lines.push(
        `        409: { content: { 'application/json': { schema: errorSchema } }, description: 'Conflict' },`,
      );
      lines.push(`      },`);
      lines.push(`    }),`);
      lines.push(`    async c => {`);
      lines.push(`      const input = c.req.valid('json');`);
      lines.push(`      try {`);
      lines.push(`        const result = await adapter.${opName}(input);`);
      lines.push(`        return c.json(result);`);
      lines.push(`      } catch (error) {`);
      lines.push(
        `        if (isDuplicateConstraintError(error)) return duplicateConstraintResponse(c, error);`,
      );
      lines.push(`        throw error;`);
      lines.push(`      }`);
      lines.push(`    },`);
      lines.push(`  );`);
      break;
    }

    case 'consume': {
      const paramSchema = params.map(p => `${p}: z.string()`).join(', ');
      lines.push(`  // Operation: ${opName} (consume)`);
      lines.push(`  router.openapi(`);
      lines.push(`    createRoute({`);
      lines.push(`      method: 'post',`);
      lines.push(`      path: '/${basePath}/consume/${opPath}',`);
      lines.push(`      tags: ['${tag}'],`);
      lines.push(`      summary: '${opName}',`);
      lines.push(
        `      request: { body: { content: { 'application/json': { schema: z.object({ ${paramSchema} }) } } } },`,
      );
      lines.push(`      responses: {`);
      if (op.returns === 'boolean') {
        lines.push(
          `        200: { content: { 'application/json': { schema: z.object({ consumed: z.boolean() }) } }, description: 'Consume result' },`,
        );
      } else {
        lines.push(
          `        200: { content: { 'application/json': { schema: ${schemas.entity}.nullable() } }, description: 'Consumed entity' },`,
        );
      }
      lines.push(
        `        409: { content: { 'application/json': { schema: errorSchema } }, description: 'Conflict' },`,
      );
      lines.push(`      },`);
      lines.push(`    }),`);
      lines.push(`    async c => {`);
      lines.push(`      const params = c.req.valid('json');`);
      lines.push(`      try {`);
      lines.push(`        const result = await adapter.${opName}(params);`);
      if (op.returns === 'boolean') {
        lines.push(`        return c.json({ consumed: result });`);
      } else {
        lines.push(`        return c.json(result);`);
      }
      lines.push(`      } catch (error) {`);
      lines.push(
        `        if (isDuplicateConstraintError(error)) return duplicateConstraintResponse(c, error);`,
      );
      lines.push(`        throw error;`);
      lines.push(`      }`);
      lines.push(`    },`);
      lines.push(`  );`);
      break;
    }

    case 'computedAggregate':
    case 'derive':
    case 'collection':
    case 'custom':
      // These ops have complex signatures — generate a comment placeholder
      // Plugin authors wire these manually using the adapter methods
      lines.push(`  // Operation: ${opName} (${op.kind}) — wire manually`);
      break;
  }

  lines.push(``);
}
