/**
 * Generator: sqlite.ts — Bun SQLite adapter. Imports only `bun:sqlite`.
 */
import {
  fieldEntries,
  isAutoDefault,
  sqliteColType,
  storageName,
  toSnakeCase,
} from '../lib/naming';
import type { ResolvedEntityConfig } from '../types';

/**
 * Generate the Bun SQLite adapter implementation source code for an entity.
 *
 * Produces a `createSqlite{Name}Adapter(db: Database): {Name}Adapter` factory
 * function that implements all five CRUD methods (`create`, `getById`, `update`,
 * `delete`, `list`) using `bun:sqlite`. The generated file imports only
 * `bun:sqlite` and the sibling `types.ts` and `adapter.ts` files.
 *
 * The implementation includes:
 * - Lazy `ensureTable()` that runs `CREATE TABLE IF NOT EXISTS` + all index and
 *   unique index DDL statements once on first use.
 * - `applyDefaults()` that fills `uuid`, `cuid`, and `now` auto-defaults at
 *   insert time.
 * - `applyOnUpdate()` that refreshes `onUpdate: 'now'` date fields at update time.
 * - Cursor-based pagination via base64url-encoded JSON cursors, supporting
 *   single or compound cursor fields.
 * - Soft-delete filtering on `getById`, `update`, `delete`, and `list` when
 *   `config.softDelete` is set.
 * - TTL pruning (removes expired rows on `create` and filters them from reads)
 *   when `config.ttl` is set.
 * - Per-field serialisation helpers (`domainToSqlite` / `sqliteToDomain`) for
 *   `date` → integer, `boolean` → 0/1, `json`/`string[]` → JSON string.
 *
 * @param config - The resolved entity configuration.
 * @returns A string containing the TypeScript source code for the SQLite adapter
 *   implementation file.
 *
 * @remarks
 * The `clear()` method is always emitted to support test isolation. It executes
 * `DELETE FROM <table>` without conditions.
 *
 * @example
 * ```ts
 * import { generateSqlite } from '@lastshotlabs/slingshot-entity';
 *
 * const source = generateSqlite(config);
 * // Write source to sqlite.ts in the entity output directory
 * ```
 */
export function generateSqlite(config: ResolvedEntityConfig): string {
  const name = config.name;
  const pkField = config._pkField;
  const pkColumn = toSnakeCase(pkField);
  const table = storageName(config, 'sqlite');
  const ttlSeconds = config.ttl?.defaultSeconds;
  const hasSoftDelete = !!config.softDelete;
  const sdConfig = config.softDelete ?? null;
  const sdField = sdConfig ? sdConfig.field : '';
  const sdNonNull = sdConfig !== null && 'strategy' in sdConfig;
  const sdValue = sdConfig !== null && 'value' in sdConfig ? sdConfig.value : '';
  const defaultLimit = config.pagination?.defaultLimit ?? 50;
  const maxLimit = config.pagination?.maxLimit ?? 200;
  const cursorFields = (config.pagination?.cursor != null
    ? config.pagination.cursor.fields
    : undefined) ?? [pkField];
  const defaultSortDir = config.defaultSort?.direction ?? 'asc';
  const fields = fieldEntries(config);
  const autoDefaultFields = fields.filter(([, def]) => isAutoDefault(def.default));
  const literalDefaultFields = fields.filter(
    ([, def]) => def.default !== undefined && !isAutoDefault(def.default),
  );
  const onUpdateFields = fields.filter(([, def]) => def.onUpdate === 'now');

  const lines: string[] = [
    '// Auto-generated by @lastshotlabs/slingshot-entity — do not edit manually.',
    '',
    "import type { Database } from 'bun:sqlite';",
    `import type { ${name}, Create${name}Input, Update${name}Input } from './types';`,
    `import type { ${name}Adapter, PaginatedResult } from './adapter';`,
    '',
  ];

  // --- Column definitions for CREATE TABLE ---
  const colDefs: string[] = [];
  for (const [fieldName, def] of fields) {
    const col = toSnakeCase(fieldName);
    const sqlType = sqliteColType(def.type);
    const notNull = !def.optional && !def.primary ? ' NOT NULL' : '';
    const pk = def.primary ? ' PRIMARY KEY NOT NULL' : '';
    colDefs.push(`${col} ${sqlType}${pk}${notNull}`);
  }
  if (ttlSeconds) colDefs.push('_expires_at INTEGER NOT NULL');

  // --- Inlined helpers ---
  lines.push('// --- Inlined helpers ---');
  lines.push('');
  lines.push('function encodeCursor(values: Record<string, unknown>): string {');
  lines.push("  return Buffer.from(JSON.stringify(values)).toString('base64url');");
  lines.push('}');
  lines.push('');
  lines.push('function decodeCursor(cursor: string): Record<string, unknown> {');
  lines.push(
    "  return JSON.parse(Buffer.from(cursor, 'base64url').toString('utf-8')) as Record<string, unknown>;",
  );
  lines.push('}');
  lines.push('');

  // domainToSqlite - per-field transform
  lines.push('function domainToSqlite(val: unknown, fieldName: string): unknown {');
  lines.push('  switch (fieldName) {');
  for (const [fieldName, def] of fields) {
    if (def.type === 'date') {
      lines.push(`    case '${fieldName}': return val instanceof Date ? val.getTime() : val;`);
    } else if (def.type === 'boolean') {
      lines.push(`    case '${fieldName}': return val ? 1 : 0;`);
    } else if (def.type === 'json' || def.type === 'string[]') {
      lines.push(`    case '${fieldName}': return JSON.stringify(val);`);
    }
  }
  lines.push('    default: return val;');
  lines.push('  }');
  lines.push('}');
  lines.push('');

  // sqliteToDomain - per-field transform
  lines.push('function sqliteToDomain(val: unknown, fieldName: string): unknown {');
  lines.push('  switch (fieldName) {');
  for (const [fieldName, def] of fields) {
    if (def.type === 'date') {
      lines.push(
        `    case '${fieldName}': return typeof val === 'number' ? new Date(val) : val instanceof Date ? val : new Date(String(val));`,
      );
    } else if (def.type === 'boolean') {
      lines.push(`    case '${fieldName}': return val === 1 || val === true;`);
    } else if (def.type === 'json' || def.type === 'string[]') {
      lines.push(
        `    case '${fieldName}': return typeof val === 'string' ? JSON.parse(val) : val;`,
      );
    }
  }
  lines.push('    default: return val;');
  lines.push('  }');
  lines.push('}');
  lines.push('');

  // toRow / fromRow using hardcoded field map
  const fieldMap = fields.map(([camel, def]) => [camel, toSnakeCase(camel), def] as const);

  lines.push(`function toRow(record: Record<string, unknown>): Record<string, unknown> {`);
  lines.push('  const row: Record<string, unknown> = {};');
  for (const [camel, snake] of fieldMap) {
    lines.push(
      `  if (record['${camel}'] !== undefined) row['${snake}'] = domainToSqlite(record['${camel}'], '${camel}');`,
    );
  }
  lines.push('  return row;');
  lines.push('}');
  lines.push('');

  lines.push(`function fromRow(row: Record<string, unknown>): ${name} {`);
  lines.push('  const record: Record<string, unknown> = {};');
  for (const [camel, snake] of fieldMap) {
    lines.push(
      `  if (row['${snake}'] !== undefined && row['${snake}'] !== null) record['${camel}'] = sqliteToDomain(row['${snake}'], '${camel}');`,
    );
  }
  lines.push(`  return record as ${name};`);
  lines.push('}');
  lines.push('');

  // --- Factory function ---
  lines.push(`export function createSqlite${name}Adapter(db: Database): ${name}Adapter {`);
  lines.push(`  const table = '${table}';`);
  lines.push('  let initialized = false;');
  lines.push('');

  // ensureTable
  lines.push('  function ensureTable(): void {');
  lines.push('    if (initialized) return;');
  lines.push(
    `    db.run(\`CREATE TABLE IF NOT EXISTS \${table} (\\n  ${colDefs.join(',\\n  ')}\\n)\`);`,
  );

  // Indexes
  if (config.indexes) {
    for (let i = 0; i < config.indexes.length; i++) {
      const idx = config.indexes[i];
      const colList = idx.fields.map(f => toSnakeCase(f)).join(', ');
      const unique = idx.unique ? 'UNIQUE ' : '';
      lines.push(
        `    db.run(\`CREATE ${unique}INDEX IF NOT EXISTS idx_\${table}_${i} ON \${table} (${colList})\`);`,
      );
    }
  }
  if (config.uniques) {
    for (let i = 0; i < config.uniques.length; i++) {
      const uq = config.uniques[i];
      const colList = uq.fields.map(f => toSnakeCase(f)).join(', ');
      lines.push(
        `    db.run(\`CREATE UNIQUE INDEX IF NOT EXISTS uidx_\${table}_${i} ON \${table} (${colList})\`);`,
      );
    }
  }
  lines.push('    initialized = true;');
  lines.push('  }');
  lines.push('');

  // applyDefaults
  lines.push(`  function applyDefaults(input: Create${name}Input): Record<string, unknown> {`);
  lines.push('    const record: Record<string, unknown> = { ...input };');
  for (const [fieldName, def] of autoDefaultFields) {
    if (def.default === 'uuid') {
      lines.push(
        `    if (record['${fieldName}'] === undefined) record['${fieldName}'] = crypto.randomUUID();`,
      );
    } else if (def.default === 'cuid') {
      lines.push(
        `    if (record['${fieldName}'] === undefined) record['${fieldName}'] = 'c' + Date.now().toString(36) + Math.random().toString(36).slice(2, 8);`,
      );
    } else if (def.default === 'now') {
      lines.push(
        `    if (record['${fieldName}'] === undefined) record['${fieldName}'] = new Date();`,
      );
    }
  }
  for (const [fieldName, def] of literalDefaultFields) {
    const val = typeof def.default === 'string' ? `'${def.default}'` : def.default;
    lines.push(`    if (record['${fieldName}'] === undefined) record['${fieldName}'] = ${val};`);
  }
  lines.push('    return record;');
  lines.push('  }');
  lines.push('');

  if (onUpdateFields.length > 0) {
    lines.push(
      '  function applyOnUpdate(input: Record<string, unknown>): Record<string, unknown> {',
    );
    lines.push('    const result = { ...input };');
    for (const [fieldName] of onUpdateFields) {
      lines.push(`    result['${fieldName}'] = new Date();`);
    }
    lines.push('    return result;');
    lines.push('  }');
    lines.push('');
  }

  if (ttlSeconds) {
    lines.push(`  function expiresAt(): number { return Date.now() + ${ttlSeconds * 1000}; }`);
    lines.push(
      `  function pruneExpired(): void { db.run(\`DELETE FROM \${table} WHERE _expires_at < ?\`, [Date.now()]); }`,
    );
    lines.push('');
  }

  // buildCursorForRecord
  const cursorFieldsStr = cursorFields.map(f => `'${f}'`).join(', ');
  lines.push(`  const cursorFieldNames = [${cursorFieldsStr}];`);
  lines.push(
    `  const cursorColNames = [${cursorFields.map(f => `'${toSnakeCase(f)}'`).join(', ')}];`,
  );
  lines.push('');
  lines.push('  function buildCursorForRecord(record: Record<string, unknown>): string {');
  lines.push('    const values: Record<string, unknown> = {};');
  lines.push('    for (const f of cursorFieldNames) {');
  lines.push('      const val = record[f];');
  lines.push('      values[f] = val instanceof Date ? val.toISOString() : val;');
  lines.push('    }');
  lines.push('    return encodeCursor(values);');
  lines.push('  }');
  lines.push('');

  // --- Return adapter ---
  lines.push('  return {');

  // create
  lines.push('    async create(input) {');
  lines.push('      ensureTable();');
  if (ttlSeconds) lines.push('      pruneExpired();');
  lines.push('      const record = applyDefaults(input);');
  lines.push('      const row = toRow(record);');
  if (ttlSeconds) lines.push("      row['_expires_at'] = expiresAt();");
  lines.push('      const columns = Object.keys(row);');
  lines.push("      const placeholders = columns.map(() => '?').join(', ');");
  lines.push('      const values = columns.map(c => row[c]);');
  lines.push(
    '      db.run(`INSERT OR REPLACE INTO ${table} (${columns.join(", ")}) VALUES (${placeholders})`, values);',
  );
  lines.push(`      return fromRow(row);`);
  lines.push('    },');
  lines.push('');

  // getById
  lines.push('    async getById(id, filter) {');
  lines.push('      ensureTable();');
  lines.push(`      const conditions: string[] = ["${pkColumn} = ?"];`);
  lines.push('      const params: unknown[] = [id];');
  if (hasSoftDelete) {
    if (sdNonNull) {
      lines.push(`      conditions.push('${toSnakeCase(sdField)} IS NULL');`);
    } else {
      lines.push(`      conditions.push('${toSnakeCase(sdField)} != ?');`);
      lines.push(`      params.push('${sdValue}');`);
    }
  }
  if (ttlSeconds) {
    lines.push("      conditions.push('_expires_at > ?');");
    lines.push('      params.push(Date.now());');
  }
  lines.push('      if (filter) {');
  lines.push('        const filterRow = toRow(filter);');
  lines.push('        for (const [col, value] of Object.entries(filterRow)) {');
  lines.push('          conditions.push(`${col} = ?`);');
  lines.push('          params.push(value);');
  lines.push('        }');
  lines.push('      }');
  lines.push("      const whereClause = conditions.join(' AND ');");
  lines.push(
    '      const row = db.query<Record<string, unknown>>(`SELECT * FROM ${table} WHERE ${whereClause}`).get(...params);',
  );
  lines.push('      if (!row) return null;');
  lines.push('      return fromRow(row);');
  lines.push('    },');
  lines.push('');

  // update
  lines.push('    async update(id, input, filter) {');
  lines.push('      ensureTable();');
  lines.push(`      const conditions: string[] = ["${pkColumn} = ?"];`);
  lines.push('      const params: unknown[] = [id];');
  if (hasSoftDelete) {
    if (sdNonNull) {
      lines.push(`      conditions.push('${toSnakeCase(sdField)} IS NULL');`);
    } else {
      lines.push(`      conditions.push('${toSnakeCase(sdField)} != ?');`);
      lines.push(`      params.push('${sdValue}');`);
    }
  }
  if (ttlSeconds) {
    lines.push("      conditions.push('_expires_at > ?');");
    lines.push('      params.push(Date.now());');
  }
  lines.push('      if (filter) {');
  lines.push('        const filterRow = toRow(filter);');
  lines.push('        for (const [col, value] of Object.entries(filterRow)) {');
  lines.push('          conditions.push(`${col} = ?`);');
  lines.push('          params.push(value);');
  lines.push('        }');
  lines.push('      }');
  lines.push("      const whereClause = conditions.join(' AND ');");
  if (onUpdateFields.length > 0) {
    lines.push('      const updatePayload = applyOnUpdate(input as Record<string, unknown>);');
  } else {
    lines.push('      const updatePayload = input as Record<string, unknown>;');
  }
  lines.push('      const partial = toRow(updatePayload);');
  if (ttlSeconds) lines.push("      partial['_expires_at'] = expiresAt();");
  lines.push('      const entries = Object.entries(partial);');
  lines.push('      if (entries.length === 0) {');
  lines.push(
    '        const current = db.query<Record<string, unknown>>(`SELECT * FROM ${table} WHERE ${whereClause}`).get(...params);',
  );
  lines.push('        return current ? fromRow(current) : null;');
  lines.push('      }');
  lines.push("      const setClauses = entries.map(([col]) => `${col} = ?`).join(', ');");
  lines.push('      const values = [...entries.map(([, v]) => v), ...params];');
  lines.push(
    '      const result = db.query<Record<string, unknown>>(`UPDATE ${table} SET ${setClauses} WHERE ${whereClause} RETURNING *`).get(...values);',
  );
  lines.push('      return result ? fromRow(result) : null;');
  lines.push('    },');
  lines.push('');

  // delete
  lines.push('    async delete(id, filter) {');
  lines.push('      ensureTable();');
  if (hasSoftDelete) {
    const sdCol = toSnakeCase(sdField);
    if (sdNonNull) {
      lines.push(`      const partial: Record<string, unknown> = { '${sdCol}': Date.now() };`);
    } else {
      lines.push(`      const partial: Record<string, unknown> = { '${sdCol}': '${sdValue}' };`);
    }
    if (onUpdateFields.length > 0) {
      lines.push('      const onUpdate = toRow(applyOnUpdate({}));');
      lines.push('      Object.assign(partial, onUpdate);');
    }
    lines.push('      const entries = Object.entries(partial);');
    lines.push("      const setClauses = entries.map(([col]) => `${col} = ?`).join(', ');");
    lines.push(`      const conditions: string[] = ["${pkColumn} = ?"];`);
    lines.push('      const values = [...entries.map(([, v]) => v), id];');
    if (sdNonNull) {
      lines.push(`      conditions.push('${sdCol} IS NULL');`);
    } else {
      lines.push(`      conditions.push('${sdCol} != ?');`);
      lines.push(`      values.push('${sdValue}');`);
    }
    if (ttlSeconds) {
      lines.push("      conditions.push('_expires_at > ?');");
      lines.push('      values.push(Date.now());');
    }
    lines.push('      if (filter) {');
    lines.push('        const filterRow = toRow(filter);');
    lines.push('        for (const [col, value] of Object.entries(filterRow)) {');
    lines.push('          conditions.push(`${col} = ?`);');
    lines.push('          values.push(value);');
    lines.push('        }');
    lines.push('      }');
    lines.push("      const whereClause = conditions.join(' AND ');");
    lines.push(
      '      const result = db.query<Record<string, unknown>>(`UPDATE ${table} SET ${setClauses} WHERE ${whereClause} RETURNING *`).get(...values);',
    );
    lines.push('      return !!result;');
  } else {
    lines.push(`      const conditions: string[] = ["${pkColumn} = ?"];`);
    lines.push('      const values: unknown[] = [id];');
    if (ttlSeconds) {
      lines.push("      conditions.push('_expires_at > ?');");
      lines.push('      values.push(Date.now());');
    }
    lines.push('      if (filter) {');
    lines.push('        const filterRow = toRow(filter);');
    lines.push('        for (const [col, value] of Object.entries(filterRow)) {');
    lines.push('          conditions.push(`${col} = ?`);');
    lines.push('          values.push(value);');
    lines.push('        }');
    lines.push('      }');
    lines.push("      const whereClause = conditions.join(' AND ');");
    lines.push(
      '      const result = db.query<Record<string, unknown>>(`DELETE FROM ${table} WHERE ${whereClause} RETURNING *`).get(...values);',
    );
    lines.push('      return !!result;');
  }
  lines.push('    },');
  lines.push('');

  // list
  lines.push('    async list(opts) {');
  lines.push('      ensureTable();');
  lines.push(`      const sortDir = opts?.sortDir ?? '${defaultSortDir}';`);
  lines.push(`      const rawLimit = opts?.limit ?? ${defaultLimit};`);
  lines.push(`      const limit = Math.min(rawLimit, ${maxLimit});`);
  lines.push('      const conditions: string[] = [];');
  lines.push('      const params: unknown[] = [];');
  if (hasSoftDelete) {
    if (sdNonNull) {
      lines.push(`      conditions.push("${toSnakeCase(sdField)} IS NULL");`);
    } else {
      lines.push(`      conditions.push("${toSnakeCase(sdField)} != ?");`);
      lines.push(`      params.push('${sdValue}');`);
    }
  }
  if (ttlSeconds) {
    lines.push('      conditions.push("_expires_at > ?");');
    lines.push('      params.push(Date.now());');
  }

  // Filter params
  lines.push('      if (opts) {');
  lines.push('        for (const [key, val] of Object.entries(opts as Record<string, unknown>)) {');
  lines.push('          if (val === undefined) continue;');
  lines.push("          if (key === 'limit' || key === 'cursor' || key === 'sortDir') continue;");

  // Build a set of known field names and their snake_case/types
  lines.push('          const fieldMeta: Record<string, { col: string; type: string }> = {');
  for (const [fieldName, def] of fields) {
    lines.push(
      `            '${fieldName}': { col: '${toSnakeCase(fieldName)}', type: '${def.type}' },`,
    );
  }
  lines.push('          };');
  lines.push('          const meta = fieldMeta[key];');
  lines.push('          if (!meta) continue;');
  lines.push('          conditions.push(`${meta.col} = ?`);');
  lines.push(
    "          if (meta.type === 'json' || meta.type === 'string[]') params.push(JSON.stringify(val));",
  );
  lines.push(
    "          else if (meta.type === 'date') params.push(val instanceof Date ? val.getTime() : val);",
  );
  lines.push("          else if (meta.type === 'boolean') params.push(val ? 1 : 0);");
  lines.push('          else params.push(val);');
  lines.push('        }');
  lines.push('      }');

  // Cursor
  lines.push('      if (opts?.cursor) {');
  lines.push('        const cursorValues = decodeCursor(opts.cursor);');
  lines.push("        const op = sortDir === 'desc' ? '<' : '>';");
  if (cursorFields.length === 1) {
    const f = cursorFields[0];
    const col = toSnakeCase(f);
    const isDate = config.fields[f].type === 'date';
    lines.push(`        conditions.push(\`${col} \${op} ?\`);`);
    lines.push(`        const cv = cursorValues['${f}'];`);
    if (isDate) {
      lines.push(
        "        params.push(typeof cv === 'string' ? new Date(cv).getTime() : cv instanceof Date ? cv.getTime() : cv);",
      );
    } else {
      lines.push('        params.push(cv);');
    }
  } else {
    lines.push('        const orClauses: string[] = [];');
    for (let i = 0; i < cursorFields.length; i++) {
      lines.push(`        {`);
      lines.push('          const parts: string[] = [];');
      for (let j = 0; j < i; j++) {
        const f = cursorFields[j];
        const col = toSnakeCase(f);
        const isDate = config.fields[f].type === 'date';
        lines.push(`          parts.push('${col} = ?');`);
        lines.push(`          const cv${j} = cursorValues['${f}'];`);
        if (isDate) {
          lines.push(
            `          params.push(typeof cv${j} === 'string' ? new Date(String(cv${j})).getTime() : cv${j} instanceof Date ? cv${j}.getTime() : cv${j});`,
          );
        } else {
          lines.push(`          params.push(cv${j});`);
        }
      }
      const f = cursorFields[i];
      const col = toSnakeCase(f);
      const isDate = config.fields[f].type === 'date';
      lines.push(`          parts.push(\`${col} \${op} ?\`);`);
      lines.push(`          const cvI = cursorValues['${f}'];`);
      if (isDate) {
        lines.push(
          "          params.push(typeof cvI === 'string' ? new Date(String(cvI)).getTime() : cvI instanceof Date ? cvI.getTime() : cvI);",
        );
      } else {
        lines.push('          params.push(cvI);');
      }
      lines.push("          orClauses.push(`(${parts.join(' AND ')})`);");
      lines.push('        }');
    }
    lines.push("        conditions.push(`(${orClauses.join(' OR ')})`);");
  }
  lines.push('      }');

  // Build query
  lines.push(
    "      const where = conditions.length > 0 ? `WHERE ${conditions.join(' AND ')}` : '';",
  );
  const sortColsStr = cursorFields
    .map(f => `${toSnakeCase(f)} \${sortDir === 'desc' ? 'DESC' : 'ASC'}`)
    .join(', ');
  lines.push('      params.push(limit + 1);');
  lines.push(
    `      const rows = db.query<Record<string, unknown>>(\`SELECT * FROM \${table} \${where} ORDER BY ${sortColsStr} LIMIT ?\`).all(...params);`,
  );
  lines.push('');
  lines.push('      const hasMore = rows.length > limit;');
  lines.push('      const pageRows = rows.slice(0, limit);');
  lines.push('      const items = pageRows.map(row => fromRow(row));');
  lines.push('');
  lines.push('      let nextCursor: string | undefined;');
  lines.push('      if (hasMore && pageRows.length > 0) {');
  lines.push(
    '        nextCursor = buildCursorForRecord(fromRow(pageRows[pageRows.length - 1]) as Record<string, unknown>);',
  );
  lines.push('      }');
  lines.push('');
  lines.push('      return { items, nextCursor, hasMore };');
  lines.push('    },');
  lines.push('');

  // clear
  lines.push('    async clear() {');
  lines.push('      ensureTable();');
  lines.push('      db.run(`DELETE FROM ${table}`);');
  lines.push('    },');

  lines.push('  };');
  lines.push('}');
  lines.push('');

  return lines.join('\n');
}
