/**
 * Generator: types.ts — plain TypeScript interfaces, zero imports.
 */
import { fieldEntries, isAutoDefault, tsType } from '../lib/naming';
import type { ResolvedEntityConfig } from '../types';

/**
 * Generate the TypeScript type declaration source code for an entity.
 *
 * Produces three named interface exports and one type alias:
 * - `{Name}` — the full entity interface (all fields with their exact types and
 *   optional markers).
 * - `Create{Name}Input` — creation input interface (excludes auto-default and
 *   `onUpdate` fields; fields with literal defaults are optional).
 * - `Update{Name}Input` — partial update input interface (all mutable,
 *   non-`onUpdate` fields as optional).
 * - `{Name}Id` — type alias for the primary key type (`string` or `number`).
 *
 * The generated file has zero imports and no external dependencies.
 *
 * @param config - The resolved entity configuration containing field definitions
 *   and primary key info.
 * @returns A string containing the TypeScript source code for the types file.
 *
 * @remarks
 * - Immutable fields (including the primary key by default) are included in the
 *   full entity interface but excluded from `Update{Name}Input`.
 * - Fields with `onUpdate: 'now'` are excluded from both `Create{Name}Input`
 *   and `Update{Name}Input` since they are managed automatically.
 *
 * @example
 * ```ts
 * import { generateTypes } from '@lastshotlabs/slingshot-entity';
 *
 * const source = generateTypes(config);
 * // Write source to types.ts in the entity output directory
 * ```
 */
export function generateTypes(config: ResolvedEntityConfig): string {
  const name = config.name;
  const fields = fieldEntries(config);
  const pkField = config._pkField;

  const lines: string[] = [
    '// Auto-generated by @lastshotlabs/slingshot-entity — do not edit manually.',
    '',
  ];

  // --- Entity interface ---
  lines.push(`export interface ${name} {`);
  for (const [fieldName, def] of fields) {
    const opt = def.optional ? '?' : '';
    lines.push(`  ${fieldName}${opt}: ${tsType(def)};`);
  }
  lines.push('}');
  lines.push('');

  // --- CreateInput ---
  lines.push(`export interface Create${name}Input {`);
  for (const [fieldName, def] of fields) {
    // Exclude auto-defaults and onUpdate fields
    if (def.onUpdate === 'now') continue;
    if (isAutoDefault(def.default)) continue;

    const hasLiteralDefault = def.default !== undefined && !isAutoDefault(def.default);
    const opt = def.optional || hasLiteralDefault ? '?' : '';
    lines.push(`  ${fieldName}${opt}: ${tsType(def)};`);
  }
  lines.push('}');
  lines.push('');

  // --- UpdateInput ---
  lines.push(`export interface Update${name}Input {`);
  for (const [fieldName, def] of fields) {
    if (def.immutable) continue;
    if (def.onUpdate === 'now') continue;
    lines.push(`  ${fieldName}?: ${tsType(def)};`);
  }
  lines.push('}');
  lines.push('');

  // --- PK type ---
  const pkDef = config.fields[pkField];
  const pkType = pkDef.type === 'string' ? 'string' : 'number';
  lines.push(`export type ${name}Id = ${pkType};`);
  lines.push('');

  return lines.join('\n');
}
