/**
 * Route generation content tests.
 *
 * Verifies the actual content of code generated by `generateRoutes()` and
 * `generate()`: correct CRUD endpoints, named operation routes, routePath
 * override, registerSchemas call, backend selection, and full file set.
 */
import { describe, expect, it } from 'bun:test';
import { defineEntity, field } from '../../src/defineEntity';
import { generate } from '../../src/generate';
import { generateRoutes } from '../../src/generators/routes';

// ---------------------------------------------------------------------------
// Fixtures
// ---------------------------------------------------------------------------

const articleEntity = defineEntity('Article', {
  fields: {
    id: field.string({ primary: true, default: 'uuid' }),
    title: field.string(),
    status: field.enum(['draft', 'published'], { default: 'draft' }),
    publishedMonth: field.string({ format: 'month', optional: true }),
    createdAt: field.date({ default: 'now' }),
  },
  routes: {
    create: { auth: 'userAuth' },
    list: { auth: 'none' },
    get: {},
    update: {},
    delete: {},
  },
});

const articleOps = {
  publish: {
    kind: 'transition' as const,
    field: 'status',
    from: 'draft',
    to: 'published',
    match: { id: 'param:id' as const },
  },
  findByTitle: {
    kind: 'search' as const,
    fields: ['title'],
    paginate: true,
  },
};

// ---------------------------------------------------------------------------
// generateRoutes() content
// ---------------------------------------------------------------------------

describe('generateRoutes() — CRUD endpoints', () => {
  it('contains the factory function named create{Name}Routes', () => {
    const src = generateRoutes(articleEntity);
    expect(src).toContain('createArticleRoutes');
  });

  it('emits POST endpoint for create', () => {
    const src = generateRoutes(articleEntity);
    expect(src).toContain("method: 'post'");
    expect(src).toContain("path: '/articles'");
  });

  it('emits GET endpoint for getById', () => {
    const src = generateRoutes(articleEntity);
    expect(src).toContain("method: 'get'");
    expect(src).toContain("path: '/articles/{id}'");
  });

  it('emits PATCH endpoint for update', () => {
    const src = generateRoutes(articleEntity);
    expect(src).toContain("method: 'patch'");
  });

  it('emits DELETE endpoint for delete', () => {
    const src = generateRoutes(articleEntity);
    expect(src).toContain("method: 'delete'");
  });

  it('emits GET endpoint for list', () => {
    const src = generateRoutes(articleEntity);
    // Two GET routes: getById (with :id) and list (without) — both present
    const getCount = (src.match(/method: 'get'/g) ?? []).length;
    expect(getCount).toBeGreaterThanOrEqual(2);
  });

  it('calls registerSchemas at module scope', () => {
    const src = generateRoutes(articleEntity);
    expect(src).toContain('registerSchemas(');
    expect(src).toContain('Article:');
    expect(src).toContain('CreateArticleInput:');
    expect(src).toContain('UpdateArticleInput:');
  });

  it('imports from @hono/zod-openapi and @lastshotlabs/slingshot-core', () => {
    const src = generateRoutes(articleEntity);
    expect(src).toContain("from '@hono/zod-openapi'");
    expect(src).toContain("from '@lastshotlabs/slingshot-core'");
  });

  it('imports the adapter type from ./adapter', () => {
    const src = generateRoutes(articleEntity);
    expect(src).toContain("from './adapter'");
    expect(src).toContain('ArticleAdapter');
  });

  it('emits duplicate conflict handling and responses for mutating routes', () => {
    const src = generateRoutes(articleEntity);
    expect(src).toContain("code: 'duplicate'");
    expect(src).toContain('duplicateConstraintResponse');
    expect(src).toContain("description: 'Conflict'");
  });
});

describe('generateRoutes() — named operations', () => {
  it('emits a POST route for a transition operation', () => {
    const src = generateRoutes(articleEntity, articleOps);
    expect(src).toContain("path: '/articles/publish'");
    expect(src).toContain("method: 'post'");
  });

  it('emits a GET route for a search operation at /search path', () => {
    const src = generateRoutes(articleEntity, articleOps);
    // search ops use a fixed /search path on the entity root
    expect(src).toContain("path: '/articles/search'");
    expect(src).toContain("method: 'get'");
    expect(src).toContain('findByTitle');
  });

  it('adapter.publish is called in the handler', () => {
    const src = generateRoutes(articleEntity, articleOps);
    expect(src).toContain('adapter.publish');
  });
});

describe('generateRoutes() — routePath override', () => {
  it('uses routePath instead of the default entity path', () => {
    const src = generateRoutes(articleEntity, undefined, { routePath: 'posts' });
    expect(src).toContain("path: '/posts'");
    expect(src).toContain("path: '/posts/{id}'");
    // Default path should NOT appear
    expect(src).not.toContain("path: '/articles/{id}'");
  });

  it('named operation paths also use routePath', () => {
    const src = generateRoutes(articleEntity, articleOps, { routePath: 'posts' });
    expect(src).toContain("path: '/posts/publish'");
    expect(src).not.toContain("path: '/articles/publish'");
  });
});

// ---------------------------------------------------------------------------
// generate() — file set and backend selection
// ---------------------------------------------------------------------------

describe('generate() — file set', () => {
  it('always produces types.ts, schemas.ts, adapter.ts, index.ts', () => {
    const files = generate(articleEntity, { backends: ['memory'] });
    expect('types.ts' in files).toBe(true);
    expect('schemas.ts' in files).toBe(true);
    expect('adapter.ts' in files).toBe(true);
    expect('index.ts' in files).toBe(true);
  });

  it('produces only the requested backends', () => {
    const files = generate(articleEntity, { backends: ['memory', 'sqlite'] });
    expect('memory.ts' in files).toBe(true);
    expect('sqlite.ts' in files).toBe(true);
    expect('postgres.ts' in files).toBe(false);
    expect('mongo.ts' in files).toBe(false);
    expect('redis.ts' in files).toBe(false);
  });

  it('produces all five adapters when backends is omitted', () => {
    const files = generate(articleEntity);
    expect('memory.ts' in files).toBe(true);
    expect('sqlite.ts' in files).toBe(true);
    expect('postgres.ts' in files).toBe(true);
    expect('mongo.ts' in files).toBe(true);
    expect('redis.ts' in files).toBe(true);
  });

  it('produces routes.ts when entity has routes config', () => {
    const files = generate(articleEntity, { backends: ['memory'] });
    expect('routes.ts' in files).toBe(true);
  });

  it('produces routes.ts when operations are provided', () => {
    const entityWithoutRoutes = defineEntity('Tag', {
      fields: {
        id: field.string({ primary: true }),
        name: field.string(),
      },
    });
    const files = generate(entityWithoutRoutes, {
      backends: ['memory'],
      operations: articleOps,
    });
    expect('routes.ts' in files).toBe(true);
  });

  it('sqlite.ts contains createSqliteArticleAdapter', () => {
    const files = generate(articleEntity, { backends: ['sqlite'] });
    expect(files['sqlite.ts']).toContain('createSqliteArticleAdapter');
  });

  it('memory.ts contains createMemoryArticleAdapter', () => {
    const files = generate(articleEntity, { backends: ['memory'] });
    expect(files['memory.ts']).toContain('createMemoryArticleAdapter');
  });

  it('types.ts contains the entity interface', () => {
    const files = generate(articleEntity, { backends: ['memory'] });
    expect(files['types.ts']).toContain('interface Article');
    expect(files['types.ts']).toContain('title: string');
    expect(files['types.ts']).toContain('status:');
  });

  it('schemas.ts contains Zod schemas for create/update/entity', () => {
    const files = generate(articleEntity, { backends: ['memory'] });
    // Generated schema variable names are camelCase: articleSchema, createArticleSchema, etc.
    expect(files['schemas.ts']).toContain('articleSchema');
    expect(files['schemas.ts']).toContain('createArticleSchema');
    expect(files['schemas.ts']).toContain('updateArticleSchema');
    expect(files['schemas.ts']).toContain("format: 'month'");
  });
});
