import type { SlingshotSsrRenderer } from '@lastshotlabs/slingshot-ssr';
import type { PageDeclaration } from '@lastshotlabs/slingshot-ssr';
import type { AppManifest, AppManifestHandlerRef } from './manifest';
import { resolveBuiltinPath, resolveHandlerRef } from './manifestBuiltinConfig';
import type { ManifestHandlerRegistry } from './manifestHandlerRegistry';
import type { ManifestToConfigOptions } from './manifestToAppConfig';

/**
 * Build-time SSG configuration derived from `app.manifest.json`.
 *
 * The shape matches the inputs expected by `@lastshotlabs/slingshot-ssg`, while
 * keeping SSR-shared fields single-sourced in the top-level manifest.
 */
export interface ManifestSsgBuildConfig {
  /** Absolute path to the server routes directory. */
  readonly serverRoutesDir: string;
  /** Absolute path to the client asset manifest generated by the browser build. */
  readonly assetsManifest: string;
  /** Absolute output directory for generated HTML. */
  readonly outDir: string;
  /** Maximum number of pages to render in parallel. */
  readonly concurrency?: number;
  /** Optional Vite manifest key for the browser entry chunk. */
  readonly clientEntry?: string;
  /** Optional entity-driven page declarations shared with SSR. */
  readonly pages?: Readonly<Record<string, PageDeclaration>>;
}

/**
 * Resolved SSG runtime inputs derived from the manifest.
 */
export interface ManifestSsgConfigResult {
  /** The SSR renderer used by the SSG build. */
  readonly renderer: SlingshotSsrRenderer;
  /** Build-time file and policy configuration. */
  readonly config: ManifestSsgBuildConfig;
}

function requireHandlerRef(
  value: AppManifestHandlerRef | undefined,
  context: string,
): AppManifestHandlerRef {
  if (!value) {
    throw new Error(`[manifestToSsgConfig] Missing required handler ref at ${context}.`);
  }

  return value;
}

function requireString(value: string | undefined, context: string): string {
  if (!value) {
    throw new Error(`[manifestToSsgConfig] Missing required string value at ${context}.`);
  }

  return value;
}

/**
 * Resolve the SSG build inputs from a validated app manifest.
 *
 * The `ssg` section carries build-only policy (`outDir`, `concurrency`,
 * `clientEntry`). Shared fields inherit from `ssr` when omitted so the
 * manifest stays single-sourced for renderer and route locations.
 *
 * @param manifest - A validated manifest object.
 * @param registry - Registry used to resolve renderer handler refs.
 * @param options - Optional base directory override for relative paths.
 * @returns The resolved renderer and SSG build config.
 */
export function manifestToSsgConfig(
  manifest: AppManifest,
  registry?: ManifestHandlerRegistry,
  options?: ManifestToConfigOptions,
): ManifestSsgConfigResult {
  if (manifest.ssg?.enabled === false) {
    throw new Error(
      '[manifestToSsgConfig] manifest.ssg.enabled is false. Remove the section or enable SSG before resolving build config.',
    );
  }

  const baseDir = options?.baseDir ?? process.cwd();
  const rendererRef = manifest.ssg?.renderer ?? manifest.ssr?.renderer;
  const serverRoutesDir = manifest.ssg?.serverRoutesDir ?? manifest.ssr?.serverRoutesDir;
  const assetsManifest = manifest.ssg?.assetsManifest ?? manifest.ssr?.assetsManifest;
  const outDir = manifest.ssg?.outDir ?? manifest.ssr?.staticDir;

  const resolvedAssetsManifest = requireString(
    assetsManifest,
    manifest.ssg?.assetsManifest ? 'manifest.ssg.assetsManifest' : 'manifest.ssr.assetsManifest',
  );
  if (resolvedAssetsManifest.trimStart().startsWith('{')) {
    throw new Error(
      '[manifestToSsgConfig] Inline JSON assets manifests are not supported for SSG builds. ' +
        'Provide a path to the browser build manifest instead.',
    );
  }

  const renderer = resolveHandlerRef(
    requireHandlerRef(
      rendererRef,
      manifest.ssg?.renderer ? 'manifest.ssg.renderer' : 'manifest.ssr.renderer',
    ),
    registry,
    manifest.ssg?.renderer ? 'manifest.ssg.renderer' : 'manifest.ssr.renderer',
  ) as SlingshotSsrRenderer;

  const config = Object.freeze({
    serverRoutesDir: resolveBuiltinPath(
      requireString(
        serverRoutesDir,
        manifest.ssg?.serverRoutesDir
          ? 'manifest.ssg.serverRoutesDir'
          : 'manifest.ssr.serverRoutesDir',
      ),
      baseDir,
    ),
    assetsManifest: resolveBuiltinPath(resolvedAssetsManifest, baseDir),
    outDir: resolveBuiltinPath(
      requireString(
        outDir,
        manifest.ssg?.outDir ? 'manifest.ssg.outDir' : 'manifest.ssr.staticDir',
      ),
      baseDir,
    ),
    ...(manifest.pages ? { pages: manifest.pages } : {}),
    ...(manifest.ssg?.concurrency !== undefined ? { concurrency: manifest.ssg.concurrency } : {}),
    ...(manifest.ssg?.clientEntry !== undefined ? { clientEntry: manifest.ssg.clientEntry } : {}),
  }) satisfies ManifestSsgBuildConfig;

  return Object.freeze({
    renderer,
    config,
  });
}
