 
import {
  Apple,
  Bitbucket,
  GitHub,
  GitLab,
  Google,
  LinkedIn,
  MicrosoftEntraId,
  Slack,
  Twitter,
  generateCodeVerifier,
  generateState,
} from 'arctic';
import { DEFAULT_MAX_ENTRIES, createEvictExpired, evictOldest } from '@lastshotlabs/slingshot-core';
import type { RepoFactories, RuntimeSqliteDatabase } from '@lastshotlabs/slingshot-core';
import { createPostgresInitializer } from './postgresInit';
import { createSqliteInitializer } from './sqliteInit';
import type { RedisLike } from '../types/redis';

/**
 * OAuth provider credential configuration map.
 *
 * Each key corresponds to a supported OAuth provider. Provide credentials for any
 * providers you want to enable. Passed to `OAuthConfig.providers` inside `AuthConfig`.
 *
 * @remarks
 * Requires the `@lastshotlabs/slingshot-oauth` package. Startup throws if providers are
 * configured but the package is not installed.
 *
 * @example
 * createAuthPlugin({
 *   auth: {
 *     oauth: {
 *       providers: {
 *         google: { clientId: '...', clientSecret: '...', redirectUri: 'https://app.com/auth/google/callback' },
 *         github: { clientId: '...', clientSecret: '...', redirectUri: 'https://app.com/auth/github/callback' },
 *       },
 *     },
 *   },
 * });
 */
export type OAuthProviderConfig = {
  google?: { clientId: string; clientSecret: string; redirectUri: string };
  apple?: {
    clientId: string;
    teamId: string;
    keyId: string;
    privateKey: string;
    redirectUri: string;
  };
  microsoft?: { tenantId: string; clientId: string; clientSecret: string; redirectUri: string };
  github?: { clientId: string; clientSecret: string; redirectUri: string };
  linkedin?: { clientId: string; clientSecret: string; redirectUri: string };
  twitter?: { clientId: string; clientSecret: string | null; redirectUri: string };
  gitlab?: { baseUrl?: string; clientId: string; clientSecret: string | null; redirectUri: string };
  slack?: { clientId: string; clientSecret: string; redirectUri: string | null };
  bitbucket?: { clientId: string; clientSecret: string; redirectUri: string };
};

/**
 * Map of initialized `arctic` OAuth provider instances.
 *
 * Built from `OAuthProviderConfig` by `createOAuthProviders`. Each present key holds
 * an `arctic` client instance ready for authorization URL generation and token exchange.
 * Stored on `AuthRuntimeContext.oauth.providers`.
 */
export type OAuthProviders = {
  google?: Google;
  apple?: Apple;
  microsoft?: MicrosoftEntraId;
  github?: GitHub;
  linkedin?: LinkedIn;
  twitter?: Twitter;
  gitlab?: GitLab;
  slack?: Slack;
  bitbucket?: Bitbucket;
};

/**
 * Union of all provider keys for which credentials were configured.
 * Derived from the keys of `OAuthProviders`.
 */
export type ConfiguredOAuthProvider = keyof OAuthProviders;

/**
 * The data payload associated with an OAuth state value.
 *
 * Stored alongside the state string in `OAuthStateStore`. Retrieved atomically by
 * `consume` when the callback arrives with the matching state parameter.
 *
 * - `codeVerifier` — the PKCE code verifier for providers that require it (Google, etc.).
 * - `linkUserId` — the ID of an already-authenticated user who initiated a "link provider" flow.
 */
export interface OAuthStateRecord {
  codeVerifier?: string;
  linkUserId?: string;
}

/**
 * Storage contract for OAuth PKCE state values.
 *
 * The `state` parameter is a cryptographically random string passed through the OAuth
 * redirect and validated on callback to prevent CSRF. When PKCE is used (e.g. Google),
 * the `codeVerifier` is stored alongside the state. When linking a provider to an
 * existing account, `linkUserId` records which user initiated the flow.
 *
 * State entries expire after 300 seconds (5 minutes), matching the typical OAuth
 * redirect timeout.
 */
export interface OAuthStateStore {
  /**
   * Stores an OAuth state entry.
   *
   * @param state - The cryptographically random state string generated by `generateState()`.
   *   This is the key for later retrieval on callback.
   * @param codeVerifier - Optional PKCE code verifier generated by `generateCodeVerifier()`.
   *   Required for providers that enforce PKCE (e.g. Google). Pass `undefined` for providers
   *   that do not use PKCE.
   * @param linkUserId - Optional ID of an already-authenticated user who initiated a
   *   "link provider" flow. When present, the callback route will link the OAuth identity
   *   to this user rather than creating a new account or logging in.
   * @returns `Promise<void>` — resolves when the state has been durably stored.
   *
   * @remarks
   * State entries have a fixed TTL of 300 seconds (5 minutes). If the user does not
   * complete the OAuth redirect within that window, `consume` will return `null` and
   * the login or link flow must be restarted.
   */
  store(state: string, codeVerifier?: string, linkUserId?: string): Promise<void>;

  /**
   * Atomically reads and deletes the state entry identified by `state`.
   *
   * @param state - The state string from the OAuth callback `?state=` query parameter.
   * @returns The stored `OAuthStateRecord` (`{ codeVerifier?, linkUserId? }`) on success,
   *   or `null` when the state is not found, has expired, or was already consumed.
   *
   * @remarks
   * **Single-use atomicity**: all backends implement this as an atomic read-and-delete
   * (Redis `GETDEL` / Lua fallback, SQLite `DELETE ... RETURNING`, Postgres
   * `DELETE ... RETURNING`, MongoDB `findOneAndDelete`). Once consumed a state value
   * is permanently gone — a second call with the same state string returns `null`.
   * This prevents OAuth callback replay attacks where an attacker re-submits a valid
   * callback URL.
   */
  consume(state: string): Promise<OAuthStateRecord | null>;
}

const STATE_TTL = 300;

// ---------------------------------------------------------------------------
// Memory repository factory
// ---------------------------------------------------------------------------

interface MemoryOAuthStateEntry {
  codeVerifier?: string;
  linkUserId?: string;
  expiresAt: number;
}

/**
 * Creates an in-memory OAuth state store.
 *
 * Entries expire after 300 seconds (matching the OAuth state TTL). Eviction is
 * opportunistic — expired entries are swept on `store` calls. Suitable for
 * development and single-server deployments.
 *
 * @returns An `OAuthStateStore` backed by in-memory Maps.
 *
 * @example
 * // In tests
 * const stateStore = createMemoryOAuthStateStore();
 * await stateStore.store('random-state-value', 'code-verifier');
 * const record = await stateStore.consume('random-state-value');
 * // record: { codeVerifier: 'code-verifier' }
 */
export function createMemoryOAuthStateStore(): OAuthStateStore {
  const states = new Map<string, MemoryOAuthStateEntry>();
  const evictExpired = createEvictExpired();

  return {
    async store(state, codeVerifier, linkUserId) {
      evictExpired(states);
      evictOldest(states, DEFAULT_MAX_ENTRIES);
      states.set(state, { codeVerifier, linkUserId, expiresAt: Date.now() + STATE_TTL * 1000 });
    },
    async consume(state) {
      const entry = states.get(state);
      if (!entry || entry.expiresAt <= Date.now()) {
        states.delete(state);
        return null;
      }
      states.delete(state);
      return { codeVerifier: entry.codeVerifier, linkUserId: entry.linkUserId };
    },
  };
}

// ---------------------------------------------------------------------------
// SQLite repository factory
// ---------------------------------------------------------------------------

export function createSqliteOAuthStateStore(db: RuntimeSqliteDatabase): OAuthStateStore {
  const init = createSqliteInitializer(db, () => {
    db.run(`CREATE TABLE IF NOT EXISTS oauth_states (
      state      TEXT PRIMARY KEY,
      codeVerifier TEXT,
      linkUserId TEXT,
      expiresAt  INTEGER NOT NULL
    )`);
    db.run('CREATE INDEX IF NOT EXISTS idx_oauth_states_expiresAt ON oauth_states(expiresAt)');
  });

  return {
    async store(state, codeVerifier, linkUserId) {
      init();
      const expiresAt = Date.now() + STATE_TTL * 1000;
      db.run(
        `INSERT INTO oauth_states (state, codeVerifier, linkUserId, expiresAt)
         VALUES (?, ?, ?, ?)
         ON CONFLICT(state) DO UPDATE SET codeVerifier = excluded.codeVerifier, linkUserId = excluded.linkUserId, expiresAt = excluded.expiresAt`,
        state,
        codeVerifier ?? null,
        linkUserId ?? null,
        expiresAt,
      );
    },
    async consume(state) {
      init();
      const now = Date.now();
      const row = db
        .query(
          'DELETE FROM oauth_states WHERE state = ? AND expiresAt > ? RETURNING codeVerifier, linkUserId',
        )
        .get(state, now) as { codeVerifier?: string; linkUserId?: string } | null;
      return row ?? null;
    },
  };
}

// ---------------------------------------------------------------------------
// Redis repository factory
// ---------------------------------------------------------------------------

async function redisGetDel(redis: RedisLike, key: string): Promise<string | null> {
  if (typeof redis.getdel === 'function') {
    try {
      return await redis.getdel(key);
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : '';
      if (!/unknown command|ERR unknown command/i.test(msg)) throw err;
    }
  }
  const result = await redis.eval(
    "local v = redis.call('GET', KEYS[1])\nif v then redis.call('DEL', KEYS[1]) end\nreturn v",
    1,
    key,
  );
  return (result as string | null) ?? null;
}

export function createRedisOAuthStateStore(
  getRedis: () => RedisLike,
  appName: string,
): OAuthStateStore {
  return {
    async store(state, codeVerifier, linkUserId) {
      await getRedis().set(
        `oauth:${appName}:state:${state}`,
        JSON.stringify({ codeVerifier, linkUserId }),
        'EX',
        STATE_TTL,
      );
    },
    async consume(state) {
      const key = `oauth:${appName}:state:${state}`;
      const value = await redisGetDel(getRedis(), key);
      if (!value) return null;
      return JSON.parse(value) as OAuthStateRecord;
    },
  };
}

// ---------------------------------------------------------------------------
// Mongo repository factory
// ---------------------------------------------------------------------------

interface OAuthStateDoc {
  state: string;
  codeVerifier?: string;
  linkUserId?: string;
  expiresAt: Date;
}

function getOAuthStateModel(
  conn: import('mongoose').Connection,
  mg: typeof import('mongoose'),
): import('mongoose').Model<OAuthStateDoc> {
  if ('OAuthState' in conn.models) {
    return conn.models['OAuthState'] as unknown as import('mongoose').Model<OAuthStateDoc>;
  }
  const { Schema } = mg;
  const oauthStateSchema = new Schema<OAuthStateDoc>(
    {
      state: { type: String, required: true, unique: true },
      codeVerifier: { type: String },
      linkUserId: { type: String },
      expiresAt: { type: Date, required: true, index: { expireAfterSeconds: 0 } },
    },
    { collection: 'oauth_states' },
  );
  return conn.model('OAuthState', oauthStateSchema) as import('mongoose').Model<OAuthStateDoc>;
}

export function createMongoOAuthStateStore(
  conn: import('mongoose').Connection,
  mg: typeof import('mongoose'),
): OAuthStateStore {
  return {
    async store(state, codeVerifier, linkUserId) {
      const expiresAt = new Date(Date.now() + STATE_TTL * 1000);
      await getOAuthStateModel(conn, mg).create({ state, codeVerifier, linkUserId, expiresAt });
    },
    async consume(state) {
      const doc = await getOAuthStateModel(conn, mg)
        .findOneAndDelete({ state, expiresAt: { $gt: new Date() } })
        .lean();
      return doc ? { codeVerifier: doc.codeVerifier, linkUserId: doc.linkUserId } : null;
    },
  };
}

/**
 * Instantiates `arctic` OAuth client objects for every provider configured in `config`.
 *
 * Each provider entry in `config` produces the corresponding `arctic` client
 * (e.g. `config.google` → `new Google(...)`).  Providers absent from `config`
 * are simply not included in the returned map — their keys are `undefined`.
 *
 * Called once during auth plugin bootstrap; the result is stored on
 * `AuthRuntimeContext.oauth.providers`.
 *
 * @param config - OAuth provider credentials from `AuthConfig.oauth.providers`.
 * @returns An `OAuthProviders` map of initialised `arctic` client instances.
 *
 * @example
 * const providers = createOAuthProviders({
 *   google: { clientId: '...', clientSecret: '...', redirectUri: 'https://app.com/auth/google/callback' },
 *   github: { clientId: '...', clientSecret: '...', redirectUri: 'https://app.com/auth/github/callback' },
 * });
 * // providers.google instanceof Google === true
 * // providers.twitter === undefined
 */
export function createOAuthProviders(config: OAuthProviderConfig): OAuthProviders {
  const providers: OAuthProviders = {};
  if (config.google) {
    const { clientId, clientSecret, redirectUri } = config.google;
    providers.google = new Google(clientId, clientSecret, redirectUri);
  }
  if (config.apple) {
    const { clientId, teamId, keyId, privateKey, redirectUri } = config.apple;
    providers.apple = new Apple(
      clientId,
      teamId,
      keyId,
      new TextEncoder().encode(privateKey),
      redirectUri,
    );
  }
  if (config.microsoft) {
    const { tenantId, clientId, clientSecret, redirectUri } = config.microsoft;
    providers.microsoft = new MicrosoftEntraId(tenantId, clientId, clientSecret, redirectUri);
  }
  if (config.github) {
    const { clientId, clientSecret, redirectUri } = config.github;
    providers.github = new GitHub(clientId, clientSecret, redirectUri);
  }
  if (config.linkedin) {
    const { clientId, clientSecret, redirectUri } = config.linkedin;
    providers.linkedin = new LinkedIn(clientId, clientSecret, redirectUri);
  }
  if (config.twitter) {
    const { clientId, clientSecret, redirectUri } = config.twitter;
    providers.twitter = new Twitter(clientId, clientSecret, redirectUri);
  }
  if (config.gitlab) {
    const { baseUrl, clientId, clientSecret, redirectUri } = config.gitlab;
    providers.gitlab = new GitLab(
      baseUrl ?? 'https://gitlab.com',
      clientId,
      clientSecret,
      redirectUri,
    );
  }
  if (config.slack) {
    const { clientId, clientSecret, redirectUri } = config.slack;
    providers.slack = new Slack(clientId, clientSecret, redirectUri);
  }
  if (config.bitbucket) {
    const { clientId, clientSecret, redirectUri } = config.bitbucket;
    providers.bitbucket = new Bitbucket(clientId, clientSecret, redirectUri);
  }
  return providers;
}

/**
 * Returns an array of provider keys for which a client instance is present.
 *
 * Filters the `OAuthProviders` map to only the keys whose values are non-null.
 * Used to populate the list of enabled providers returned by the
 * `GET /auth/oauth/providers` discovery endpoint.
 *
 * @param providers - Initialised `OAuthProviders` map from `createOAuthProviders`.
 * @returns Array of `ConfiguredOAuthProvider` keys (e.g. `["google", "github"]`).
 *
 * @example
 * const enabled = getConfiguredOAuthProviders(runtime.oauth.providers);
 * // enabled: ['google', 'github']
 */
export function getConfiguredOAuthProviders(providers: OAuthProviders): ConfiguredOAuthProvider[] {
  return (Object.entries(providers) as [ConfiguredOAuthProvider, unknown][])
    .filter(([, value]) => value != null)
    .map(([name]) => name);
}

// ---------------------------------------------------------------------------
// Factory map
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Postgres repository factory
// ---------------------------------------------------------------------------

export function createPostgresOAuthStateStore(pool: import('pg').Pool): OAuthStateStore {
  const ensureTable = createPostgresInitializer(pool, async client => {
    await client.query(`CREATE TABLE IF NOT EXISTS auth_oauth_state (
      state         TEXT PRIMARY KEY,
      code_verifier TEXT,
      link_user_id  TEXT,
      expires_at    BIGINT NOT NULL
    )`);
    await client.query(
      'CREATE INDEX IF NOT EXISTS idx_auth_oauth_state_expires_at ON auth_oauth_state(expires_at)',
    );
  });

  return {
    async store(state, codeVerifier, linkUserId) {
      await ensureTable();
      const expiresAt = Date.now() + STATE_TTL * 1000;
      await pool.query(
        `INSERT INTO auth_oauth_state (state, code_verifier, link_user_id, expires_at)
         VALUES ($1, $2, $3, $4)
         ON CONFLICT (state) DO UPDATE SET
           code_verifier = EXCLUDED.code_verifier,
           link_user_id  = EXCLUDED.link_user_id,
           expires_at    = EXCLUDED.expires_at`,
        [state, codeVerifier ?? null, linkUserId ?? null, expiresAt],
      );
    },
    async consume(state) {
      await ensureTable();
      const now = Date.now();
      const { rows } = await pool.query<{
        code_verifier: string | null;
        link_user_id: string | null;
      }>(
        `DELETE FROM auth_oauth_state
         WHERE state = $1 AND expires_at > $2
         RETURNING code_verifier, link_user_id`,
        [state, now],
      );
      if (!rows[0]) return null;
      return {
        codeVerifier: rows[0].code_verifier ?? undefined,
        linkUserId: rows[0].link_user_id ?? undefined,
      };
    },
  };
}

export const oauthStateFactories: RepoFactories<OAuthStateStore> = {
  memory: () => createMemoryOAuthStateStore(),
  sqlite: infra => createSqliteOAuthStateStore(infra.getSqliteDb()),
  redis: infra => createRedisOAuthStateStore(infra.getRedis, infra.appName),
  mongo: infra => {
    const { conn, mg } = infra.getMongo();
    return createMongoOAuthStateStore(conn, mg);
  },
  postgres: infra => createPostgresOAuthStateStore(infra.getPostgres().pool),
};

/**
 * Generates a cryptographically random OAuth state parameter for CSRF protection.
 *
 * The state string should be stored in `OAuthStateStore.store()` before redirecting
 * the user to the provider's authorization URL. On callback, verify it with
 * `OAuthStateStore.consume()`. Re-exported from the `arctic` library.
 *
 * @returns A random base64url-encoded state string.
 *
 * @example
 * import { generateState } from '@lastshotlabs/slingshot-auth';
 *
 * const state = generateState();
 * await runtime.oauth.stateStore.store(state, codeVerifier);
 * return c.redirect(provider.createAuthorizationURL(state, codeVerifier, scopes));
 */
export { generateState };

/**
 * Generates a cryptographically random PKCE code verifier.
 *
 * Required for OAuth providers that support PKCE (e.g. Google, GitHub). Store the
 * verifier alongside the state in `OAuthStateStore.store()` before the redirect, then
 * pass it to the token exchange call on callback. Re-exported from the `arctic` library.
 *
 * @returns A random base64url-encoded code verifier string (43–128 characters).
 *
 * @example
 * import { generateCodeVerifier, generateState } from '@lastshotlabs/slingshot-auth';
 *
 * const codeVerifier = generateCodeVerifier();
 * const state = generateState();
 * await runtime.oauth.stateStore.store(state, codeVerifier);
 */
export { generateCodeVerifier };
