import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    'cli/index': 'src/cli/index.ts',
    'cli/commands/init': 'src/cli/commands/init.ts',
    'cli/commands/deploy': 'src/cli/commands/deploy.ts',
    'cli/commands/start': 'src/cli/commands/start.ts',
    'cli/commands/platform/init': 'src/cli/commands/platform/init.ts',
    'cli/commands/platform/deploy': 'src/cli/commands/platform/deploy.ts',
    'cli/commands/platform/sync': 'src/cli/commands/platform/sync.ts',

    'cli/commands/platform/destroy': 'src/cli/commands/platform/destroy.ts',
    'cli/commands/platform/pull': 'src/cli/commands/platform/pull.ts',
    'cli/commands/stacks/create': 'src/cli/commands/stacks/create.ts',
    'cli/commands/stacks/list': 'src/cli/commands/stacks/list.ts',
    'cli/commands/stacks/inspect': 'src/cli/commands/stacks/inspect.ts',
    'cli/commands/secrets/push': 'src/cli/commands/secrets/push.ts',
    'cli/commands/secrets/pull': 'src/cli/commands/secrets/pull.ts',
    'cli/commands/secrets/check': 'src/cli/commands/secrets/check.ts',
    'cli/commands/registry/init': 'src/cli/commands/registry/init.ts',
    'cli/commands/servers/remove': 'src/cli/commands/servers/remove.ts',
    'cli/commands/servers/inspect': 'src/cli/commands/servers/inspect.ts',
    'cli/commands/servers/add': 'src/cli/commands/servers/add.ts',
    'cli/commands/infra/generate': 'src/cli/commands/infra/generate.ts',
    'cli/commands/generate': 'src/cli/commands/generate.ts',
    'cli/commands/migrate/generate': 'src/cli/commands/migrate/generate.ts',
    'cli/commands/migrate/apply': 'src/cli/commands/migrate/apply.ts',
    'cli/commands/migrate/status': 'src/cli/commands/migrate/status.ts',
    'cli/commands/migrate/dev': 'src/cli/commands/migrate/dev.ts',
    'cli/commands/migrate/reset': 'src/cli/commands/migrate/reset.ts',
  },
  format: ['esm'],
  dts: false,
  sourcemap: false,
  clean: false,
  target: 'node20',
  platform: 'node',
  bundle: true,
  outExtension: () => ({ js: '.js' }),
  // Bundle all @lastshotlabs workspace packages inline so the CLI doesn't depend
  // on their dist files at runtime. Workspace dists use "moduleResolution: bundler"
  // which omits .js extensions — Node.js ESM cannot resolve those at runtime.
  noExternal: [/^@lastshotlabs\//],
  external: [
    '@lastshotlabs/slingshot-orchestration-temporal',
    '@oclif/core',
    '@temporalio/activity',
    '@temporalio/client',
    '@temporalio/common',
    '@temporalio/worker',
    '@temporalio/workflow',
    '@swc/core',
    '@swc/wasm',
    '@hono/zod-openapi',
    '@simplewebauthn/server',
    '@aws-sdk/client-s3',
    '@aws-sdk/client-ssm',
    '@aws-sdk/lib-storage',
    '@aws-sdk/s3-request-presigner',
    'arctic',
    'bullmq',
    'hono',
    'hono/cookie',
    'ioredis',
    'jose',
    'mongoose',
    'node:fs',
    'node:path',
    'node:child_process',
    'node:process',
    'node:buffer',
    'otpauth',
    'fs',
    'path',
    'pg',
    'samlify',
    'child_process',
    'bun:sqlite',
    'better-sqlite3',
    'mongodb',
  ],
  banner: {
    js: '#!/usr/bin/env node',
  },
});
