import type { DefineInfraConfig, ServiceDeclaration } from './infra';
import type { DefinePlatformConfig, StackConfig, StageConfig } from './platform';
import type { RegistryDocument, RegistryServiceEntry } from './registry';

/**
 * A sibling service entry — a deployed service from another repo on the same stack.
 *
 * Used by the EC2/nginx preset to generate composite docker-compose and Caddyfile
 * configs that include all services on the stack, not just the current app's services.
 */
export interface SiblingService extends RegistryServiceEntry {
  /** Logical service name (key in `RegistryDocument.services`). */
  name: string;
}

/**
 * Context object passed to every `PresetProvider` method.
 *
 * Assembles all data a preset needs to generate deployment files and execute
 * the deploy: frozen platform/infra configs, resolved env vars, registry state,
 * sibling services, and runtime metadata (image tag, temp dir, etc.).
 */
export interface PresetContext {
  /** Frozen platform config as defined in `slingshot.platform.ts`. */
  platform: DefinePlatformConfig;
  /** Frozen infra config as defined in `slingshot.infra.ts`. */
  infra: DefineInfraConfig;
  /**
   * Resolved stage config for `stageName`.
   * Contains env, secrets, domain, scaling, and provider overrides for this stage.
   */
  stage: StageConfig;
  /** Deployment stage name (e.g. `'production'`, `'staging'`). */
  stageName: string;
  /**
   * Stack config for `stackName`.
   * Contains the preset identifier and per-stage infrastructure settings.
   */
  stack: StackConfig;
  /** Stack name the services are deployed to (e.g. `'main'`, `'workers'`). */
  stackName: string;
  /**
   * Current registry document at the time of the deploy.
   * Contains provisioning state for all stacks, resources, and services.
   */
  registry: RegistryDocument;
  /**
   * Resolved environment variables.
   *
   * - Single-service apps: a flat `Record<string, string>` mapping env var name → value.
   * - Multi-service apps: `Record<serviceName, Record<string, string>>` keyed by service name.
   *
   * Use {@link getServiceEnv} to access this field safely regardless of app shape.
   */
  resolvedEnv: Record<string, string> | Record<string, Record<string, string>>;
  /** Absolute path to the app/service root on the host machine. */
  appRoot: string;
  /**
   * Temp directory where generated files are written during the deploy pipeline.
   * Absent until the pipeline creates the temp dir (available from the `generate` phase onward).
   */
  tempDir?: string;
  /** Logical service name used as a key in `registry.services`. `'default'` for single-service apps. */
  serviceName: string;
  /**
   * Service declaration from `DefineInfraConfig.services` for multi-service apps.
   * Absent for single-service apps.
   */
  service?: ServiceDeclaration;
  /** Docker image tag for this deploy (e.g. `'20240101-120000-abc1234'`). */
  imageTag: string;
  /** Docker registry base URL used for image push/pull (e.g. `'123456.dkr.ecr.us-east-1.amazonaws.com'`). */
  dockerRegistry: string;
  /**
   * Deployed services on this stack from other repos.
   * Used by the EC2/nginx preset to generate composite docker-compose and Caddyfile configs
   * that include all services on the stack, not just the current app's services.
   * Absent when no sibling services are registered in the registry.
   */
  siblingServices?: SiblingService[];
}

/**
 * Get the flat env map for a specific service from a `PresetContext`.
 *
 * Handles both single-service (`resolvedEnv` is a flat map) and multi-service
 * (`resolvedEnv` is keyed by service name) cases without requiring type casts
 * in preset code.
 *
 * @param ctx - The preset context.
 * @param serviceName - The service to retrieve env vars for.
 * @returns A flat `Record<string, string>` for the specified service.
 *
 * @example
 * ```ts
 * import { getServiceEnv } from '@lastshotlabs/slingshot-infra';
 *
 * const env = getServiceEnv(ctx, 'api');
 * // { DATABASE_URL: '...', NODE_ENV: 'production', ... }
 * ```
 */
export function getServiceEnv(ctx: PresetContext, serviceName: string): Record<string, string> {
  if (!ctx.infra.services) {
    return ctx.resolvedEnv as Record<string, string>;
  }
  return (ctx.resolvedEnv as Record<string, Record<string, string>>)[serviceName] ?? {};
}

/**
 * A file generated by a `PresetProvider` for deployment.
 *
 * Generated files are written to a temp directory during the deploy pipeline.
 * Ephemeral files are never committed to the repository.
 */
export interface GeneratedFile {
  /** Relative path of the generated file (e.g. `'Dockerfile'`, `'sst.config.ts'`). */
  path: string;
  /** File content as a string. */
  content: string;
  /** When `true`, the file exists only during deploy and should not be committed. */
  ephemeral: boolean;
}

/**
 * A deployment preset that generates files and executes deploys for a specific
 * infrastructure pattern (ECS Fargate, EC2/nginx, etc.).
 *
 * @remarks
 * All presets follow the swappable-provider pattern: register via
 * `createPresetRegistry()` and retrieve by name. New presets implement this
 * interface and add a case to the registry — no changes to existing code.
 */
export interface PresetProvider {
  /**
   * Unique identifier for this preset.
   *
   * Used for registry lookup (e.g. `stack.preset === provider.name`) and
   * displayed in CLI output (e.g. `slingshot infra provision --stack main`).
   * Must be unique across all registered presets. Examples: `'ecs'`, `'ec2-nginx'`.
   */
  readonly name: string;

  /**
   * Generate all files required for deployment.
   *
   * Called once per deploy run before any file is written to disk or any remote
   * command is executed. Returns an in-memory list of files to be written to
   * `ctx.tempDir`. Common generated files include:
   * - `Dockerfile` / multi-stage `Dockerfile` variants
   * - `docker-compose.yml` (EC2/nginx preset — includes all sibling services)
   * - `Caddyfile` / `nginx.conf` (reverse-proxy config)
   * - CI workflow fragments (`.github/workflows/deploy.yml`)
   * - SST config (`sst.config.ts`) for ECS/Lambda presets
   * - Any other infrastructure-as-code files needed for this preset
   *
   * @param ctx - The preset context assembled by the deploy pipeline.
   * @returns An array of {@link GeneratedFile} objects. Ephemeral files are
   *   written to `ctx.tempDir` and deleted after the deploy; non-ephemeral files
   *   are intended to be committed to the repository.
   *
   * @throws {Error} If required context fields are missing or misconfigured.
   *
   * @example
   * ```ts
   * const files = provider.generate(ctx);
   * for (const f of files) {
   *   await fs.writeFile(path.join(ctx.tempDir!, f.path), f.content);
   * }
   * ```
   */
  generate(ctx: PresetContext): GeneratedFile[];

  /**
   * Execute the deploy using the previously generated files.
   *
   * Responsible for pushing Docker images to the registry, transferring files to
   * the target host, and updating the running service (e.g. restarting
   * docker-compose, updating an ECS service, or running `sst deploy`). Also
   * updates the registry entry for the service on success.
   *
   * @param ctx - The preset context assembled by the deploy pipeline.
   * @param generatedFiles - The files returned by {@link generate} for this deploy.
   * @returns A {@link DeployResult} indicating success/failure, the live service
   *   URL (if resolvable), and any arbitrary key-value outputs from the deploy.
   *
   * @throws {Error} If a prerequisite (Docker push, SSH connection, AWS call) fails
   *   and the error cannot be represented as a `DeployResult` with `success: false`.
   */
  deploy(ctx: PresetContext, generatedFiles: GeneratedFile[]): Promise<DeployResult>;

  /**
   * Provision stack-level infrastructure.
   *
   * Creates (or updates) all durable infrastructure shared by all services on the
   * stack. Depending on the preset, this may include:
   * - VPC, subnets, security groups
   * - Application Load Balancer (ALB) and target groups
   * - ECS cluster (Fargate preset)
   * - EC2 instance with Docker/Caddy installed (EC2/nginx preset)
   * - IAM roles and instance profiles
   *
   * This method is called once per stack per `slingshot infra provision` invocation,
   * not on every deploy. It is safe to call when infrastructure already exists —
   * implementations should be idempotent (using `--update` or equivalent).
   *
   * @param ctx - The preset context assembled by the provisioner pipeline.
   * @returns A {@link ProvisionResult} with infrastructure outputs (e.g. ALB ARN,
   *   VPC ID, EC2 public IP) that are written to the registry for subsequent deploys.
   *
   * @throws {Error} If the cloud provider returns an unrecoverable error.
   */
  provisionStack(ctx: PresetContext): Promise<ProvisionResult>;

  /**
   * Destroy all stack-level infrastructure provisioned by {@link provisionStack}.
   *
   * @remarks
   * **Irreversible.** This permanently deletes all cloud resources for the stack
   * and stage (ECS cluster, EC2 instance, VPC, ALB, etc.). Data stored on those
   * resources (volumes, databases attached to the instance) will be lost. The
   * registry entry for the stack is updated to `'destroying'` status by the
   * caller before this method is invoked.
   *
   * @param ctx - The preset context assembled by the destroy pipeline.
   *
   * @throws {Error} If the cloud provider returns an error during teardown. Partial
   *   destruction is possible — check the cloud console to verify cleanup.
   */
  destroyStack(ctx: PresetContext): Promise<void>;

  /**
   * Return the default logging configuration for this preset.
   *
   * @remarks
   * Used by `slingshot infra init` to populate the default `logging` block in
   * `slingshot.platform.ts` when the user selects this preset. The `driver` value
   * corresponds to a registered `LogDriver` provider (e.g. `'cloudwatch'`,
   * `'datadog'`). `retentionDays` is passed to the log group creation call.
   *
   * @returns An object with `driver` (log driver name) and `retentionDays`
   *   (default log retention for this preset's typical deployment target).
   */
  defaultLogging(): { driver: string; retentionDays: number };
}

/**
 * Result returned by `PresetProvider.deploy()`.
 */
export interface DeployResult {
  /** Whether the deploy completed successfully. */
  success: boolean;
  /** The live URL of the deployed service (if resolvable). */
  serviceUrl?: string;
  /** Arbitrary key-value outputs from the deploy (e.g. ALB DNS name). */
  outputs?: Record<string, string>;
  /** Error message when `success` is `false`. */
  error?: string;
}

/**
 * Result returned by `PresetProvider.provisionStack()`.
 */
export interface ProvisionResult {
  /** Whether the stack was provisioned successfully. */
  success: boolean;
  /** Infrastructure outputs (e.g. ALB ARN, VPC ID). */
  outputs: Record<string, string>;
  /** Error message when `success` is `false`. */
  error?: string;
}
