/**
 * Initial-migration generator for MongoDB.
 *
 * Mongo is schemaless, so there is no `CREATE TABLE` analog — collections are
 * created lazily on first insert. The "initial" migration for an entity is
 * therefore just the index and unique-constraint creation.
 *
 * Output is a `mongosh`-style script with `db.getCollection(...).createIndex(...)`
 * calls. When run by `slingshot migrate apply`, statements are auto-`await`ed
 * inside an async IIFE.
 */
import { escapeJsString, storageName } from '../../lib/naming';
import type { ResolvedEntityConfig } from '../../types';

function jsonString(value: unknown): string {
  return JSON.stringify(value);
}

function indexSpec(fields: readonly string[], direction: 'asc' | 'desc' | undefined): string {
  const entries = fields.map(f => `${jsonString(f)}: ${direction === 'desc' ? -1 : 1}`);
  return `{ ${entries.join(', ')} }`;
}

export function generateInitialMigrationMongo(config: ResolvedEntityConfig): string {
  const collName = storageName(config, 'mongo');
  const coll = `db.getCollection("${escapeJsString(collName)}")`;
  const sections: string[] = [];

  sections.push(
    [
      '// --- section:header ---',
      `// Initial migration for ${config.name} (MongoDB)`,
      '// Auto-generated by `slingshot migrate generate`. Edit inside section',
      '// markers to preserve overrides across regeneration.',
      '// Mongo is schemaless — only indexes are created here.',
      '// --- end:header ---',
    ].join('\n'),
  );

  const indexes: string[] = ['// --- section:indexes ---'];
  for (const idx of config.indexes ?? []) {
    const spec = indexSpec(idx.fields, idx.direction);
    const options = idx.unique ? ', { unique: true }' : '';
    indexes.push(`${coll}.createIndex(${spec}${options});`);
  }
  for (const uq of config.uniques ?? []) {
    const spec = indexSpec(uq.fields, undefined);
    indexes.push(`${coll}.createIndex(${spec}, { unique: true });`);
  }
  if (indexes.length === 1) {
    indexes.push('// (no indexes declared — collection will be created on first write)');
  }
  indexes.push('// --- end:indexes ---');
  sections.push(indexes.join('\n'));

  return sections.join('\n\n') + '\n';
}
