/**
 * Initial-migration generators — emit `CREATE TABLE` + index DDL for an entity
 * that has no prior snapshot.
 *
 * The diff-based generators (`generateMigrationPostgres`, `generateMigrationSqlite`)
 * only emit `ALTER TABLE`, which is correct for evolution but fails on a fresh
 * database. A "Prisma-style" workflow needs the full create statement on first
 * migration so the migration files capture the entire schema state.
 *
 * Output is deterministic and uses the same section markers as the diff
 * generators so users can edit individual sections without losing them on
 * regeneration.
 */
import {
  escapeSqlString,
  pgColType,
  quoteSqlIdent,
  sqlIndexName,
  sqliteColType,
  storageName,
  toSnakeCase,
} from '../../lib/naming';
import type { FieldDef, ResolvedEntityConfig } from '../../types';

function pgDefaultClause(def: FieldDef): string {
  if (def.default === undefined) return '';
  if (def.default === 'uuid') return ' DEFAULT gen_random_uuid()';
  if (def.default === 'cuid') return '';
  if (def.default === 'now') return ' DEFAULT NOW()';
  if (typeof def.default === 'string') return ` DEFAULT ${escapeSqlString(def.default)}`;
  if (typeof def.default === 'number') return ` DEFAULT ${def.default}`;
  if (typeof def.default === 'boolean') return ` DEFAULT ${def.default}`;
  return '';
}

function sqliteDefaultClause(def: FieldDef): string {
  if (def.default === undefined) return '';
  if (def.default === 'uuid' || def.default === 'cuid') return '';
  if (def.default === 'now') return ` DEFAULT (strftime('%s','now') * 1000)`;
  if (typeof def.default === 'string') return ` DEFAULT ${escapeSqlString(def.default)}`;
  if (typeof def.default === 'number') return ` DEFAULT ${def.default}`;
  if (typeof def.default === 'boolean') return ` DEFAULT ${def.default ? 1 : 0}`;
  return '';
}

/**
 * Generate the initial PostgreSQL `CREATE TABLE` migration for an entity.
 *
 * Emits a single transactional script with `CREATE TABLE IF NOT EXISTS`, all
 * column definitions (types, NOT NULL, defaults, primary key), a TTL column
 * when configured, and `CREATE INDEX` / `CREATE UNIQUE INDEX` statements for
 * declared indexes and unique constraints.
 *
 * Use this when no prior snapshot exists for the entity (first-ever migration).
 * Subsequent changes should use `generateMigrationPostgres()` against a diff.
 */
export function generateInitialMigrationPostgres(config: ResolvedEntityConfig): string {
  const table = storageName(config, 'postgres');
  const qTable = quoteSqlIdent(table);
  const tenantField = config._systemFields.tenantField;
  const hasTenantField = tenantField in config.fields;
  const sections: string[] = [];

  sections.push(
    [
      '-- --- section:header ---',
      `-- Initial migration for ${config.name} (PostgreSQL)`,
      '-- Auto-generated by `slingshot migrate generate`. Edit inside section',
      '-- markers to preserve overrides across regeneration.',
      '-- --- end:header ---',
    ].join('\n'),
  );

  sections.push(
    ['-- --- section:transaction ---', 'BEGIN;', '-- --- end:transaction ---'].join('\n'),
  );

  const colLines: string[] = [];
  for (const [name, def] of Object.entries(config.fields)) {
    const col = quoteSqlIdent(toSnakeCase(name));
    const type = pgColType(def.type);
    const pk = def.primary ? ' PRIMARY KEY' : '';
    const notNull = !def.optional && !def.primary ? ' NOT NULL' : def.primary ? ' NOT NULL' : '';
    const defClause = name === config._concurrency?.field ? ' DEFAULT 1' : pgDefaultClause(def);
    colLines.push(`  ${col} ${type}${pk}${notNull}${defClause}`);
  }

  const ttlSeconds = config.ttl?.defaultSeconds;
  const ttlColumn = config._storageFields?.ttlField;
  if (ttlSeconds && ttlColumn) {
    colLines.push(`  ${quoteSqlIdent(ttlColumn)} BIGINT NOT NULL`);
  }

  const schema: string[] = [
    '-- --- section:schema ---',
    `CREATE TABLE IF NOT EXISTS ${qTable} (`,
    colLines.join(',\n'),
    ');',
    '-- --- end:schema ---',
  ];
  sections.push(schema.join('\n'));

  if (config.tenant?.postgresRls) {
    const tenantColumn = quoteSqlIdent(toSnakeCase(config.tenant.field));
    const policy = quoteSqlIdent(`tenant_isolation_${table}`);
    sections.push(
      [
        '-- --- section:tenant-rls ---',
        `ALTER TABLE ${qTable} ENABLE ROW LEVEL SECURITY;`,
        `ALTER TABLE ${qTable} FORCE ROW LEVEL SECURITY;`,
        `DROP POLICY IF EXISTS ${policy} ON ${qTable};`,
        `CREATE POLICY ${policy} ON ${qTable} USING (${tenantColumn} = current_setting('slingshot.tenant_id', true)) WITH CHECK (${tenantColumn} = current_setting('slingshot.tenant_id', true));`,
        `-- Verify: SELECT polname FROM pg_policies WHERE tablename = ${escapeSqlString(table)} AND polname = ${escapeSqlString(`tenant_isolation_${table}`)};`,
        '-- Runtime transactions must execute: SET LOCAL slingshot.tenant_id = <tenant-id>;',
        '-- --- end:tenant-rls ---',
      ].join('\n'),
    );
  }

  const indexes: string[] = ['-- --- section:indexes ---'];
  for (const idx of config.indexes ?? []) {
    const cols = idx.fields.map(f => quoteSqlIdent(toSnakeCase(f))).join(', ');
    const unique = idx.unique ? 'UNIQUE ' : '';
    const name = quoteSqlIdent(sqlIndexName(table, idx.fields, 'idx'));
    const nullsNotDistinct =
      idx.unique && hasTenantField && idx.fields.includes(tenantField) ? ' NULLS NOT DISTINCT' : '';
    indexes.push(
      `CREATE ${unique}INDEX IF NOT EXISTS ${name} ON ${qTable} (${cols})${nullsNotDistinct};`,
    );
  }
  for (const uq of config.uniques ?? []) {
    const cols = uq.fields.map(f => quoteSqlIdent(toSnakeCase(f))).join(', ');
    const name = quoteSqlIdent(sqlIndexName(table, uq.fields, 'uidx'));
    const nullsNotDistinct =
      hasTenantField && uq.fields.includes(tenantField) ? ' NULLS NOT DISTINCT' : '';
    indexes.push(
      `CREATE UNIQUE INDEX IF NOT EXISTS ${name} ON ${qTable} (${cols})${nullsNotDistinct};`,
    );
  }
  indexes.push('-- --- end:indexes ---');
  sections.push(indexes.join('\n'));

  sections.push(['-- --- section:footer ---', 'COMMIT;', '-- --- end:footer ---'].join('\n'));

  return sections.join('\n\n') + '\n';
}

/**
 * Generate the initial SQLite `CREATE TABLE` migration for an entity.
 *
 * Mirrors `generateInitialMigrationPostgres()` but uses SQLite column types
 * (TEXT/INTEGER/REAL) and SQLite-specific default expressions.
 */
export function generateInitialMigrationSqlite(config: ResolvedEntityConfig): string {
  const table = storageName(config, 'sqlite');
  const qTable = quoteSqlIdent(table);
  const sections: string[] = [];

  sections.push(
    [
      '-- --- section:header ---',
      `-- Initial migration for ${config.name} (SQLite)`,
      '-- Auto-generated by `slingshot migrate generate`. Edit inside section',
      '-- markers to preserve overrides across regeneration.',
      '-- --- end:header ---',
    ].join('\n'),
  );

  sections.push(
    ['-- --- section:transaction ---', 'BEGIN;', '-- --- end:transaction ---'].join('\n'),
  );

  const colLines: string[] = [];
  for (const [name, def] of Object.entries(config.fields)) {
    const col = quoteSqlIdent(toSnakeCase(name));
    const type = sqliteColType(def.type);
    const pk = def.primary ? ' PRIMARY KEY' : '';
    const notNull = !def.optional && !def.primary ? ' NOT NULL' : def.primary ? ' NOT NULL' : '';
    const defClause = name === config._concurrency?.field ? ' DEFAULT 1' : sqliteDefaultClause(def);
    colLines.push(`  ${col} ${type}${pk}${notNull}${defClause}`);
  }

  const ttlSeconds = config.ttl?.defaultSeconds;
  const ttlColumn = config._storageFields?.ttlField;
  if (ttlSeconds && ttlColumn) {
    colLines.push(`  ${quoteSqlIdent(ttlColumn)} INTEGER NOT NULL`);
  }

  const schema: string[] = [
    '-- --- section:schema ---',
    `CREATE TABLE IF NOT EXISTS ${qTable} (`,
    colLines.join(',\n'),
    ');',
    '-- --- end:schema ---',
  ];
  sections.push(schema.join('\n'));

  const indexes: string[] = ['-- --- section:indexes ---'];
  for (const idx of config.indexes ?? []) {
    const cols = idx.fields.map(f => quoteSqlIdent(toSnakeCase(f))).join(', ');
    const unique = idx.unique ? 'UNIQUE ' : '';
    const name = quoteSqlIdent(sqlIndexName(table, idx.fields, 'idx'));
    indexes.push(`CREATE ${unique}INDEX IF NOT EXISTS ${name} ON ${qTable} (${cols});`);
  }
  for (const uq of config.uniques ?? []) {
    const cols = uq.fields.map(f => quoteSqlIdent(toSnakeCase(f))).join(', ');
    const name = quoteSqlIdent(sqlIndexName(table, uq.fields, 'uidx'));
    indexes.push(`CREATE UNIQUE INDEX IF NOT EXISTS ${name} ON ${qTable} (${cols});`);
  }
  indexes.push('-- --- end:indexes ---');
  sections.push(indexes.join('\n'));

  sections.push(['-- --- section:footer ---', 'COMMIT;', '-- --- end:footer ---'].join('\n'));

  return sections.join('\n\n') + '\n';
}
