/**
 * MongoDB migration generator — MigrationPlan → mongosh-runnable script.
 *
 * Mongo is schemaless, so field additions are no-ops at the schema level.
 * Field removals use `$unset` updateMany. Index changes use `createIndex` /
 * `dropIndex`.
 *
 * Collection and field names are never inlined as raw identifiers — they go
 * through `db.getCollection("...")` and bracket notation so hyphens, dots,
 * and reserved characters don't break the generated JavaScript. Output is
 * deterministic (no timestamps); section markers (CLAUDE.md rule 13) let
 * users override specific sections without replacing the whole file.
 */
import { escapeJsString } from '../../lib/naming';
import type { MigrationPlan } from '../types';

function jsonString(value: unknown): string {
  return JSON.stringify(value);
}

function collectionExpr(name: string): string {
  return `db.getCollection("${escapeJsString(name)}")`;
}

function indexSpec(fields: readonly string[], direction: 'asc' | 'desc' | undefined): string {
  const entries = fields.map(f => `${jsonString(f)}: ${direction === 'desc' ? -1 : 1}`);
  return `{ ${entries.join(', ')} }`;
}

/**
 * Generate a MongoDB migration script from a `MigrationPlan`.
 *
 * Produces a `mongosh`-runnable JavaScript file. Because MongoDB is
 * schemaless, field additions are no-ops at the schema level; field removals
 * use `$unset` `updateMany`. Index changes use `createIndex` / `dropIndex`.
 *
 * Collection and field names are never inlined as raw identifiers —
 * `db.getCollection("...")` and bracket notation are used so hyphens, dots,
 * and reserved characters don't break the generated JavaScript.
 *
 * Output is deterministic and split into named sections (CLAUDE.md rule 13).
 *
 * @param plan - Migration plan from `diffEntityConfig()`.
 * @returns The MongoDB migration script string, or an empty string when the
 *   plan has no changes.
 *
 * @example
 * ```ts
 * import { diffEntityConfig, generateMigrationMongo } from '@lastshotlabs/slingshot-entity';
 *
 * const plan = diffEntityConfig(oldConfig, newConfig);
 * const script = generateMigrationMongo(plan);
 * fs.writeFileSync('migrations/mongo.js', script);
 * // Run with: mongosh <db> migrations/mongo.js
 * ```
 */
export function generateMigrationMongo(plan: MigrationPlan): string {
  if (plan.changes.length === 0) return '';

  const coll = collectionExpr(plan.storageNames.mongo);
  const sections: string[] = [];

  // --- section:header ---
  sections.push(
    [
      '// --- section:header ---',
      `// Migration for ${plan.entity} (MongoDB)`,
      '// Auto-generated by `slingshot generate --migration`. Edit inside',
      '// section markers to preserve overrides across regeneration.',
      '// Run with: mongosh <db> migrations/mongo.js',
      '// --- end:header ---',
    ].join('\n'),
  );

  // --- section:warnings ---
  const warnings: string[] = ['// --- section:warnings ---'];
  for (const w of plan.warnings) warnings.push(`// WARNING: ${w}`);
  warnings.push('// --- end:warnings ---');
  sections.push(warnings.join('\n'));

  // --- section:schema ---
  const schema: string[] = ['// --- section:schema ---'];
  // --- section:indexes ---
  const indexes: string[] = ['// --- section:indexes ---'];

  for (const change of plan.changes) {
    switch (change.type) {
      case 'addField': {
        const fieldKey = jsonString(change.name);
        schema.push(`// Field ${fieldKey} added — no migration needed (schemaless).`);
        if (
          change.field.default !== undefined &&
          change.field.default !== 'uuid' &&
          change.field.default !== 'cuid' &&
          change.field.default !== 'now'
        ) {
          const val =
            typeof change.field.default === 'string'
              ? `"${escapeJsString(change.field.default)}"`
              : String(change.field.default);
          schema.push(`// To backfill default value on existing documents:`);
          schema.push(
            `${coll}.updateMany({ [${fieldKey}]: { $exists: false } }, { $set: { [${fieldKey}]: ${val} } });`,
          );
        }
        break;
      }

      case 'removeField': {
        const fieldKey = jsonString(change.name);
        schema.push(`// Remove field ${fieldKey} from all documents:`);
        schema.push(`${coll}.updateMany({}, { $unset: { [${fieldKey}]: "" } });`);
        break;
      }

      case 'changeFieldType': {
        schema.push(
          `// WARNING: Field '${change.name}' type changed from '${change.from}' to '${change.to}'`,
        );
        schema.push(`// Manual data transformation required.`);
        break;
      }

      case 'addIndex': {
        const spec = indexSpec(change.index.fields, change.index.direction);
        const options = change.index.unique ? ', { unique: true }' : '';
        indexes.push(`${coll}.createIndex(${spec}${options});`);
        break;
      }

      case 'removeIndex': {
        const spec = indexSpec(change.index.fields, change.index.direction);
        indexes.push(`${coll}.dropIndex(${spec});`);
        break;
      }

      case 'addUnique': {
        const spec = indexSpec(change.unique.fields, undefined);
        indexes.push(`${coll}.createIndex(${spec}, { unique: true });`);
        break;
      }

      case 'removeUnique': {
        const spec = indexSpec(change.unique.fields, undefined);
        indexes.push(`${coll}.dropIndex(${spec});`);
        break;
      }

      case 'changeSoftDelete':
      case 'changePagination':
        break;
    }
  }

  schema.push('// --- end:schema ---');
  indexes.push('// --- end:indexes ---');
  sections.push(schema.join('\n'));
  sections.push(indexes.join('\n'));

  return sections.join('\n\n') + '\n';
}
