/**
 * PostgreSQL migration generator — MigrationPlan → SQL statements.
 *
 * Output is deterministic (no timestamps) so re-running `slingshot generate
 * --migration` with the same inputs produces byte-identical files. Section
 * markers delimit each logical block so users can override specific sections
 * without replacing the whole file (CLAUDE.md rule 13).
 */
import { escapeSqlString, pgColType, quoteSqlIdent, toSnakeCase } from '../../lib/naming';
import type { FieldDef } from '../../types';
import type { MigrationPlan } from '../types';

function defaultClause(def: FieldDef): string {
  if (def.default === undefined) return '';
  if (def.default === 'uuid') return ' DEFAULT gen_random_uuid()';
  if (def.default === 'cuid') return ''; // runtime default
  if (def.default === 'now') return ' DEFAULT NOW()';
  if (typeof def.default === 'string') return ` DEFAULT ${escapeSqlString(def.default)}`;
  if (typeof def.default === 'number') return ` DEFAULT ${def.default}`;
  if (typeof def.default === 'boolean') return ` DEFAULT ${def.default}`;
  return '';
}

function indexName(table: string, cols: readonly string[], prefix: 'idx' | 'uidx'): string {
  return `${prefix}_${table}_${cols.map(f => toSnakeCase(f)).join('_')}`;
}

/**
 * Generate a PostgreSQL migration script from a `MigrationPlan`.
 *
 * Emits `ALTER TABLE` statements for field additions and removals (wrapped in
 * `BEGIN / COMMIT`), and `CREATE / DROP INDEX` statements for index and unique
 * constraint changes. The output is split into named sections so users can
 * override individual sections without regenerating the whole file
 * (CLAUDE.md rule 13).
 *
 * Output is deterministic — running with the same inputs always produces
 * byte-identical output.
 *
 * @param plan - Migration plan from `diffEntityConfig()`.
 * @returns The PostgreSQL migration SQL string, or an empty string when the
 *   plan has no changes.
 *
 * @remarks
 * - Adding a non-optional column generates an `ADD COLUMN` without `NOT NULL`,
 *   plus a commented-out `SET NOT NULL` that the developer should run after
 *   backfilling existing rows.
 * - Column type changes are emitted as commented-out `ALTER COLUMN … TYPE`
 *   statements that require manual verification before execution.
 * - UUID defaults use `gen_random_uuid()` (available in Postgres ≥ 13 without
 *   extensions, or via `pgcrypto`).
 *
 * @example
 * ```ts
 * import { diffEntityConfig, generateMigrationPostgres } from '@lastshotlabs/slingshot-entity';
 *
 * const plan = diffEntityConfig(oldConfig, newConfig);
 * const sql = generateMigrationPostgres(plan);
 * fs.writeFileSync('migrations/postgres.sql', sql);
 * ```
 */
export function generateMigrationPostgres(plan: MigrationPlan): string {
  if (plan.changes.length === 0) return '';

  const table = plan.storageNames.postgres;
  const qTable = quoteSqlIdent(table);
  const sections: string[] = [];

  // --- section:header ---
  sections.push(
    [
      '-- --- section:header ---',
      `-- Migration for ${plan.entity} (PostgreSQL)`,
      '-- Auto-generated by `slingshot generate --migration`. Edit inside',
      '-- section markers to preserve overrides across regeneration.',
      '-- --- end:header ---',
    ].join('\n'),
  );

  // --- section:warnings ---
  const warnings: string[] = ['-- --- section:warnings ---'];
  for (const w of plan.warnings) warnings.push(`-- WARNING: ${w}`);
  warnings.push('-- --- end:warnings ---');
  sections.push(warnings.join('\n'));

  // --- section:schema ---
  const schema: string[] = ['-- --- section:schema ---', 'BEGIN;'];
  // --- section:indexes ---
  const indexes: string[] = ['-- --- section:indexes ---'];

  for (const change of plan.changes) {
    switch (change.type) {
      case 'addField': {
        const col = quoteSqlIdent(toSnakeCase(change.name));
        const type = pgColType(change.field.type);
        const def = defaultClause(change.field);
        schema.push(`ALTER TABLE ${qTable} ADD COLUMN ${col} ${type}${def};`);
        if (!change.field.optional && !change.field.primary) {
          schema.push(`-- NOTE: Set NOT NULL after backfilling existing rows:`);
          schema.push(`-- ALTER TABLE ${qTable} ALTER COLUMN ${col} SET NOT NULL;`);
        }
        break;
      }

      case 'removeField': {
        const col = quoteSqlIdent(toSnakeCase(change.name));
        schema.push(`ALTER TABLE ${qTable} DROP COLUMN IF EXISTS ${col};`);
        break;
      }

      case 'changeFieldType': {
        const col = quoteSqlIdent(toSnakeCase(change.name));
        const newType = pgColType(change.to);
        schema.push(
          `-- WARNING: Type change on '${change.name}' from '${change.from}' to '${change.to}'`,
        );
        schema.push(`-- Uncomment after verifying data compatibility:`);
        schema.push(
          `-- ALTER TABLE ${qTable} ALTER COLUMN ${col} TYPE ${newType} USING ${col}::${newType};`,
        );
        break;
      }

      case 'addIndex': {
        const cols = change.index.fields.map(f => quoteSqlIdent(toSnakeCase(f))).join(', ');
        const unique = change.index.unique ? 'UNIQUE ' : '';
        const name = quoteSqlIdent(indexName(table, change.index.fields, 'idx'));
        indexes.push(`CREATE ${unique}INDEX IF NOT EXISTS ${name} ON ${qTable} (${cols});`);
        break;
      }

      case 'removeIndex': {
        const name = quoteSqlIdent(indexName(table, change.index.fields, 'idx'));
        indexes.push(`DROP INDEX IF EXISTS ${name};`);
        break;
      }

      case 'addUnique': {
        const cols = change.unique.fields.map(f => quoteSqlIdent(toSnakeCase(f))).join(', ');
        const name = quoteSqlIdent(indexName(table, change.unique.fields, 'uidx'));
        indexes.push(`CREATE UNIQUE INDEX IF NOT EXISTS ${name} ON ${qTable} (${cols});`);
        break;
      }

      case 'removeUnique': {
        const name = quoteSqlIdent(indexName(table, change.unique.fields, 'uidx'));
        indexes.push(`DROP INDEX IF EXISTS ${name};`);
        break;
      }

      case 'changeSoftDelete':
      case 'changePagination':
        break;
    }
  }

  schema.push('-- --- end:schema ---');
  indexes.push('COMMIT;');
  indexes.push('-- --- end:indexes ---');
  sections.push(schema.join('\n'));
  sections.push(indexes.join('\n'));

  return sections.join('\n\n') + '\n';
}
