/**
 * SQLite migration generator — MigrationPlan → SQL statements.
 *
 * Output is deterministic (no timestamps) so re-running `slingshot generate
 * --migration` with the same inputs produces byte-identical files. Section
 * markers delimit each logical block so users can override specific sections
 * without replacing the whole file (CLAUDE.md rule 13).
 */
import { escapeSqlString, quoteSqlIdent, sqliteColType, toSnakeCase } from '../../lib/naming';
import type { FieldDef } from '../../types';
import type { MigrationPlan } from '../types';

function defaultClause(def: FieldDef): string {
  if (def.default === undefined) return '';
  if (def.default === 'uuid' || def.default === 'cuid') return ''; // runtime default
  if (def.default === 'now') return ''; // runtime default
  if (typeof def.default === 'string') return ` DEFAULT ${escapeSqlString(def.default)}`;
  if (typeof def.default === 'number') return ` DEFAULT ${def.default}`;
  if (typeof def.default === 'boolean') return ` DEFAULT ${def.default ? 1 : 0}`;
  return '';
}

function indexName(table: string, cols: readonly string[], prefix: 'idx' | 'uidx'): string {
  return `${prefix}_${table}_${cols.map(f => toSnakeCase(f)).join('_')}`;
}

/**
 * Generate a SQLite migration script from a `MigrationPlan`.
 *
 * Emits `ALTER TABLE` statements for field additions and removals, and
 * `CREATE / DROP INDEX` statements for index and unique constraint changes.
 * The output is split into named sections (`# --- section:schema ---`,
 * `# --- section:indexes ---`) so users can override individual sections
 * without regenerating the whole file (CLAUDE.md rule 13).
 *
 * Output is deterministic — running with the same inputs always produces
 * byte-identical output, so git diffs only show real changes.
 *
 * @param plan - Migration plan from `diffEntityConfig()`.
 * @returns The SQLite migration SQL string, or an empty string when the plan
 *   has no changes.
 *
 * @remarks
 * - SQLite `DROP COLUMN` requires version ≥ 3.35.0. The generator emits the
 *   statement as a comment for safety, requiring the developer to uncomment it.
 * - Column type changes are emitted as warning comments only — SQLite does not
 *   support `ALTER COLUMN TYPE`.
 *
 * @example
 * ```ts
 * import { diffEntityConfig, generateMigrationSqlite } from '@lastshotlabs/slingshot-entity';
 *
 * const plan = diffEntityConfig(oldConfig, newConfig);
 * const sql = generateMigrationSqlite(plan);
 * fs.writeFileSync('migrations/sqlite.sql', sql);
 * ```
 */
export function generateMigrationSqlite(plan: MigrationPlan): string {
  if (plan.changes.length === 0) return '';

  const table = plan.storageNames.sqlite;
  const qTable = quoteSqlIdent(table);
  const sections: string[] = [];

  // --- section:header ---
  const header: string[] = [
    '-- --- section:header ---',
    `-- Migration for ${plan.entity} (SQLite)`,
    '-- Auto-generated by `slingshot migrate generate`. Edit inside section',
    '-- markers to preserve overrides across regeneration.',
    '-- --- end:header ---',
  ];
  sections.push(header.join('\n'));

  // --- section:warnings --- (always present so users can drop notes here)
  const warnings: string[] = ['-- --- section:warnings ---'];
  for (const w of plan.warnings) warnings.push(`-- WARNING: ${w}`);
  warnings.push('-- --- end:warnings ---');
  sections.push(warnings.join('\n'));

  // --- section:schema ---
  const schema: string[] = ['-- --- section:schema ---'];
  // --- section:indexes ---
  const indexes: string[] = ['-- --- section:indexes ---'];

  for (const change of plan.changes) {
    switch (change.type) {
      case 'addField': {
        const col = quoteSqlIdent(toSnakeCase(change.name));
        const type = sqliteColType(change.field.type);
        const def = defaultClause(change.field);
        const needsManualBackfill = !change.field.optional && !change.field.primary && !def;
        if (needsManualBackfill) {
          schema.push(`ALTER TABLE ${qTable} ADD COLUMN ${col} ${type};`);
          schema.push(
            `-- NOTE: Backfill ${col} for existing rows before enforcing NOT NULL in application code or a follow-up table rebuild.`,
          );
          break;
        }
        const notNull = !change.field.optional && !change.field.primary ? ' NOT NULL' : '';
        schema.push(`ALTER TABLE ${qTable} ADD COLUMN ${col} ${type}${notNull}${def};`);
        break;
      }

      case 'removeField': {
        const col = quoteSqlIdent(toSnakeCase(change.name));
        schema.push(`-- SQLite requires 3.35.0+ for DROP COLUMN.`);
        schema.push(`-- ALTER TABLE ${qTable} DROP COLUMN ${col};`);
        break;
      }

      case 'changeFieldType': {
        schema.push(
          `-- WARNING: Field '${change.name}' type changed from '${change.from}' to '${change.to}'`,
        );
        schema.push(`-- SQLite does not support ALTER COLUMN. Manual data migration required.`);
        break;
      }

      case 'addIndex': {
        const cols = change.index.fields.map(f => quoteSqlIdent(toSnakeCase(f))).join(', ');
        const unique = change.index.unique ? 'UNIQUE ' : '';
        const name = quoteSqlIdent(indexName(table, change.index.fields, 'idx'));
        indexes.push(`CREATE ${unique}INDEX IF NOT EXISTS ${name} ON ${qTable} (${cols});`);
        break;
      }

      case 'removeIndex': {
        const name = quoteSqlIdent(indexName(table, change.index.fields, 'idx'));
        indexes.push(`DROP INDEX IF EXISTS ${name};`);
        break;
      }

      case 'addUnique': {
        const cols = change.unique.fields.map(f => quoteSqlIdent(toSnakeCase(f))).join(', ');
        const name = quoteSqlIdent(indexName(table, change.unique.fields, 'uidx'));
        indexes.push(`CREATE UNIQUE INDEX IF NOT EXISTS ${name} ON ${qTable} (${cols});`);
        break;
      }

      case 'removeUnique': {
        const name = quoteSqlIdent(indexName(table, change.unique.fields, 'uidx'));
        indexes.push(`DROP INDEX IF EXISTS ${name};`);
        break;
      }

      case 'changeSoftDelete':
      case 'changePagination':
        // These don't affect the database schema directly.
        break;
    }
  }

  schema.push('-- --- end:schema ---');
  indexes.push('-- --- end:indexes ---');
  sections.push(schema.join('\n'));
  sections.push(indexes.join('\n'));

  return sections.join('\n\n') + '\n';
}
