import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { Command, Flags } from '@oclif/core';
import { createRegistryFromConfig, parseRegistryUrl } from '@lastshotlabs/slingshot-infra';

export default class PlatformPull extends Command {
  static override description =
    'Download the platform config from the shared registry and write it to slingshot.platform.ts';

  static override examples = [
    'SLINGSHOT_REGISTRY=s3://my-platform-registry slingshot platform pull',
  ];

  static override flags = {
    dir: Flags.string({ description: 'Output directory', default: '.' }),
    registry: Flags.string({
      description: 'Registry URL (overrides SLINGSHOT_REGISTRY env var)',
      env: 'SLINGSHOT_REGISTRY',
    }),
  };

  async run() {
    const { flags } = await this.parse(PlatformPull);

    const registryUrl = flags.registry;
    if (!registryUrl) {
      this.error(
        'No registry URL provided. Set SLINGSHOT_REGISTRY env var or use --registry flag.\n' +
          'Example: SLINGSHOT_REGISTRY=s3://my-platform-registry slingshot platform pull',
      );
    }

    const registryConfig = parseRegistryUrl(registryUrl);
    const registry = createRegistryFromConfig(registryConfig);

    this.log(`Reading registry from ${registryConfig.provider}...`);
    const doc = await registry.read();
    if (!doc) {
      this.error('Registry is empty or not initialized.');
    }

    if (!doc.platformConfig) {
      this.error(
        'No platformConfig found in registry. ' +
          'The platform admin must publish the config with `slingshot platform sync`.',
      );
    }

    const outPath = join(flags.dir, 'slingshot.platform.ts');
    const content = [
      `import { definePlatform } from '@lastshotlabs/slingshot-infra';`,
      ``,
      `// Auto-generated by 'slingshot platform pull'. Do not edit by hand.`,
      `// Re-run this command to refresh from the shared registry.`,
      `export default definePlatform(${JSON.stringify(doc.platformConfig, null, 2)});`,
      ``,
    ].join('\n');

    writeFileSync(outPath, content, 'utf-8');
    this.log(`\u2713 Downloaded platform config to ${outPath}`);
  }
}
