#!/usr/bin/env bun
// packages/slingshot-ssg/src/cli.ts
//
// CLI entry point for `slingshot ssg`.
//
// Usage:
//   slingshot ssg [options]
//   bun run ssg
//
// Flags:
//   --routes-dir        Absolute or relative path to server routes dir
//                       (default: server/routes)
//   --assets-manifest   Path to Vite client manifest JSON
//                       (default: dist/client/.vite/manifest.json)
//   --out               Output directory for .html files
//                       (default: dist/static)
//   --concurrency       Parallel render limit (default: 4, max: 256)
//   --renderer          Path to a module that exports a SlingshotSsrRenderer as default
//                       (default: dist/server/entry-server.js)
//   --client-entry      Vite manifest key for client entry chunk
//   --rsc-manifest      Path to rsc-manifest.json generated by snapshotSsr({ rsc: true })
//                       (optional; only used when the renderer implements ssgConfigure())
//   --retry             Maximum render attempts per page for transient failures
//                       (default: 3)
//   --retry-base-delay  Base backoff delay in ms (default: 1000)
//   --retry-max-delay   Maximum backoff delay in ms (default: 30000)
//   --breaker-threshold Consecutive failures before circuit breaker trips
//                       (default: 5; omit to disable breaker)
//   --breaker-cooldown  Circuit breaker cooldown in ms (default: 30000)
//   --watch             Watch routes directory and re-render on changes
//   -h, --help          Show this help message and exit
import { accessSync, constants, existsSync, mkdirSync } from 'node:fs';
import { watch } from 'node:fs';
import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { z } from 'zod';
import type { SlingshotSsrRenderer } from '@lastshotlabs/slingshot-ssr';
import { MAX_CONCURRENCY } from './constants';
import { collectSsgRoutes } from './crawler';
import { renderSsgPages } from './renderer';
import type { SsgConfig } from './types';

// ─── Help text ─────────────────────────────────────────────────────────────────

const HELP_TEXT = `
${'Usage: slingshot-ssg [options]'}
${''}
${'Static site generation for Slingshot applications. Crawls SSR routes and'}
${'renders them into static HTML output.'}
${''}
${'Options:'}
${'  --routes-dir <path>      Path to server routes directory'}
${'                            (default: server/routes)'}
${'  --assets-manifest <path> Path to Vite client manifest JSON'}
${'                            (default: dist/client/.vite/manifest.json)'}
${'  --out <path>             Output directory for generated HTML files'}
${'                            (default: dist/static)'}
${'  --concurrency <number>   Parallel render limit (default: 4, max: 256)'}
${'  --renderer <path>        Path to server entry module'}
${'                            (default: dist/server/entry-server.js)'}
${'  --client-entry <key>     Vite manifest key for client entry chunk'}
${'  --rsc-manifest <path>    Path to RSC manifest from snapshotSsr({ rsc: true })'}
${'  --retry <number>         Max render attempts per page for transient failures'}
${'                            (default: 3)'}
${'  --retry-base-delay <ms>  Base exponential backoff delay (default: 1000)'}
${'  --retry-max-delay <ms>   Max backoff delay (default: 30000)'}
${'  --breaker-threshold <n>  Consecutive failures before circuit trips'}
${'                            (default: 5; omit to disable breaker)'}
${'  --breaker-cooldown <ms>  Circuit breaker cooldown (default: 30000)'}
${'  --watch                  Watch routes directory and re-render on changes'}
${'  -h, --help               Show this help message'}
${''}
${'Examples:'}
${'  slingshot-ssg                              Default configuration'}
${'  slingshot-ssg --out dist/static            Custom output directory'}
${'  slingshot-ssg --concurrency 8 --watch      Higher concurrency with watch'}
${'  slingshot-ssg --help                       Show this help message'}
`;

function printHelp(): void {
  // Help text is assembled from a template literal in HELP_TEXT above.
  // We print via console.log so the output goes to stdout (not stderr),
  // making it pipeable (e.g. slingshot-ssg --help | head).
  console.log(HELP_TEXT);
}

// ─── Argument parsing ─────────────────────────────────────────────────────────

/**
 * Parse and validate a positive integer CLI argument.
 *
 * Rejects `NaN`, non-finite, and non-integer values with an explicit error
 * naming the flag. Optionally clamps the parsed value into `[min, max]` so
 * callers cannot supply pathological values (negative, zero, or absurdly
 * large) that would crash or hang the renderer.
 *
 * @param raw - The raw string from the CLI (already extracted from argv).
 * @param flag - The flag name (without leading `--`) for error messages.
 * @param min - Inclusive lower bound after parse.
 * @param max - Inclusive upper bound after parse.
 * @internal
 */

/**
 * Read a text file, using Bun when available with a Node.js fallback.
 *
 * Bun.file().text() is the fast path; node:fs/promises covers environments
 * where Bun APIs are absent (e.g. CI runners using Node).
 *
 * @internal
 */
async function readTextFile(filePath: string): Promise<string> {
  if (typeof Bun !== 'undefined' && Bun.file) {
    return Bun.file(filePath).text();
  }
  return readFile(filePath, 'utf8');
}

function parsePositiveIntArg(raw: string, flag: string, min: number, max: number): number {
  const parsed = Number(raw);
  if (!Number.isFinite(parsed) || !Number.isInteger(parsed)) {
    throw new Error(`[slingshot-ssg] --${flag} must be a positive integer, got "${raw}"`);
  }
  return Math.max(min, Math.min(parsed, max));
}

export function parseArgs(argv: string[]): {
  routesDir: string;
  assetsManifest: string;
  outDir: string;
  concurrency: number;
  rendererPath: string;
  clientEntry: string | undefined;
  rscManifestPath: string | undefined;
  watch: boolean;
  help: boolean;
  retryMaxAttempts: number;
  retryBaseDelayMs: number;
  retryMaxDelayMs: number;
  breakerThreshold: number | undefined;
  breakerCooldownMs: number | undefined;
} {
  const args: Record<string, string> = {};

  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg.startsWith('--')) {
      const key = arg.slice(2);
      const next = argv[i + 1];
      if (next && !next.startsWith('--')) {
        args[key] = next;
        i++;
      } else {
        args[key] = 'true';
      }
    }
  }

  const concurrency = args['concurrency']
    ? parsePositiveIntArg(args['concurrency'], 'concurrency', 1, MAX_CONCURRENCY)
    : 4;

  const retryMaxAttempts = args['retry'] ? parsePositiveIntArg(args['retry'], 'retry', 1, 10) : 3;

  const retryBaseDelayMs = args['retry-base-delay']
    ? parsePositiveIntArg(args['retry-base-delay'], 'retry-base-delay', 100, 60_000)
    : 1_000;

  const retryMaxDelayMs = args['retry-max-delay']
    ? parsePositiveIntArg(args['retry-max-delay'], 'retry-max-delay', 100, 120_000)
    : 30_000;

  const breakerThreshold = args['breaker-threshold']
    ? parsePositiveIntArg(args['breaker-threshold'], 'breaker-threshold', 1, 100)
    : undefined;

  const breakerCooldownMs = args['breaker-cooldown']
    ? parsePositiveIntArg(args['breaker-cooldown'], 'breaker-cooldown', 1_000, 300_000)
    : undefined;

  return {
    routesDir: args['routes-dir'] ?? 'server/routes',
    assetsManifest: args['assets-manifest'] ?? 'dist/client/.vite/manifest.json',
    outDir: args['out'] ?? 'dist/static',
    concurrency,
    rendererPath: args['renderer'] ?? 'dist/server/entry-server.js',
    clientEntry: args['client-entry'],
    rscManifestPath: args['rsc-manifest'],
    watch: args['watch'] === 'true',
    help: args['help'] === 'true',
    retryMaxAttempts,
    retryBaseDelayMs,
    retryMaxDelayMs,
    breakerThreshold,
    breakerCooldownMs,
  };
}

/**
 * Emit a startup warning when the configured concurrency is close to the
 * process file-descriptor limit.
 *
 * Each in-flight render may open several FDs (route module imports, asset
 * reads, output stream). When concurrency approaches `nofile - reserve`,
 * a large crawl risks EMFILE. The warning is informational only — we still
 * proceed with the requested concurrency.
 *
 * Uses `process.getrlimit?.()` when available (Bun/Deno); on Node.js this
 * API is gated behind `--experimental-permission` and may be undefined,
 * in which case the warning is skipped.
 *
 * @internal
 */
export function warnIfConcurrencyExceedsFdHeadroom(concurrency: number): void {
  // Bun exposes process.getrlimit(); Node does not (or gates it behind
  // --experimental-permission). Feature-detect at the runtime boundary so
  // we degrade gracefully on Node without leaking a hard dependency.
  type ProcessWithGetrlimit = { getrlimit?: () => { nofile?: number } | undefined };
  const getrlimit = (process as unknown as ProcessWithGetrlimit).getrlimit;
  if (typeof getrlimit !== 'function') return;
  const limit = getrlimit();
  const nofile = limit?.nofile;
  if (typeof nofile !== 'number' || nofile <= 0) return;
  // Reserve 256 FDs for stdio, dependencies, and other handles.
  // Allow a quarter of the remaining headroom for parallel renders.
  const safeMax = Math.max(1, Math.floor((nofile - 256) / 4));
  if (concurrency > safeMax) {
    console.warn(
      `[slingshot-ssg] concurrency=${concurrency} is high relative to FD ulimit (${nofile}). ` +
        `Recommended max ~${safeMax}. Large crawls may hit EMFILE — consider lowering ` +
        `--concurrency or raising the file-descriptor limit (\`ulimit -n\`).`,
    );
  }
}

// ─── Asset tag resolution ─────────────────────────────────────────────────────

/**
 * Candidate manifest keys to probe when no explicit `clientEntry` is configured.
 * Checked in order — the first one present in the manifest wins.
 */
const CLIENT_ENTRY_CANDIDATES = [
  'src/client/main.ts',
  'src/client/main.tsx',
  'src/client/index.ts',
  'src/client/index.tsx',
];

/**
 * Read the Vite manifest and build asset tag HTML strings for injection into
 * pre-rendered HTML. Only the JS and CSS assets belonging to the client entry
 * chunk are included — assets from unrelated entry chunks are not injected.
 *
 * Returns an empty string when the manifest does not exist (dev mode or missing
 * build) or when the client entry chunk cannot be found.
 *
 * @param manifestPath - Absolute path to the Vite client manifest JSON.
 * @param clientEntry  - Manifest key for the client entry chunk, or `undefined`
 *                       to auto-detect from {@link CLIENT_ENTRY_CANDIDATES}.
 */
export async function resolveAssetTagsHtml(
  manifestPath: string,
  clientEntry: string | undefined,
): Promise<string> {
  if (!existsSync(manifestPath)) {
    console.warn(
      `[slingshot-ssg] Asset manifest not found at ${manifestPath}. ` +
        `Asset tags will not be injected into pre-rendered pages.`,
    );
    return '';
  }

  try {
    // Inline a minimal manifest parser — avoids importing slingshot-ssr internals
    const raw = await readTextFile(manifestPath);
    const parsed: unknown = JSON.parse(raw);
    if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) {
      console.warn(
        `[slingshot-ssg] Asset manifest at ${manifestPath} is not a JSON object. Asset tags will not be injected.`,
      );
      return '';
    }
    const manifest = parsed as Partial<
      Record<string, { file?: string; css?: string[]; isEntry?: boolean }>
    >;

    // Resolve which manifest key to use for the client entry chunk
    let entryKey: string | undefined = clientEntry;
    if (!entryKey) {
      entryKey = CLIENT_ENTRY_CANDIDATES.find(k => manifest[k]?.isEntry === true);
    }

    if (!entryKey) {
      console.warn(
        `[slingshot-ssg] Could not find a client entry chunk in ${manifestPath}. ` +
          `Pass --client-entry <key> to specify the manifest key explicitly, or ensure ` +
          `the Vite build includes one of: ${CLIENT_ENTRY_CANDIDATES.join(', ')}.`,
      );
      return '';
    }

    const entry = manifest[entryKey];
    if (!entry) {
      console.warn(
        `[slingshot-ssg] Client entry key "${entryKey}" not found in manifest ${manifestPath}.`,
      );
      return '';
    }

    const tags: string[] = [];
    if (entry.css !== undefined) {
      for (const css of entry.css) {
        tags.push(`<link rel="stylesheet" href="/${css}">`);
      }
    }
    if (entry.file) {
      tags.push(`<script type="module" src="/${entry.file}"></script>`);
    }
    return tags.join('\n');
  } catch (err: unknown) {
    console.warn(`[slingshot-ssg] Failed to parse asset manifest:`, err);
    return '';
  }
}

// ─── RSC manifest loading ─────────────────────────────────────────────────────

/**
 * Minimal structural schema for `rsc-manifest.json`.
 *
 * The runner does not need to interpret the manifest — it only forwards the
 * parsed value to the renderer's `ssgConfigure()` hook. We validate that the
 * top-level value is a JSON object containing a `modules` map (the well-known
 * shape produced by `snapshotSsr({ rsc: true })`) so that an obviously wrong
 * file (HTML error page, build log, empty file) fails fast with a clear
 * message instead of being passed through to the renderer where it would
 * surface as a confusing downstream error.
 *
 * Unknown keys are allowed — renderers may extend the manifest format.
 *
 * @internal
 */
const rscManifestSchema = z
  .object({
    modules: z.record(z.string(), z.unknown()),
  })
  .passthrough();

/**
 * Read, parse, and validate an RSC manifest file produced by the Vite build.
 *
 * Distinguishes three failure modes and raises a single, labeled `[slingshot-ssg]`
 * error in each case so the top-level CLI handler can exit with a clean,
 * stack-free message:
 * - File missing (ENOENT) — race between existsSync() and the read, or a
 *   permission error masquerading as missing.
 * - Malformed JSON — `JSON.parse` throws a `SyntaxError`.
 * - Wrong shape — parses as JSON but does not match {@link rscManifestSchema}.
 *
 * The thrown error message always includes the resolved absolute path and a
 * hint about the expected format so the user can correct the input without
 * reading the source.
 *
 * @internal
 */
export async function loadRscManifest(absRscManifest: string): Promise<unknown> {
  let raw: string;
  try {
    raw = await readTextFile(absRscManifest);
  } catch (err: unknown) {
    const code = (err as NodeJS.ErrnoException | undefined)?.code;
    if (code === 'ENOENT') {
      throw new Error(
        `[slingshot-ssg] --rsc-manifest file not readable: ${absRscManifest}\n` +
          `The file does not exist or is not accessible. ` +
          `Ensure the Vite build ran with rsc: true and the manifest path is correct.`,
        { cause: err },
      );
    }
    throw new Error(
      `[slingshot-ssg] --rsc-manifest could not be read: ${absRscManifest}\n` +
        `${err instanceof Error ? err.message : String(err)}`,
      { cause: err },
    );
  }

  if (raw.trim() === '') {
    throw new Error(
      `[slingshot-ssg] --rsc-manifest is empty: ${absRscManifest}\n` +
        `Expected a JSON object produced by snapshotSsr({ rsc: true }) ` +
        `(e.g. { "modules": { ... } }).`,
    );
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch (err: unknown) {
    const detail = err instanceof Error ? err.message : String(err);
    throw new Error(
      `[slingshot-ssg] --rsc-manifest is not valid JSON: ${absRscManifest}\n` +
        `${detail}\n` +
        `Expected a JSON object produced by snapshotSsr({ rsc: true }) ` +
        `(e.g. { "modules": { ... } }).`,
      { cause: err },
    );
  }

  const result = rscManifestSchema.safeParse(parsed);
  if (!result.success) {
    const issues = result.error.issues
      .map(issue => `  - ${issue.path.join('.') || '<root>'}: ${issue.message}`)
      .join('\n');
    throw new Error(
      `[slingshot-ssg] --rsc-manifest has an unexpected shape: ${absRscManifest}\n` +
        `${issues}\n` +
        `Expected a JSON object with a "modules" map (as produced by snapshotSsr({ rsc: true })).`,
    );
  }

  return result.data;
}

// ─── Renderer loading ─────────────────────────────────────────────────────────

/**
 * Dynamically import the server entry bundle and extract a `SlingshotSsrRenderer`.
 *
 * The server entry is expected to export one of:
 * - `export default renderer` — a `SlingshotSsrRenderer` object
 * - `export const renderer` — a `SlingshotSsrRenderer` object
 *
 * Throws when the module cannot be loaded or no renderer is found.
 */
export async function loadRenderer(rendererPath: string): Promise<SlingshotSsrRenderer> {
  const absPath = resolve(process.cwd(), rendererPath);
  if (!existsSync(absPath)) {
    throw new Error(
      `[slingshot-ssg] Renderer module not found: ${absPath}\n` +
        `Run \`vite build --ssr\` before running \`slingshot ssg\`.`,
    );
  }

  const mod = (await import(absPath)) as Record<string, unknown>;
  const renderer = mod['default'] ?? mod['renderer'];

  if (
    !renderer ||
    typeof renderer !== 'object' ||
    typeof (renderer as Record<string, unknown>)['resolve'] !== 'function' ||
    typeof (renderer as Record<string, unknown>)['render'] !== 'function'
  ) {
    throw new Error(
      `[slingshot-ssg] ${absPath} does not export a valid SlingshotSsrRenderer.\n` +
        `Export a default or named "renderer" that has resolve() and render() methods.`,
    );
  }

  return renderer as SlingshotSsrRenderer;
}

// ─── Exit code resolution ─────────────────────────────────────────────────────

/**
 * Tri-state exit codes for `slingshot ssg` (P-SSG-2).
 *
 * Replaces the previous binary 0/1 model so CI can distinguish a run where
 * one route blew up from a run where every route failed (or the build itself
 * crashed). Concretely:
 *
 * - **0** — every page rendered successfully (or there was nothing to do).
 * - **1** — total failure: the build crashed, every page failed, or the run
 *   never produced any successful output (`succeeded === 0 && failed > 0`).
 * - **2** — partial failure: at least one page failed and at least one page
 *   succeeded. The build proceeded; CI should treat this as a degraded state
 *   so consumers know which pages are stale.
 *
 * @see {@link runCli} which calls this with the aggregate result.
 */
export const SsgExitCode = Object.freeze({
  Success: 0,
  TotalFailure: 1,
  PartialFailure: 2,
} as const);

export type SsgExitCode = (typeof SsgExitCode)[keyof typeof SsgExitCode];

/**
 * Resolve the exit code for a completed SSG run.
 *
 * @param succeeded - Number of pages that rendered without error, or a result
 *   object containing total `pages` and collected `errors`.
 * @param failed - Number of pages that recorded an error when numeric counters
 *   are passed.
 * @returns The {@link SsgExitCode} for the run.
 */
export function resolveExitCode(succeeded: number, failed: number): SsgExitCode;
export function resolveExitCode(result: {
  readonly errors: ReadonlyArray<unknown>;
  readonly pages: number;
}): SsgExitCode;
export function resolveExitCode(
  succeededOrResult: number | { readonly errors: ReadonlyArray<unknown>; readonly pages: number },
  failedArg?: number,
): SsgExitCode {
  const failed =
    typeof succeededOrResult === 'number' ? (failedArg ?? 0) : succeededOrResult.errors.length;
  const succeeded =
    typeof succeededOrResult === 'number'
      ? succeededOrResult
      : Math.max(0, succeededOrResult.pages - failed);

  if (failed === 0) return SsgExitCode.Success;
  if (succeeded === 0) return SsgExitCode.TotalFailure;
  return SsgExitCode.PartialFailure;
}

// ─── Main ─────────────────────────────────────────────────────────────────────

/**
 * Print the build summary to the console.
 */
function printSummary(result: {
  readonly succeeded: number;
  readonly failed: number;
  readonly durationMs: number;
  readonly pages: ReadonlyArray<{ readonly path: string; readonly error?: Error }>;
}): void {
  console.log(
    `\n[slingshot-ssg] Done. ${result.succeeded} succeeded, ${result.failed} failed. ` +
      `(${result.durationMs}ms total)`,
  );

  if (result.failed > 0) {
    for (const page of result.pages) {
      if (page.error) {
        console.error(`  ✗ ${page.path}: ${page.error.message}`);
      }
    }
  }
}

export async function runCli(argv = process.argv.slice(2)): Promise<void> {
  const opts = parseArgs(argv);

  // Handle --help
  if (opts.help) {
    printHelp();
    return;
  }

  warnIfConcurrencyExceedsFdHeadroom(opts.concurrency);

  const cwd = process.cwd();
  const config: SsgConfig = Object.freeze({
    serverRoutesDir: resolve(cwd, opts.routesDir),
    assetsManifest: resolve(cwd, opts.assetsManifest),
    outDir: resolve(cwd, opts.outDir),
    concurrency: opts.concurrency,
    clientEntry: opts.clientEntry,
    retry: {
      maxAttempts: opts.retryMaxAttempts,
      baseDelayMs: opts.retryBaseDelayMs,
      maxDelayMs: opts.retryMaxDelayMs,
    },
    circuitBreaker:
      opts.breakerThreshold !== undefined
        ? {
            threshold: opts.breakerThreshold,
            cooldownMs: opts.breakerCooldownMs ?? 30_000,
          }
        : undefined,
  });

  // Crawl routes first — early exit when nothing to render
  console.log('[slingshot-ssg] Collecting SSG routes...');
  const paths = await collectSsgRoutes(config);

  if (paths.length === 0) {
    console.log(
      '[slingshot-ssg] No SSG routes found. ' +
        'Mark routes with `revalidate: false` or export `staticPaths()` / `generateStaticParams()` to enable SSG.',
    );
    return;
  }

  console.log(`[slingshot-ssg] Found ${paths.length} route(s):`, paths);

  // Load renderer only when there are routes to render
  const renderer = await loadRenderer(opts.rendererPath);
  if (opts.rscManifestPath) {
    const absRscManifest = resolve(cwd, opts.rscManifestPath);
    if (!existsSync(absRscManifest)) {
      console.warn(
        `[slingshot-ssg] --rsc-manifest file not found: ${absRscManifest}. ` +
          `RSC rendering will not be active for pre-rendered pages. ` +
          `Ensure the Vite build ran with rsc: true before running SSG.`,
      );
    } else if (typeof renderer.ssgConfigure === 'function') {
      const rscManifest = await loadRscManifest(absRscManifest);
      await renderer.ssgConfigure({ rscManifest });
      console.log(`[slingshot-ssg] RSC manifest loaded from ${absRscManifest}.`);
    } else {
      console.warn(
        `[slingshot-ssg] --rsc-manifest was provided but the renderer does not implement ` +
          `ssgConfigure(). RSC rendering will not be active. ` +
          `Ensure the renderer was created with createReactRenderer() from snapshot >= 0.x.`,
      );
    }
  }

  try {
    mkdirSync(config.outDir, { recursive: true });
    accessSync(config.outDir, constants.W_OK);
  } catch (err) {
    throw new Error(
      `[slingshot-ssg] Cannot write to output directory "${config.outDir}": ${
        err instanceof Error ? err.message : String(err)
      }`,
      { cause: err },
    );
  }

  const assetTagsHtml = await resolveAssetTagsHtml(config.assetsManifest, config.clientEntry);

  console.log(
    `[slingshot-ssg] Rendering ${paths.length} page(s) with concurrency=${opts.concurrency}...`,
  );
  const result = await renderSsgPages(paths, renderer, config, assetTagsHtml);

  printSummary(result);

  // P-SSG-2: tri-state exit code. 0 = full success; 2 = partial failure; 1 =
  // total failure. CI can branch on the difference between "no successful
  // output at all" and "some routes are stale" without parsing log output.
  if (!opts.watch) {
    const exitCode = resolveExitCode(result.succeeded, result.failed);
    if (exitCode !== 0) process.exit(exitCode);
    return;
  }

  // ── Watch mode ──────────────────────────────────────────────────────────────
  console.log(
    `\n[slingshot-ssg] Watching ${config.serverRoutesDir} for changes...` +
      `\n  Press Ctrl+C to stop.`,
  );

  let watchTimeout: ReturnType<typeof setTimeout> | undefined;
  const WATCH_DEBOUNCE_MS = 300;

  const watcher = watch(config.serverRoutesDir, { recursive: true }, () => {
    if (watchTimeout) return;
    watchTimeout = setTimeout(async () => {
      watchTimeout = undefined;
      try {
        console.log('\n[slingshot-ssg] File change detected, re-rendering...');
        const newPaths = await collectSsgRoutes(config);
        if (newPaths.length === 0) {
          console.log('[slingshot-ssg] No SSG routes remain. Waiting for changes...');
          return;
        }
        const newAssetTags = await resolveAssetTagsHtml(config.assetsManifest, config.clientEntry);
        const newResult = await renderSsgPages(newPaths, renderer, config, newAssetTags);
        printSummary(newResult);
      } catch (err: unknown) {
        console.error(
          '[slingshot-ssg] Watch re-render failed:',
          err instanceof Error ? err.message : String(err),
        );
      }
    }, WATCH_DEBOUNCE_MS);
  });

  // Keep the process alive until SIGINT
  await new Promise<void>(resolve => {
    process.on('SIGINT', () => {
      watcher.close();
      console.log('\n[slingshot-ssg] Watch terminated.');
      resolve();
    });
  });
}

if (import.meta.main) {
  runCli().catch((err: unknown) => {
    // Errors produced by the CLI itself are pre-labeled with `[slingshot-ssg]`
    // and have user-facing messages — print them cleanly without a stack
    // trace. Unexpected errors (assertion failures, third-party bugs) are
    // dumped in full so the user can file a bug report.
    if (err instanceof Error && err.message.startsWith('[slingshot-ssg]')) {
      console.error(err.message);
    } else {
      console.error('[slingshot-ssg] Fatal error:', err);
    }
    process.exit(1);
  });
}
