#!/usr/bin/env bun
// packages/slingshot-ssg/src/cli.ts
//
// CLI entry point for `slingshot ssg`.
//
// Usage:
//   slingshot ssg [options]
//   bun run ssg
//
// Flags:
//   --routes-dir        Absolute or relative path to server routes dir
//                       (default: server/routes)
//   --assets-manifest   Path to Vite client manifest JSON
//                       (default: dist/client/.vite/manifest.json)
//   --out               Output directory for .html files
//                       (default: dist/static)
//   --concurrency       Parallel render limit (default: 4)
//   --renderer          Path to a module that exports a SlingshotSsrRenderer as default
//                       (default: dist/server/entry-server.js)
//   --rsc-manifest      Path to rsc-manifest.json generated by snapshotSsr({ rsc: true })
//                       (optional; only used when the renderer implements ssgConfigure())
import { existsSync } from 'node:fs';
import { resolve } from 'node:path';
import type { SlingshotSsrRenderer } from '@lastshotlabs/slingshot-ssr';
import { collectSsgRoutes } from './crawler';
import { renderSsgPages } from './renderer';
import type { SsgConfig } from './types';

// ─── Argument parsing ─────────────────────────────────────────────────────────

function parseArgs(argv: string[]): {
  routesDir: string;
  assetsManifest: string;
  outDir: string;
  concurrency: number;
  rendererPath: string;
  clientEntry: string | undefined;
  rscManifestPath: string | undefined;
} {
  const args: Record<string, string> = {};

  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg.startsWith('--')) {
      const key = arg.slice(2);
      const next = argv[i + 1];
      if (next && !next.startsWith('--')) {
        args[key] = next;
        i++;
      } else {
        args[key] = 'true';
      }
    }
  }

  return {
    routesDir: args['routes-dir'] ?? 'server/routes',
    assetsManifest: args['assets-manifest'] ?? 'dist/client/.vite/manifest.json',
    outDir: args['out'] ?? 'dist/static',
    concurrency: args['concurrency'] ? parseInt(args['concurrency'], 10) : 4,
    rendererPath: args['renderer'] ?? 'dist/server/entry-server.js',
    clientEntry: args['client-entry'],
    rscManifestPath: args['rsc-manifest'],
  };
}

// ─── Asset tag resolution ─────────────────────────────────────────────────────

/**
 * Candidate manifest keys to probe when no explicit `clientEntry` is configured.
 * Checked in order — the first one present in the manifest wins.
 */
const CLIENT_ENTRY_CANDIDATES = [
  'src/client/main.ts',
  'src/client/main.tsx',
  'src/client/index.ts',
  'src/client/index.tsx',
];

/**
 * Read the Vite manifest and build asset tag HTML strings for injection into
 * pre-rendered HTML. Only the JS and CSS assets belonging to the client entry
 * chunk are included — assets from unrelated entry chunks are not injected.
 *
 * Returns an empty string when the manifest does not exist (dev mode or missing
 * build) or when the client entry chunk cannot be found.
 *
 * @param manifestPath - Absolute path to the Vite client manifest JSON.
 * @param clientEntry  - Manifest key for the client entry chunk, or `undefined`
 *                       to auto-detect from {@link CLIENT_ENTRY_CANDIDATES}.
 */
async function resolveAssetTagsHtml(
  manifestPath: string,
  clientEntry: string | undefined,
): Promise<string> {
  if (!existsSync(manifestPath)) {
    console.warn(
      `[slingshot-ssg] Asset manifest not found at ${manifestPath}. ` +
        `Asset tags will not be injected into pre-rendered pages.`,
    );
    return '';
  }

  try {
    // Inline a minimal manifest parser — avoids importing slingshot-ssr internals
    const raw = await Bun.file(manifestPath).text();
    const manifest = JSON.parse(raw) as Partial<
      Record<string, { file?: string; css?: string[]; isEntry?: boolean }>
    >;

    // Resolve which manifest key to use for the client entry chunk
    let entryKey: string | undefined = clientEntry;
    if (!entryKey) {
      entryKey = CLIENT_ENTRY_CANDIDATES.find(k => manifest[k]?.isEntry === true);
    }

    if (!entryKey) {
      console.warn(
        `[slingshot-ssg] Could not find a client entry chunk in ${manifestPath}. ` +
          `Pass --client-entry <key> to specify the manifest key explicitly, or ensure ` +
          `the Vite build includes one of: ${CLIENT_ENTRY_CANDIDATES.join(', ')}.`,
      );
      return '';
    }

    const entry = manifest[entryKey];
    if (!entry) {
      console.warn(
        `[slingshot-ssg] Client entry key "${entryKey}" not found in manifest ${manifestPath}.`,
      );
      return '';
    }

    const tags: string[] = [];
    if (entry.css !== undefined) {
      for (const css of entry.css) {
        tags.push(`<link rel="stylesheet" href="/${css}">`);
      }
    }
    if (entry.file) {
      tags.push(`<script type="module" src="/${entry.file}"></script>`);
    }
    return tags.join('\n');
  } catch (err: unknown) {
    console.warn(`[slingshot-ssg] Failed to parse asset manifest:`, err);
    return '';
  }
}

// ─── Renderer loading ─────────────────────────────────────────────────────────

/**
 * Dynamically import the server entry bundle and extract a `SlingshotSsrRenderer`.
 *
 * The server entry is expected to export one of:
 * - `export default renderer` — a `SlingshotSsrRenderer` object
 * - `export const renderer` — a `SlingshotSsrRenderer` object
 *
 * Throws when the module cannot be loaded or no renderer is found.
 */
async function loadRenderer(rendererPath: string): Promise<SlingshotSsrRenderer> {
  const absPath = resolve(process.cwd(), rendererPath);
  if (!existsSync(absPath)) {
    throw new Error(
      `[slingshot-ssg] Renderer module not found: ${absPath}\n` +
        `Run \`vite build --ssr\` before running \`slingshot ssg\`.`,
    );
  }

  const mod = (await import(absPath)) as Record<string, unknown>;
  const renderer = mod['default'] ?? mod['renderer'];

  if (
    !renderer ||
    typeof renderer !== 'object' ||
    typeof (renderer as Record<string, unknown>)['resolve'] !== 'function' ||
    typeof (renderer as Record<string, unknown>)['render'] !== 'function'
  ) {
    throw new Error(
      `[slingshot-ssg] ${absPath} does not export a valid SlingshotSsrRenderer.\n` +
        `Export a default or named "renderer" that has resolve() and render() methods.`,
    );
  }

  return renderer as SlingshotSsrRenderer;
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  const argv = process.argv.slice(2);
  const opts = parseArgs(argv);

  const cwd = process.cwd();
  const config: SsgConfig = Object.freeze({
    serverRoutesDir: resolve(cwd, opts.routesDir),
    assetsManifest: resolve(cwd, opts.assetsManifest),
    outDir: resolve(cwd, opts.outDir),
    concurrency: opts.concurrency,
    clientEntry: opts.clientEntry,
  });

  console.log('[slingshot-ssg] Collecting SSG routes...');
  const paths = await collectSsgRoutes(config);

  if (paths.length === 0) {
    console.log(
      '[slingshot-ssg] No SSG routes found. ' +
        'Mark routes with `revalidate: false` or export `staticPaths()` / `generateStaticParams()` to enable SSG.',
    );
    return;
  }

  console.log(`[slingshot-ssg] Found ${paths.length} route(s):`, paths);

  const renderer = await loadRenderer(opts.rendererPath);
  if (opts.rscManifestPath) {
    const absRscManifest = resolve(cwd, opts.rscManifestPath);
    if (!existsSync(absRscManifest)) {
      console.warn(
        `[slingshot-ssg] --rsc-manifest file not found: ${absRscManifest}. ` +
          `RSC rendering will not be active for pre-rendered pages. ` +
          `Ensure the Vite build ran with rsc: true before running SSG.`,
      );
    } else if (typeof renderer.ssgConfigure === 'function') {
      const rscManifest = JSON.parse(await Bun.file(absRscManifest).text()) as unknown;
      await renderer.ssgConfigure({ rscManifest });
      console.log(`[slingshot-ssg] RSC manifest loaded from ${absRscManifest}.`);
    } else {
      console.warn(
        `[slingshot-ssg] --rsc-manifest was provided but the renderer does not implement ` +
          `ssgConfigure(). RSC rendering will not be active. ` +
          `Ensure the renderer was created with createReactRenderer() from snapshot >= 0.x.`,
      );
    }
  }
  const assetTagsHtml = await resolveAssetTagsHtml(config.assetsManifest, config.clientEntry);

  console.log(
    `[slingshot-ssg] Rendering ${paths.length} page(s) with concurrency=${opts.concurrency}...`,
  );
  const result = await renderSsgPages(paths, renderer, config, assetTagsHtml);

  console.log(
    `\n[slingshot-ssg] Done. ${result.succeeded} succeeded, ${result.failed} failed. ` +
      `(${result.durationMs}ms total)`,
  );

  if (result.failed > 0) {
    for (const page of result.pages) {
      if (page.error) {
        console.error(`  ✗ ${page.path}: ${page.error.message}`);
      }
    }
    process.exit(1);
  }
}

main().catch((err: unknown) => {
  console.error('[slingshot-ssg] Fatal error:', err);
  process.exit(1);
});
