/**
 * Generates SST config content for provisioning shared AWS resources.
 *
 * Each resource type maps to Pulumi AWS providers (since SST v3 is built on Pulumi),
 * giving fine-grained control over resource configuration.
 */

/**
 * A single resource to include in the generated SST config.
 */
export interface ResourceProvisionEntry {
  /** Logical name for the resource (used as the Pulumi/SST component name). */
  name: string;
  /** Resource type determines which SST/Pulumi component is generated. */
  type: 'postgres' | 'redis' | 'kafka' | 'mongo' | 'documentdb';
  /** Instance class (e.g. `'db.t3.micro'` for RDS, `'cache.t3.micro'` for ElastiCache). */
  instanceClass?: string;
  /** Persistent storage in GB. Relevant for Kafka broker EBS volumes. */
  storageGb?: number;
  /** Engine/framework version string passed to the generated component. */
  engineVersion?: string;
}

/**
 * Options for `generateResourceSstConfig()`.
 */
export interface GenerateResourceSstOptions {
  /** Organization name used as the SST app name prefix. */
  org: string;
  /** AWS region injected into the SST app config. */
  region: string;
  /** Stage name (not embedded in config but used to set the correct SST stage). */
  stageName: string;
}

/**
 * Generate an `sst.config.ts` file with SST/Pulumi resource definitions.
 *
 * Uses SST built-in components where available (`sst.aws.Postgres`,
 * `sst.aws.Redis`) and falls back to raw Pulumi AWS providers for resources
 * SST doesn't wrap (MSK Kafka, DocumentDB). All resource blocks are wrapped
 * in `# --- section:resource-<name> ---` markers for user override support.
 *
 * @param resources - One or more resource entries to include in the config.
 * @param opts - Org name, AWS region, and stage name for the generated app config.
 * @returns The full content of an `sst.config.ts` file as a string.
 *
 * @example
 * ```ts
 * import { generateResourceSstConfig } from '@lastshotlabs/slingshot-infra';
 *
 * const config = generateResourceSstConfig(
 *   [{ name: 'db', type: 'postgres', instanceClass: 'db.t3.micro' }],
 *   { org: 'acme', region: 'us-east-1', stageName: 'production' },
 * );
 * ```
 */
export function generateResourceSstConfig(
  resources: ResourceProvisionEntry[],
  opts: GenerateResourceSstOptions,
): string {
  const resourceBlocks = resources.map(r => generateResourceBlock(r)).join('\n\n');
  const outputLines = resources.flatMap(r => generateOutputLines(r, opts));
  const outputBlock = outputLines.length ? `\n    return {\n${outputLines.join('\n')}\n    };` : '';

  return `// Generated by slingshot — do not commit
/// <reference path="./.sst/platform/config.d.ts" />

export default $config({
  app(input) {
    return {
      name: "${opts.org}-resources",
      home: "aws",
      providers: {
        aws: { region: "${opts.region}" },
      },
    };
  },
  async run() {
    // --- section:vpc ---
    const vpc = new sst.aws.Vpc("ResourceVpc", {
      nat: "managed",
      az: 2,
    });
    // --- end:vpc ---

${resourceBlocks}
${outputBlock}
  },
});
`;
}

/**
 * Sanitize a resource name for use as a TypeScript identifier and SST output key prefix.
 *
 * Strips all characters that are not ASCII letters or digits. This is necessary
 * because resource names from the infra config may contain hyphens, underscores,
 * or other punctuation that are invalid in JavaScript variable names.
 *
 * @param name - The raw resource name (e.g. `'my-db'`, `'cache_01'`).
 * @returns The sanitized name with only `[a-zA-Z0-9]` characters (e.g. `'mydb'`, `'cache01'`).
 */
export function sanitizeResourceName(name: string): string {
  return name.replace(/[^a-zA-Z0-9]/g, '');
}

/**
 * Build the SST output key for a resource attribute.
 *
 * Provisioners and the generated `sst.config.ts` both use this helper so the
 * output naming contract lives in one place instead of being reconstructed by
 * string convention in multiple files.
 *
 * @param resourceName - Raw resource name from the infra config.
 * @param attribute - Output suffix such as `'Host'`, `'Port'`, or `'Brokers'`.
 * @returns The generated output key (e.g. `'mydbHost'`).
 */
export function getResourceOutputKey(resourceName: string, attribute: string): string {
  return `${sanitizeResourceName(resourceName)}${attribute}`;
}

/**
 * Dispatch to the correct SST/Pulumi resource block generator for a single resource.
 *
 * @param resource - The resource entry describing the type and configuration.
 * @returns A multi-line TypeScript string for the `run()` body of `sst.config.ts`,
 *   wrapped in `// --- section:resource-<name> ---` markers.
 */
function generateResourceBlock(resource: ResourceProvisionEntry): string {
  switch (resource.type) {
    case 'postgres':
      return generatePostgresBlock(resource);
    case 'redis':
      return generateRedisBlock(resource);
    case 'kafka':
      return generateKafkaBlock(resource);
    case 'documentdb':
      return generateDocumentDbBlock(resource);
    case 'mongo':
      return generateMongoBlock(resource);
    default:
      throw new Error('Unsupported resource type');
  }
}

/**
 * Generate an `sst.aws.Postgres` (Aurora Serverless v2) resource block.
 *
 * Maps `resource.instanceClass` to an ACU range via `mapInstanceClassToAcu()`
 * and emits a `new sst.aws.Postgres(...)` call attached to the shared VPC.
 *
 * @param resource - The postgres resource entry. `instanceClass` defaults to `'db.t3.micro'`.
 * @returns The TypeScript resource block string, including section markers.
 */
function generatePostgresBlock(resource: ResourceProvisionEntry): string {
  const { min, max } = mapInstanceClassToAcu(resource.instanceClass ?? 'db.t3.micro');
  const name = sanitizeResourceName(resource.name);

  return `    // --- section:resource-${resource.name} ---
    const ${name} = new sst.aws.Postgres("${capitalize(name)}", {
      vpc,
      scaling: {
        min: "${min} ACU",
        max: "${max} ACU",
      },
    });
    // --- end:resource-${resource.name} ---`;
}

/**
 * Generate an `sst.aws.Redis` (ElastiCache Serverless) resource block.
 *
 * The SST Redis component handles cluster mode and scaling automatically.
 * The block is attached to the shared VPC defined earlier in the config.
 *
 * @param resource - The redis resource entry. `instanceClass` is not used by
 *   the SST Redis component and is ignored.
 * @returns The TypeScript resource block string, including section markers.
 */
function generateRedisBlock(resource: ResourceProvisionEntry): string {
  const name = sanitizeResourceName(resource.name);

  return `    // --- section:resource-${resource.name} ---
    const ${name} = new sst.aws.Redis("${capitalize(name)}", {
      vpc,
    });
    // --- end:resource-${resource.name} ---`;
}

/**
 * Generate an `aws.msk.Cluster` (Amazon Managed Streaming for Kafka) resource block.
 *
 * Falls back to raw Pulumi AWS providers because SST v3 does not provide a
 * first-class Kafka component. Uses `mapToKafkaInstanceType()` to translate
 * generic instance class strings to MSK broker instance types.
 *
 * @param resource - The kafka resource entry. `instanceClass` defaults to `'kafka.t3.small'`,
 *   `engineVersion` defaults to `'3.5.1'`, and `storageGb` defaults to `100`.
 * @returns The TypeScript resource block string, including section markers.
 */
function generateKafkaBlock(resource: ResourceProvisionEntry): string {
  const name = sanitizeResourceName(resource.name);
  const instanceType = mapToKafkaInstanceType(resource.instanceClass ?? 'kafka.t3.small');

  return `    // --- section:resource-${resource.name} ---
    const ${name}Cluster = new aws.msk.Cluster("${capitalize(name)}", {
      clusterName: $app.name + "-${resource.name}",
      kafkaVersion: "${resource.engineVersion ?? '3.5.1'}",
      numberOfBrokerNodes: 2,
      brokerNodeGroupInfo: {
        instanceType: "${instanceType}",
        clientSubnets: vpc.privateSubnets,
        securityGroups: vpc.securityGroups,
        storageInfo: {
          ebsStorageInfo: {
            volumeSize: ${resource.storageGb ?? 100},
          },
        },
      },
    });
    // --- end:resource-${resource.name} ---`;
}

/**
 * Generate a DocumentDB-backed Mongo resource block (Pulumi `aws.docdb`).
 *
 * Used when the resource type is `'mongo'` and the deployment target is AWS
 * (DocumentDB is AWS's Mongo-compatible managed service). For true MongoDB
 * Atlas provisioning, the `createMongoProvisioner()` uses the Atlas Admin API
 * directly instead of SST.
 *
 * @param resource - The mongo resource entry. `instanceClass` defaults to `'db.t3.medium'`,
 *   `engineVersion` defaults to `'5.0.0'`.
 * @returns The TypeScript resource block string, including section markers.
 */
function generateMongoBlock(resource: ResourceProvisionEntry): string {
  const name = sanitizeResourceName(resource.name);
  const instanceClass = resource.instanceClass ?? 'db.t3.medium';

  return `    // --- section:resource-${resource.name} ---
    const ${name}Cluster = new aws.docdb.Cluster("${capitalize(name)}", {
      engine: "docdb",
      engineVersion: "${resource.engineVersion ?? '5.0.0'}",
      masterUsername: "admin",
      masterPassword: new sst.Secret("${capitalize(name)}Password").value,
      vpcSecurityGroupIds: vpc.securityGroups,
    });

    const ${name}Instance = new aws.docdb.ClusterInstance("${capitalize(name)}Instance", {
      clusterId: ${name}Cluster.id,
      instanceClass: "${instanceClass}",
    });
    // --- end:resource-${resource.name} ---`;
}

/**
 * Generate an Amazon DocumentDB cluster and instance resource block.
 *
 * Creates a `sst.Secret` for the master password, an `aws.docdb.Cluster`, and an
 * `aws.docdb.ClusterInstance` using Pulumi AWS providers. The secret is referenced
 * as `${name}Password.value` so it is never stored in plaintext in the config.
 *
 * @param resource - The documentdb resource entry. `instanceClass` defaults to `'db.t3.medium'`,
 *   `engineVersion` defaults to `'5.0.0'`.
 * @returns The TypeScript resource block string, including section markers.
 */
function generateDocumentDbBlock(resource: ResourceProvisionEntry): string {
  const name = sanitizeResourceName(resource.name);
  const instanceClass = resource.instanceClass ?? 'db.t3.medium';

  return `    // --- section:resource-${resource.name} ---
    const ${name}Password = new sst.Secret("${capitalize(name)}Password");
    const ${name}Cluster = new aws.docdb.Cluster("${capitalize(name)}", {
      engine: "docdb",
      engineVersion: "${resource.engineVersion ?? '5.0.0'}",
      masterUsername: "admin",
      masterPassword: ${name}Password.value,
      vpcSecurityGroupIds: vpc.securityGroups,
    });

    const ${name}Instance = new aws.docdb.ClusterInstance("${capitalize(name)}Instance", {
      clusterId: ${name}Cluster.id,
      instanceClass: "${instanceClass}",
    });
    // --- end:resource-${resource.name} ---`;
}

/**
 * Generate the `return {}` output lines for a single resource.
 *
 * Each output line exposes a resource attribute as a named export from the SST
 * stack. The keys follow the pattern `${sanitizedName}${Attribute}` (e.g.
 * `dbHost`, `dbPort`) and are used by the provisioner to build connection strings.
 *
 * @param resource - The resource entry describing type and name.
 * @param opts - Org and region options (org used as the DocumentDB default database name).
 * @returns An array of TypeScript assignment strings suitable for the `return {}` block
 *   in `sst.config.ts`, one per output attribute.
 */
function generateOutputLines(
  resource: ResourceProvisionEntry,
  opts: GenerateResourceSstOptions,
): string[] {
  const name = sanitizeResourceName(resource.name);

  switch (resource.type) {
    case 'postgres':
      return [
        `      ${getResourceOutputKey(resource.name, 'Host')}: ${name}.host,`,
        `      ${getResourceOutputKey(resource.name, 'Port')}: ${name}.port,`,
        `      ${getResourceOutputKey(resource.name, 'Username')}: ${name}.username,`,
        `      ${getResourceOutputKey(resource.name, 'Password')}: ${name}.password,`,
        `      ${getResourceOutputKey(resource.name, 'Database')}: ${name}.database,`,
      ];
    case 'redis':
      return [
        `      ${getResourceOutputKey(resource.name, 'Host')}: ${name}.host,`,
        `      ${getResourceOutputKey(resource.name, 'Port')}: ${name}.port,`,
      ];
    case 'kafka':
      return [`      ${getResourceOutputKey(resource.name, 'Brokers')}: ${name}Cluster.bootstrapBrokers,`];
    case 'mongo':
      return [
        `      ${getResourceOutputKey(resource.name, 'Endpoint')}: ${name}Cluster.endpoint,`,
        `      ${getResourceOutputKey(resource.name, 'Port')}: ${name}Cluster.port,`,
      ];
    case 'documentdb':
      return [
        `      ${getResourceOutputKey(resource.name, 'Host')}: ${name}Cluster.endpoint,`,
        `      ${getResourceOutputKey(resource.name, 'Port')}: ${name}Cluster.port,`,
        `      ${getResourceOutputKey(resource.name, 'Username')}: "admin",`,
        `      ${getResourceOutputKey(resource.name, 'Password')}: ${name}Password.value,`,
        `      ${getResourceOutputKey(resource.name, 'Database')}: "${opts.org}",`,
      ];
    default:
      return [];
  }
}

/**
 * Map an RDS instance class string to an Aurora Serverless v2 ACU range.
 *
 * ACU = Aurora Capacity Unit. Approximately 2 GB RAM per ACU.
 * The mapping covers common `db.t3.*` and `db.r5.*` / `db.r6g.*` classes.
 * Unknown instance classes fall back to `{ min: '0.5', max: '4' }`.
 *
 * @param instanceClass - An RDS instance class string (e.g. `'db.t3.micro'`, `'db.r5.xlarge'`).
 * @returns An object with `min` and `max` ACU strings for use in the `scaling` block.
 *
 * @remarks
 * The mapping table:
 * | instanceClass     | min ACU | max ACU |
 * |-------------------|---------|---------|
 * | db.t3.micro       | 0.5     | 2       |
 * | db.t3.small       | 0.5     | 4       |
 * | db.t3.medium      | 1       | 8       |
 * | db.t3.large       | 2       | 16      |
 * | db.r5.large       | 2       | 16      |
 * | db.r5.xlarge      | 4       | 32      |
 * | db.r5.2xlarge     | 8       | 64      |
 * | db.r6g.large      | 2       | 16      |
 * | db.r6g.xlarge     | 4       | 32      |
 * | *(unknown)*       | 0.5     | 4       |
 */
function mapInstanceClassToAcu(instanceClass: string): { min: string; max: string } {
  const mapping: Record<string, { min: string; max: string }> = {
    'db.t3.micro': { min: '0.5', max: '2' },
    'db.t3.small': { min: '0.5', max: '4' },
    'db.t3.medium': { min: '1', max: '8' },
    'db.t3.large': { min: '2', max: '16' },
    'db.r5.large': { min: '2', max: '16' },
    'db.r5.xlarge': { min: '4', max: '32' },
    'db.r5.2xlarge': { min: '8', max: '64' },
    'db.r6g.large': { min: '2', max: '16' },
    'db.r6g.xlarge': { min: '4', max: '32' },
  };

  return mapping[instanceClass] ?? { min: '0.5', max: '4' };
}

/**
 * Map a generic instance class string to an MSK broker instance type.
 *
 * If `instanceClass` already starts with `'kafka.'` it is returned unchanged.
 * Known cross-mappings from RDS/ElastiCache class strings are translated; all
 * other values fall back to `'kafka.t3.small'`.
 *
 * @param instanceClass - An instance class string such as `'kafka.m5.large'`,
 *   `'db.t3.medium'`, or `'cache.t3.micro'`.
 * @returns An MSK broker instance type string (e.g. `'kafka.t3.small'`, `'kafka.m5.large'`).
 */
function mapToKafkaInstanceType(instanceClass: string): string {
  if (instanceClass.startsWith('kafka.')) return instanceClass;
  const mapping: Record<string, string> = {
    'db.t3.small': 'kafka.t3.small',
    'db.t3.medium': 'kafka.m5.large',
    'db.t3.large': 'kafka.m5.large',
    'cache.t3.micro': 'kafka.t3.small',
  };
  return mapping[instanceClass] ?? 'kafka.t3.small';
}

/**
 * Capitalize the first character of a string.
 *
 * Used to produce PascalCase SST component names from the sanitized resource
 * name (e.g. `'db'` → `'Db'`, `'mydb'` → `'Mydb'`).
 *
 * @param str - The string to capitalize.
 * @returns A new string with the first character converted to uppercase.
 */
function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}
