// ============================================================================
// Shared Content Model — type definitions for rich content across slingshot.
//
// Zero runtime imports. Safe for type-only consumers without pulling Zod.
// ============================================================================

/**
 * Content format indicator. Tells the client how to parse the `body` field.
 *
 * - `'plain'` — render as literal text, no markdown parsing, tokens still parsed
 * - `'markdown'` — parse as GitHub-flavored markdown, then parse tokens in text runs
 */
export type ContentFormat = 'plain' | 'markdown';

/**
 * Extended metadata for audio/voice message attachments.
 * Included in `AssetRef` when the attachment is a voice message.
 */
export interface VoiceMetadata {
  /** Duration in seconds. */
  readonly duration: number;
  /** Waveform samples (normalized 0-1) for visual rendering. */
  readonly waveform?: readonly number[];
}

/**
 * Reference to an uploaded asset. Stored in the `attachments` field of content
 * entities. The `assetId` references an Asset record from `slingshot-assets`.
 *
 * Clients use the asset ID to fetch a presigned download URL via the assets plugin.
 */
export interface AssetRef {
  /** Asset entity ID from slingshot-assets. */
  readonly assetId: string;
  /** Original filename for display. */
  readonly filename?: string;
  /** MIME type for rendering (e.g., show image preview vs file icon). */
  readonly mimeType?: string;
  /** File size in bytes for display. */
  readonly size?: number;
  /** Voice/audio metadata (duration, waveform) for voice messages. */
  readonly voice?: VoiceMetadata;
}

/**
 * Resolved link preview data. Stored in the `embeds` field of content entities.
 * Populated asynchronously by slingshot-embeds after content creation.
 *
 * Clients render embeds as preview cards below the content body.
 */
export interface EmbedData {
  /** The URL that was unfurled. */
  readonly url: string;
  /** Page title from Open Graph or `<title>` tag. */
  readonly title?: string;
  /** Page description from Open Graph or meta description. */
  readonly description?: string;
  /** Preview image URL from Open Graph. */
  readonly image?: string;
  /** Site name from Open Graph. */
  readonly siteName?: string;
  /** Favicon URL. */
  readonly favicon?: string;
  /** Content type from Open Graph (e.g., 'article', 'video'). */
  readonly type?: string;
}

/**
 * Snapshot of a quoted message or reply. Populated at creation time.
 * The snapshot does NOT update if the quoted content is later edited.
 */
export interface QuotePreview {
  /** Snippet of the quoted content body (first 200 chars). */
  readonly body: string;
  /** Author of the quoted content. */
  readonly authorId: string;
}

/**
 * Geolocation data for location-sharing messages.
 * Stored in the `location` field when `type` is `'location'`.
 */
export interface LocationData {
  /** Latitude in decimal degrees. */
  readonly lat: number;
  /** Longitude in decimal degrees. */
  readonly lng: number;
  /** Optional display label (e.g., "Central Park"). */
  readonly label?: string;
  /** Optional street address. */
  readonly address?: string;
}

/**
 * Contact card data for contact-sharing messages.
 * Stored in the `contact` field when `type` is `'contact'`.
 */
export interface ContactData {
  /** Display name (required). */
  readonly name: string;
  /** Phone number(s). */
  readonly phones?: readonly string[];
  /** Email address(es). */
  readonly emails?: readonly string[];
  /** Organization or company name. */
  readonly organization?: string;
}

/**
 * Structured event data for system messages.
 * Stored in the `systemEvent` field when `type` is `'system'`.
 *
 * System messages are generated by the server, not authored by users.
 * The `body` field contains a human-readable fallback string.
 */
export interface SystemEventData {
  /** Event type identifier (e.g., 'member_joined', 'room_renamed'). */
  readonly event: string;
  /** Actor who triggered the event (if any). */
  readonly actorId?: string;
  /** Target user of the event (e.g., kicked/invited user). */
  readonly targetId?: string;
  /** Additional event-specific key-value data. */
  readonly data?: Readonly<Record<string, unknown>>;
}

// --- Parser output types ---

/**
 * A single segment of parsed content body. Discriminated by `type`.
 */
export type ContentSegment =
  | { readonly type: 'text'; readonly value: string }
  | { readonly type: 'mention'; readonly userId: string }
  | { readonly type: 'broadcastMention'; readonly target: 'everyone' | 'here' }
  | { readonly type: 'roleMention'; readonly roleId: string }
  | { readonly type: 'contextRef'; readonly contextId: string }
  | { readonly type: 'emoji'; readonly shortcode: string }
  | { readonly type: 'codeSpan'; readonly value: string }
  | { readonly type: 'codeBlock'; readonly value: string; readonly language?: string };

/**
 * Result of parsing a content body for inline tokens.
 *
 * Segments preserve order and duplicates (for rendering).
 * Derived arrays are deduped (for notification routing / indexing).
 */
export interface ParsedContent {
  /** Body segments: text runs interleaved with token references. */
  readonly segments: readonly ContentSegment[];
  /** All mentioned user IDs extracted from `<@...>` tokens (deduped). */
  readonly mentionedUserIds: readonly string[];
  /** Broadcast mentions found: 'everyone', 'here' (deduped). */
  readonly broadcastMentions: readonly ('everyone' | 'here')[];
  /** Role IDs from `<@&roleId>` tokens (deduped). */
  readonly mentionedRoleIds: readonly string[];
  /** All referenced context IDs extracted from `<#...>` tokens (deduped). */
  readonly referencedContextIds: readonly string[];
  /** All custom emoji shortcodes extracted from `:...:` tokens (deduped). */
  readonly emojiShortcodes: readonly string[];
  /** All URLs found in the body text (deduped). */
  readonly urls: readonly string[];
}

// --- Constants ---

/** Hard cap on a content entity's `body` field. Schema layer enforces this. */
export const MAX_CONTENT_BODY_LENGTH = 8_000;

/** Hard cap on the number of mentions in a single content entity. */
export const MAX_CONTENT_MENTIONS = 50;

/** Hard cap on the number of attachments in a single content entity. */
export const MAX_CONTENT_ATTACHMENTS = 10;
