// ---------------------------------------------------------------------------
// WebSocket Message Persistence — repository contract and types
// ---------------------------------------------------------------------------

/**
 * A single WebSocket message that has been persisted to the backing store.
 * Includes a unique ID and a creation timestamp for history and cursor pagination.
 */
export interface StoredMessage {
  /**
   * Unique message identifier.
   *
   * Generated by the repository implementation using nanoid semantics: a URL-safe,
   * cryptographically random string (21 characters by default). IDs are monotonically
   * ordered within a single `(endpoint, room)` scope by insertion order — do not
   * assume lexicographic ordering matches chronological ordering across rooms or
   * repository implementations.
   */
  id: string;
  /** The WebSocket endpoint name the message was broadcast to. */
  endpoint: string;
  /** The room within the endpoint. */
  room: string;
  /**
   * The sender's user ID, or `null` for server-generated messages.
   *
   * Set by the WebSocket endpoint handler at the time the message is dispatched —
   * typically extracted from the authenticated session attached to the WebSocket
   * connection during upgrade. `null` indicates the message was emitted by server-side
   * logic (e.g. system notifications, broadcast events) rather than by a user.
   */
  senderId: string | null;
  /** The message payload (arbitrary JSON). */
  payload: unknown;
  /** When the message was persisted (epoch ms). */
  createdAt: number;
}

/**
 * Default persistence settings applied to rooms that don't specify their own config.
 */
export interface WsMessageDefaults {
  /** Maximum messages to retain per room. Defaults to 100. */
  maxCount?: number;
  /** TTL in seconds for persisted messages. Defaults to 86400 (24 h). */
  ttlSeconds?: number;
}

/**
 * Per-room message persistence configuration.
 * Supplied via `ResolvedPersistence.configureRoom()` during plugin `setupPost`.
 */
export interface RoomPersistenceConfig {
  /** Whether messages should be persisted for this room. */
  persist: boolean;
  /** Override the default max message count for this room. */
  maxCount?: number;
  /** Override the default TTL (in seconds) for this room's messages. */
  ttlSeconds?: number;
}

/**
 * Storage contract for WebSocket message persistence.
 *
 * Implementations store messages per `(endpoint, room)` scope with configurable
 * max count and TTL-based expiration. Used by the framework's WS history and
 * session-recovery features.
 *
 * @example
 * ```ts
 * import type { WsMessageRepository, StoredMessage } from '@lastshotlabs/slingshot-core';
 *
 * // Persist a message:
 * const stored = await wsMessages.persist(message, { maxCount: 200, ttlSeconds: 3600 });
 *
 * // Replay history on reconnect:
 * const history = await wsMessages.getHistory('chat', 'room:abc', { after: lastEventId });
 * ```
 */
export interface WsMessageRepository {
  /**
   * Persist a message to the backing store.
   *
   * Enforces `maxCount` by evicting oldest messages and respects `ttlSeconds` for expiry.
   *
   * @remarks
   * When the total number of persisted messages for the `(endpoint, room)` pair would
   * exceed `maxCount` after inserting this message, the **oldest** messages (by `createdAt`)
   * are deleted first until the count is within the limit. The new message is always
   * persisted regardless of `maxCount` — eviction happens before the insert, not instead of it.
   *
   * @returns The persisted message with a generated `id` and `createdAt` timestamp.
   */
  persist(
    message: StoredMessage,
    config: { maxCount: number; ttlSeconds: number },
  ): Promise<StoredMessage>;

  /**
   * Retrieve message history for a room.
   *
   * Returns messages in oldest-first order. Use `after` to resume from a known message
   * ID (for session recovery) or `before` for reverse pagination.
   *
   * @param endpoint - The WS endpoint name.
   * @param room - The room identifier.
   * @param opts.limit - Max messages to return.
   * @param opts.before - Exclusive upper cursor: return messages whose `id` comes before
   *   this value in insertion order. Used for reverse/infinite-scroll pagination — pass
   *   the oldest ID from the current page to fetch the page before it.
   * @param opts.after - Exclusive lower cursor: return messages whose `id` comes after
   *   this value in insertion order. Used for session recovery — pass the last `id` the
   *   client received to replay only missed messages since reconnect.
   */
  getHistory(
    endpoint: string,
    room: string,
    opts?: { limit?: number; before?: string; after?: string },
  ): Promise<StoredMessage[]>;

  /** Clear all stored messages. Called by `ctx.clear()` for test isolation. */
  clear(): Promise<void>;
}
