import type { GeneratedFile, PresetContext } from '../../../types/preset';
import { resolveDomain } from '../../resolveDomain';

interface CaddyRoute {
  domain: string;
  port: number;
  serviceName: string;
}

/**
 * Generate a `Caddyfile` for automatic HTTPS via the Caddy reverse proxy.
 *
 * Produces one server block per domain-enabled service. Each block configures:
 * - `reverse_proxy <serviceName>:<port>` to proxy traffic to the app container.
 * - `encode gzip` for response compression.
 * - `log` output to `/var/log/caddy/<serviceName>.log`.
 *
 * Caddy automatically provisions TLS certificates via Let's Encrypt (ACME HTTP-01
 * or TLS-ALPN-01) — no manual certbot invocation is required.
 *
 * @param ctx - The current `PresetContext` with infra config, stack name, stage, and sibling services.
 * @returns A `GeneratedFile` with:
 *   - `path`: `'Caddyfile'`
 *   - `content`: the Caddyfile text.
 *   - `ephemeral: true`.
 *
 * @remarks
 * Sibling services (cross-stack dependencies) are appended after the main
 * service blocks if they declare a `domain`. Services without a `domain` field
 * are omitted entirely — Caddy has nothing to bind to without a domain.
 */
export function generateCaddyfile(ctx: PresetContext): GeneratedFile {
  const routes = resolveCaddyRoutes(ctx);

  const blocks = routes.map(
    route =>
      `${route.domain} {
	reverse_proxy ${route.serviceName}:${route.port}
	encode gzip
	log {
		output file /var/log/caddy/${route.serviceName}.log
	}
}`,
  );

  const content = `# Generated by slingshot — do not edit on server
${blocks.join('\n\n')}
`;

  return {
    path: 'Caddyfile',
    content,
    ephemeral: true,
  };
}

function resolveCaddyRoutes(ctx: PresetContext): CaddyRoute[] {
  const infra = ctx.infra;
  const routes: CaddyRoute[] = [];
  const seen = new Set<string>();

  if (infra.services) {
    for (const [name, svc] of Object.entries(infra.services)) {
      const stacks = svc.stacks ?? infra.stacks ?? [];
      if (!stacks.includes(ctx.stackName)) continue;
      if (!svc.domain) continue;

      const domainConfig = svc.domains?.[name] ?? infra.domains?.[name];
      routes.push({
        domain: resolveDomain(svc.domain, ctx.stageName, ctx.stage, domainConfig),
        port: svc.port ?? 3000,
        serviceName: name,
      });
      seen.add(name);
    }
  } else if (infra.domain) {
    const domainConfig = infra.domains?.[ctx.serviceName];
    routes.push({
      domain: resolveDomain(infra.domain, ctx.stageName, ctx.stage, domainConfig),
      port: infra.port ?? 3000,
      serviceName: ctx.serviceName,
    });
    seen.add(ctx.serviceName);
  }

  for (const sibling of ctx.siblingServices ?? []) {
    if (seen.has(sibling.name)) continue;
    if (!sibling.domain) continue;
    routes.push({
      domain: sibling.domain,
      port: sibling.port ?? 3000,
      serviceName: sibling.name,
    });
  }

  return routes;
}
