import type { GeneratedFile, PresetContext } from '../../../types/preset';
import { getServiceEnv } from '../../../types/preset';

export interface ProxyOptions {
  /** Use nginx instead of caddy */
  nginx?: boolean;
  /** Include certbot service for automatic SSL cert provisioning */
  certbot?: boolean;
}

interface ComposeService {
  name: string;
  port: number;
  image: string;
  env: Record<string, string>;
}

/**
 * Generate a `docker-compose.yml` for EC2-based deployments.
 *
 * Includes service blocks for every app service in scope (filtered by
 * `stacks`), plus a reverse proxy service (Caddy by default, or nginx if
 * `proxyOpts.nginx` is `true`). When fluentd logging is enabled a `fluentd`
 * service block and the appropriate Docker logging driver options are injected.
 * When `proxyOpts.certbot` is `true`, a `certbot` service with shared volumes
 * is added for Let's Encrypt certificate provisioning.
 *
 * @param ctx - The current `PresetContext` with infra config, registry URL, and image tag.
 * @param proxyOpts - Optional proxy override flags:
 *   - `nginx`: use nginx instead of Caddy (default `false`).
 *   - `certbot`: include the certbot service for SSL provisioning (default `false`).
 * @returns A `GeneratedFile` with:
 *   - `path`: `'docker-compose.yml'`
 *   - `content`: the YAML compose file text.
 *   - `ephemeral: true`.
 *
 * @remarks
 * Caddy volumes (`caddy_data`, `caddy_config`) are defined when using Caddy so
 * that TLS certificates and configuration survive container restarts. Certbot
 * volumes (`certbot_data`, `certbot_certs`) are defined when `certbot` is true.
 * Sibling services (from `ctx.siblingServices`) are appended last, using their
 * own image references.
 */
export function generateDockerCompose(ctx: PresetContext, proxyOpts?: ProxyOptions): GeneratedFile {
  const services = resolveComposeServices(ctx);
  const logging = ctx.infra.logging;
  const isFluentd = logging?.driver === 'fluentd';
  const fluentdEndpoint = logging?.fluentd?.endpoint ?? 'localhost:24224';
  const tagPrefix = logging?.fluentd?.tagPrefix ?? ctx.serviceName;

  const serviceEntries = services
    .map(svc => {
      const envLines = Object.entries(svc.env)
        .map(([k, v]) => `        ${k}: "${v}"`)
        .join('\n');

      const loggingBlock = isFluentd
        ? `    logging:
      driver: fluentd
      options:
        fluentd-address: "${fluentdEndpoint}"
        tag: "${tagPrefix}.${svc.name}"`
        : `    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "3"`;

      const dependsOn = isFluentd ? `\n    depends_on:\n      - fluentd` : '';

      return `  ${svc.name}:
    image: ${svc.image}
    restart: always
    ports:
      - "${svc.port}:${svc.port}"
    environment:
${envLines}
${loggingBlock}${dependsOn}`;
    })
    .join('\n\n');

  const fluentdService = isFluentd
    ? `
  fluentd:
    image: fluent/fluentd:v1.16-1
    restart: always
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./fluent.conf:/fluentd/etc/fluent.conf:ro

`
    : '';

  const useNginx = proxyOpts?.nginx === true;
  const useCertbot = proxyOpts?.certbot === true;

  const proxyService = useNginx
    ? `  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro${useCertbot ? '\n      - certbot_data:/var/www/certbot:ro\n      - certbot_certs:/etc/letsencrypt:ro' : ''}`
    : `  caddy:
    image: caddy:2-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config`;

  const certbotService = useCertbot
    ? `
  certbot:
    image: certbot/certbot
    volumes:
      - certbot_data:/var/www/certbot
      - certbot_certs:/etc/letsencrypt
`
    : '';

  const volumes = useNginx
    ? useCertbot
      ? `volumes:
  certbot_data:
  certbot_certs:`
      : ''
    : `volumes:
  caddy_data:
  caddy_config:`;

  const content = `# Generated by slingshot — do not edit on server
services:
${proxyService}
${fluentdService}${certbotService}
${serviceEntries}

${volumes}
`;

  return {
    path: 'docker-compose.yml',
    content,
    ephemeral: true,
  };
}

function resolveComposeServices(ctx: PresetContext): ComposeService[] {
  const infra = ctx.infra;
  const services: ComposeService[] = [];
  const seen = new Set<string>();

  if (infra.services) {
    for (const [name, svc] of Object.entries(infra.services)) {
      const stacks = svc.stacks ?? infra.stacks ?? [];
      if (!stacks.includes(ctx.stackName)) continue;
      services.push({
        name,
        port: svc.port ?? 3000,
        image: `${ctx.dockerRegistry}/${name}:${ctx.imageTag}`,
        env: getServiceEnv(ctx, name),
      });
      seen.add(name);
    }
  }

  if (!infra.services && !seen.has(ctx.serviceName)) {
    services.push({
      name: ctx.serviceName,
      port: ctx.infra.port ?? 3000,
      image: `${ctx.dockerRegistry}/${ctx.serviceName}:${ctx.imageTag}`,
      env: getServiceEnv(ctx, ctx.serviceName),
    });
    seen.add(ctx.serviceName);
  }

  for (const sibling of ctx.siblingServices ?? []) {
    if (seen.has(sibling.name)) continue;
    const siblingStage = Object.prototype.hasOwnProperty.call(sibling.stages, ctx.stageName)
      ? sibling.stages[ctx.stageName]
      : undefined;
    services.push({
      name: sibling.name,
      port: sibling.port ?? 3000,
      image:
        sibling.image ??
        `${ctx.dockerRegistry}/${sibling.name}:${siblingStage?.imageTag ?? ctx.imageTag}`,
      env: sibling.env ?? {},
    });
    seen.add(sibling.name);
  }

  return services;
}
