import type { GeneratedFile, PresetContext } from '../../../types/preset';

/**
 * Generate a GitHub Actions workflow file for EC2/docker-compose deployments.
 *
 * The workflow triggers on pushes to `main` that touch any service path or
 * `packages/`. It builds and pushes Docker images to GHCR using the GitHub
 * Actions actor token (`secrets.GITHUB_TOKEN`), then deploys to the remote
 * EC2 instance via `appleboy/ssh-action` using SSH secrets
 * (`DEPLOY_HOST_<STAGENAME>`, `DEPLOY_USER`, `DEPLOY_KEY`).
 *
 * The remote deploy script runs:
 * ```sh
 * docker compose pull <services>
 * docker compose up -d --no-deps <services>
 * docker image prune -f
 * ```
 *
 * @param ctx - The current `PresetContext` with infra config, stage name, service info,
 *   and docker registry URL.
 * @returns A `GeneratedFile` with:
 *   - `path`: `.github/workflows/deploy-<stageName>.yml`
 *   - `content`: the YAML workflow text.
 *   - `ephemeral: true`.
 *
 * @remarks
 * Unlike the ECS workflow, this does not use OIDC or SST — it uses direct SSH
 * access to the EC2 instance. The workflow tags images with both `:latest` and
 * `:<sha>` for rollback support.
 */
export function generateEc2GhaWorkflow(ctx: PresetContext): GeneratedFile {
  const { stageName, serviceName, service, infra } = ctx;
  const servicePath = service?.path ?? '.';

  const services = infra.services ? Object.keys(infra.services) : [serviceName];
  const pathTriggers = infra.services
    ? Object.values(infra.services)
        .map(s => `      - '${s.path}/**'`)
        .join('\n')
    : `      - '${servicePath}/**'`;

  const content = `# Generated by slingshot — do not commit
name: Deploy to ${stageName}

on:
  push:
    branches: [main]
    paths:
${pathTriggers}
      - 'packages/**'

env:
  REGISTRY: ghcr.io

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: \${{ github.actor }}
          password: \${{ secrets.GITHUB_TOKEN }}

${services
  .map(
    svc => `      - name: Build and push ${svc}
        run: |
          docker build -f Dockerfile.${svc} -t ghcr.io/\${{ github.repository }}/${svc}:latest -t ghcr.io/\${{ github.repository }}/${svc}:\${{ github.sha }} .
          docker push ghcr.io/\${{ github.repository }}/${svc}:latest
          docker push ghcr.io/\${{ github.repository }}/${svc}:\${{ github.sha }}`,
  )
  .join('\n\n')}

      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: \${{ secrets.DEPLOY_HOST_${stageName.toUpperCase()} }}
          username: \${{ secrets.DEPLOY_USER }}
          key: \${{ secrets.DEPLOY_KEY }}
          script: |
            cd /opt/apps
            docker compose pull ${services.join(' ')}
            docker compose up -d --no-deps ${services.join(' ')}
            docker image prune -f
`;

  return {
    path: `.github/workflows/deploy-${stageName}.yml`,
    content,
    ephemeral: true,
  };
}
