import type { DomainConfig, NginxConfig } from '../../../types/infra';
import type { GeneratedFile, PresetContext } from '../../../types/preset';
import { resolveDomain } from '../../resolveDomain';

export interface NginxSslOptions {
  /** Path to SSL certificate on the server. Default: '/etc/letsencrypt/live/{domain}/fullchain.pem' */
  certPath?: string;
  /** Path to SSL private key on the server. Default: '/etc/letsencrypt/live/{domain}/privkey.pem' */
  keyPath?: string;
  /** Enable automatic certbot provisioning via docker. Default: true */
  certbot?: boolean;
  /** Email for Let's Encrypt registration */
  email?: string;
}

interface NginxRoute {
  domain: string;
  port: number;
  serviceName: string;
  ssl: boolean;
}

const DEFAULT_GZIP_TYPES = [
  'text/plain',
  'text/css',
  'application/json',
  'application/javascript',
  'text/xml',
  'application/xml',
];

/**
 * Generate an `nginx.conf` for EC2/docker-compose deployments using nginx as the reverse proxy.
 *
 * The generated config includes:
 * - An `events` block (wrapped in `# --- section:events ---`).
 * - An `http` block (wrapped in `# --- section:http ---`) containing:
 *   - Gzip compression settings (`# --- section:gzip ---`).
 *   - Optional rate limiting zone (`# --- section:rate-limit ---`).
 *   - Client body size limit (`# --- section:client-body ---`).
 *   - Proxy and keepalive timeouts (`# --- section:timeouts ---`).
 *   - Optional custom directives (`# --- section:custom-directives ---`).
 *   - Per-service upstream blocks (`# --- section:upstream-<serviceName> ---`).
 *   - Per-service server blocks (`# --- section:server-<serviceName> ---`).
 *
 * When `DomainConfig.ssl` is not `false` (the default), the server block
 * includes an HTTP→HTTPS redirect and a TLS server with the cert/key paths
 * from `sslOpts` (defaulting to Let's Encrypt paths under `/etc/letsencrypt`).
 *
 * @param ctx - The current `PresetContext` with infra config, stack name, stage, and service info.
 * @param sslOpts - Optional SSL certificate paths and certbot email. When omitted,
 *   Let's Encrypt paths derived from the domain name are used.
 * @returns A `GeneratedFile` with:
 *   - `path`: `'nginx.conf'`
 *   - `content`: the nginx configuration text.
 *   - `ephemeral: true`.
 *
 * @remarks
 * WebSocket support (`proxy_http_version 1.1`, `Upgrade`/`Connection` headers)
 * is injected when `infra.nginx.websocket` is `true`. Static file serving is
 * added when `infra.nginx.staticFiles` is configured.
 */
export function generateNginxConfig(ctx: PresetContext, sslOpts?: NginxSslOptions): GeneratedFile {
  const routes = resolveNginxRoutes(ctx);
  const nginx = resolveNginxDirectives(ctx);

  const httpLevelDirectives = generateHttpDirectives(nginx);
  const upstreamBlocks = routes.map(route => generateUpstreamBlock(route, nginx));
  const serverBlocks = routes.map(route => {
    if (route.ssl) {
      return generateSslServerBlocks(route, nginx, sslOpts);
    }
    return generateHttpOnlyServerBlock(route, nginx);
  });

  const content = `# Generated by slingshot — do not edit on server
# --- section:events ---
events {
    worker_connections 1024;
}
# --- end:events ---

# --- section:http ---
http {
${httpLevelDirectives}
${upstreamBlocks.join('\n\n')}

${serverBlocks.join('\n\n')}
}
# --- end:http ---
`;

  return {
    path: 'nginx.conf',
    content,
    ephemeral: true,
  };
}

/** Merge service-level and top-level nginx config, service takes precedence */
function resolveNginxDirectives(ctx: PresetContext): NginxConfig {
  const topLevel = ctx.infra.nginx ?? {};
  // For now, use top-level config. Per-service nginx could be added later.
  return topLevel;
}

function generateHttpDirectives(nginx: NginxConfig): string {
  const lines: string[] = [];

  // --- Gzip ---
  lines.push('    # --- section:gzip ---');
  const gzipEnabled = nginx.gzip !== false;
  if (gzipEnabled) {
    const gzipConfig = typeof nginx.gzip === 'object' ? nginx.gzip : {};
    const minLength = gzipConfig.minLength ?? '1k';
    const level = gzipConfig.level ?? 6;
    const types = gzipConfig.types ?? DEFAULT_GZIP_TYPES;

    lines.push('    gzip on;');
    lines.push(`    gzip_min_length ${minLength};`);
    lines.push(`    gzip_comp_level ${level};`);
    lines.push(`    gzip_types ${types.join(' ')};`);
    lines.push('    gzip_vary on;');
  }
  lines.push('    # --- end:gzip ---');

  // --- Rate limiting zone ---
  if (nginx.rateLimit) {
    lines.push('');
    lines.push('    # --- section:rate-limit ---');
    const zone = nginx.rateLimit.zone ?? 'api_limit';
    const rps = nginx.rateLimit.requestsPerSecond ?? 10;
    lines.push(`    limit_req_zone $binary_remote_addr zone=${zone}:10m rate=${rps}r/s;`);
    lines.push('    # --- end:rate-limit ---');
  }

  // --- Client body size ---
  lines.push('');
  lines.push('    # --- section:client-body ---');
  const bodySize = nginx.clientMaxBodySize ?? '10m';
  lines.push(`    client_max_body_size ${bodySize};`);
  lines.push('    # --- end:client-body ---');

  // --- Timeouts ---
  lines.push('');
  lines.push('    # --- section:timeouts ---');
  const timeouts = nginx.timeouts ?? {};
  lines.push(`    proxy_connect_timeout ${timeouts.connect ?? '60s'};`);
  lines.push(`    proxy_read_timeout ${timeouts.read ?? '60s'};`);
  lines.push(`    proxy_send_timeout ${timeouts.send ?? '60s'};`);
  lines.push(`    keepalive_timeout ${timeouts.keepalive ?? '65s'};`);
  lines.push('    # --- end:timeouts ---');

  // --- Custom directives ---
  if (nginx.customDirectives && nginx.customDirectives.length > 0) {
    lines.push('');
    lines.push('    # --- section:custom-directives ---');
    for (const directive of nginx.customDirectives) {
      lines.push(`    ${directive}`);
    }
    lines.push('    # --- end:custom-directives ---');
  }

  return lines.join('\n');
}

function generateUpstreamBlock(route: NginxRoute, nginx: NginxConfig): string {
  const lines: string[] = [];
  lines.push(`    # --- section:upstream-${route.serviceName} ---`);
  lines.push(`    upstream ${route.serviceName} {`);

  const strategy = nginx.loadBalancing ?? 'round-robin';
  if (strategy === 'least-conn') {
    lines.push('        least_conn;');
  } else if (strategy === 'ip-hash') {
    lines.push('        ip_hash;');
  }
  // round-robin is nginx default, no directive needed

  lines.push(`        server ${route.serviceName}:${route.port};`);
  lines.push('    }');
  lines.push(`    # --- end:upstream-${route.serviceName} ---`);

  return lines.join('\n');
}

function generateLocationBlock(route: NginxRoute, nginx: NginxConfig, indent: string): string {
  const lines: string[] = [];

  // Static files
  if (nginx.staticFiles) {
    lines.push(`${indent}# --- section:static-files ---`);
    lines.push(`${indent}location ${nginx.staticFiles.urlPath} {`);
    lines.push(`${indent}    alias ${nginx.staticFiles.fsPath};`);
    if (nginx.staticFiles.cacheControl) {
      lines.push(`${indent}    expires ${nginx.staticFiles.cacheControl};`);
      lines.push(`${indent}    add_header Cache-Control "public, immutable";`);
    }
    lines.push(`${indent}}`);
    lines.push(`${indent}# --- end:static-files ---`);
    lines.push('');
  }

  // Main location
  lines.push(`${indent}# --- section:proxy ---`);
  lines.push(`${indent}location / {`);

  // Rate limiting
  if (nginx.rateLimit) {
    const zone = nginx.rateLimit.zone ?? 'api_limit';
    const burst = nginx.rateLimit.burst ?? 20;
    lines.push(`${indent}    limit_req zone=${zone} burst=${burst} nodelay;`);
  }

  lines.push(`${indent}    proxy_pass http://${route.serviceName};`);
  lines.push('');
  lines.push(`${indent}    proxy_set_header Host $host;`);
  lines.push(`${indent}    proxy_set_header X-Real-IP $remote_addr;`);
  lines.push(`${indent}    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;`);
  lines.push(`${indent}    proxy_set_header X-Forwarded-Proto $scheme;`);

  // WebSocket
  if (nginx.websocket) {
    lines.push('');
    lines.push(`${indent}    proxy_http_version 1.1;`);
    lines.push(`${indent}    proxy_set_header Upgrade $http_upgrade;`);
    lines.push(`${indent}    proxy_set_header Connection "upgrade";`);
  }

  lines.push(`${indent}}`);
  lines.push(`${indent}# --- end:proxy ---`);

  return lines.join('\n');
}

function generateHttpOnlyServerBlock(route: NginxRoute, nginx: NginxConfig): string {
  const locationBlock = generateLocationBlock(route, nginx, '        ');

  return `    # --- section:server-${route.serviceName} ---
    server {
        listen 80;
        server_name ${route.domain};

${locationBlock}
    }
    # --- end:server-${route.serviceName} ---`;
}

function generateSslServerBlocks(
  route: NginxRoute,
  nginx: NginxConfig,
  sslOpts?: NginxSslOptions,
): string {
  const certPath = sslOpts?.certPath ?? `/etc/letsencrypt/live/${route.domain}/fullchain.pem`;
  const keyPath = sslOpts?.keyPath ?? `/etc/letsencrypt/live/${route.domain}/privkey.pem`;
  const locationBlock = generateLocationBlock(route, nginx, '        ');

  return `    # --- section:server-${route.serviceName} ---
    server {
        listen 80;
        server_name ${route.domain};

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl http2;
        server_name ${route.domain};

        ssl_certificate ${certPath};
        ssl_certificate_key ${keyPath};

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers on;
        ssl_session_cache shared:SSL:10m;
        ssl_session_timeout 10m;

${locationBlock}
    }
    # --- end:server-${route.serviceName} ---`;
}

function resolveNginxRoutes(ctx: PresetContext): NginxRoute[] {
  const infra = ctx.infra;
  const routes: NginxRoute[] = [];

  if (infra.services) {
    for (const [name, svc] of Object.entries(infra.services)) {
      const stacks = svc.stacks ?? infra.stacks ?? [];
      if (!stacks.includes(ctx.stackName)) continue;
      if (!svc.domain) continue;

      const domainConfig = svc.domains?.[name] ?? infra.domains?.[name];
      const ssl = resolveSsl(domainConfig);
      routes.push({
        domain: resolveDomain(svc.domain, ctx.stageName, ctx.stage, domainConfig),
        port: svc.port ?? 3000,
        serviceName: name,
        ssl,
      });
    }
  } else if (infra.domain) {
    const domainConfig = infra.domains?.[ctx.serviceName];
    const ssl = resolveSsl(domainConfig);
    routes.push({
      domain: resolveDomain(infra.domain, ctx.stageName, ctx.stage, domainConfig),
      port: infra.port ?? 3000,
      serviceName: ctx.serviceName,
      ssl,
    });
  }

  return routes;
}

/** SSL defaults to true when a domain is configured */
function resolveSsl(domainConfig?: DomainConfig): boolean {
  return domainConfig?.ssl !== false;
}
