import type { FluentdConfig, FluentdOutput } from '../../types/infra';
import type { GeneratedFile } from '../../types/preset';

/**
 * Generate a `fluent.conf` file for Fluentd log aggregation.
 *
 * Produces a Fluentd configuration with a `<source>` block listening on the
 * configured port (parsed from `fluentdConfig.endpoint`, defaulting to `24224`)
 * and one `<match>` block per configured output destination. If no outputs are
 * configured, defaults to a `stdout` match for the tag prefix.
 *
 * Supported output types: `'elasticsearch'`, `'s3'`, `'cloudwatch'`, `'stdout'`.
 * Unknown output types also fall back to stdout.
 *
 * @param fluentdConfig - Optional Fluentd-specific configuration from
 *   `InfraLoggingConfig.fluentd`. When `undefined`, uses `localhost:24224` as the
 *   endpoint and `appName` as the tag prefix.
 * @param appName - Application or service name used as the default tag prefix
 *   when `fluentdConfig.tagPrefix` is not specified.
 * @returns A `GeneratedFile` with:
 *   - `path`: `'fluent.conf'`
 *   - `content`: the Fluentd configuration text.
 *   - `ephemeral: true`.
 */
export function generateFluentdConfig(
  fluentdConfig: FluentdConfig | undefined,
  appName: string,
): GeneratedFile {
  const tagPrefix = fluentdConfig?.tagPrefix ?? appName;
  const endpoint = fluentdConfig?.endpoint ?? 'localhost:24224';
  const [, port] = parseEndpoint(endpoint);

  const outputBlocks = buildOutputBlocks(fluentdConfig?.outputs, tagPrefix);

  const content = `# Generated by slingshot — do not edit manually
<source>
  @type forward
  port ${port}
  bind 0.0.0.0
</source>

${outputBlocks}
`;

  return {
    path: 'fluent.conf',
    content,
    ephemeral: true,
  };
}

function parseEndpoint(endpoint: string): [string, string] {
  const parts = endpoint.split(':');
  const host = parts[0] || 'localhost';
  const port = parts[1] || '24224';
  return [host, port];
}

function buildOutputBlocks(outputs: FluentdOutput[] | undefined, tagPrefix: string): string {
  if (!outputs || outputs.length === 0) {
    // Default: stdout output
    return `<match ${tagPrefix}.**>
  @type stdout
</match>`;
  }

  return outputs.map(output => buildSingleOutput(output, tagPrefix)).join('\n\n');
}

function buildSingleOutput(output: FluentdOutput, tagPrefix: string): string {
  const extraLines = output.config
    ? Object.entries(output.config)
        .filter(([k]) => k !== 'host' && k !== 'port')
        .map(([k, v]) => `  ${k} ${v}`)
        .join('\n')
    : '';

  switch (output.type) {
    case 'elasticsearch':
      return `<match ${tagPrefix}.**>
  @type elasticsearch
  host ${output.config?.host ?? 'elasticsearch'}
  port ${output.config?.port ?? '9200'}
  logstash_format true
  logstash_prefix ${tagPrefix}${extraLines ? `\n${extraLines}` : ''}
</match>`;

    case 's3':
      return `<match ${tagPrefix}.**>
  @type s3${extraLines ? `\n${extraLines}` : ''}
</match>`;

    case 'cloudwatch':
      return `<match ${tagPrefix}.**>
  @type cloudwatch_logs${extraLines ? `\n${extraLines}` : ''}
</match>`;

    case 'stdout':
      return `<match ${tagPrefix}.**>
  @type stdout${extraLines ? `\n${extraLines}` : ''}
</match>`;

    default:
      return `<match ${tagPrefix}.**>
  @type stdout
</match>`;
  }
}
