import { createVerificationToken } from '@auth/lib/emailVerification';
import { type TokenClaims, signToken, verifyToken } from '@auth/lib/jwt';
import { createMfaChallenge } from '@auth/lib/mfaChallenge';
import { getSuspended } from '@auth/lib/suspension';
import { generateEmailOtpCode, generateWebAuthnAuthenticationOptions } from '@auth/services/mfa';
import {
  HttpError,
  bestEffort,
  generateSecureToken,
  sha256,
  timingSafeEqual,
} from '@lastshotlabs/slingshot-core';
import type { HookContext } from '../config/authConfig';
import type { SessionMetadata } from '../lib/session/index.js';
import type { AuthRuntimeContext } from '../runtime';

/**
 * The response payload returned by login, register, and OAuth callback routes.
 *
 * When MFA is required the `token` field is an empty string and the caller
 * must complete a second factor using `mfaToken` before a real session is
 * issued.  In the normal (non-MFA) case `token` is the signed JWT and
 * `mfaRequired` / `mfaToken` / `mfaMethods` are absent.
 */
export interface AuthResult {
  /**
   * Signed JWT access token.  Empty string (`""`) when `mfaRequired` is
   * `true` — the session has not been created yet.
   */
  token: string;
  /** Authenticated user's ID. */
  userId: string;
  /** User's email address when known. */
  email?: string;
  /**
   * Whether the user's email address has been verified.  Only present when
   * `AuthConfig.emailVerification` is enabled.
   */
  emailVerified?: boolean;
  /**
   * Whether the user has a Google provider linked.  Included so the client
   * can show "Sign in with Google" or "Link Google" UI accordingly.
   */
  googleLinked?: boolean;
  /**
   * Opaque refresh token string.  Only present when
   * `AuthConfig.refreshToken` is configured.
   */
  refreshToken?: string;
  /**
   * `true` when MFA is required before a session is created.  The client
   * must submit `mfaToken` + a second-factor credential to the
   * `POST /auth/mfa/verify` endpoint.
   */
  mfaRequired?: boolean;
  /**
   * Short-lived token identifying the pending MFA challenge.  Present only
   * when `mfaRequired` is `true`.
   */
  mfaToken?: string;
  /**
   * Enabled MFA methods for this user (e.g. `["totp", "emailOtp"]`).
   * Present when `mfaRequired` is `true` so the client knows which
   * factor options to offer.
   */
  mfaMethods?: string[];
  /**
   * WebAuthn authentication options generated by the server.  Present when
   * `mfaMethods` includes `"webauthn"` and the user has registered
   * credentials.  Should be passed directly to the browser's
   * `navigator.credentials.get()` call.
   */
  webauthnOptions?: Record<string, unknown>;
}

/**
 * Invokes the `preLogin` lifecycle hook if one is configured, passing the identifier
 * and request context to the hook.
 *
 * Throwing inside `preLogin` aborts the login attempt — the error propagates to the
 * route handler. Used by dependent plugins (e.g. `slingshot-oauth`) to apply the same
 * hook contract as the standard login route.
 *
 * @param identifier - The login identifier (email, username, or phone).
 * @param runtime - The active auth runtime context.
 * @param hookContext - Optional request-scoped context (IP, user-agent, request ID).
 *
 * @example
 * import { runPreLoginHook } from '@lastshotlabs/slingshot-auth/plugin';
 *
 * await runPreLoginHook(email, runtime, { ip: clientIp, userAgent });
 */
export const runPreLoginHook = async (
  identifier: string,
  runtime: AuthRuntimeContext,
  hookContext?: HookContext,
): Promise<void> => {
  const hooks = runtime.config.hooks;
  if (hooks.preLogin) await hooks.preLogin({ identifier, ...hookContext });
};

/**
 * Emits the standard login-success security events on the event bus.
 *
 * Publishes `security.auth.login.success` (security audit) and `auth:login` (application
 * event for SSE/push notification subscribers). Called by both the standard login route
 * and dependent plugins (OAuth, magic link, passkey) to maintain uniform event emission.
 *
 * @param userId - The authenticated user's ID.
 * @param sessionId - The newly created session ID.
 * @param runtime - The active auth runtime context.
 *
 * @example
 * import { emitLoginSuccess } from '@lastshotlabs/slingshot-auth/plugin';
 *
 * emitLoginSuccess(userId, sessionId, runtime);
 */
export const emitLoginSuccess = (
  userId: string,
  sessionId: string,
  runtime: AuthRuntimeContext,
): void => {
  runtime.eventBus.emit('security.auth.login.success', { userId });
  runtime.eventBus.emit('auth:login', { userId, sessionId });
};

/**
 * Creates a JWT, persists the session, and optionally issues a refresh token.
 *
 * This is the core session-issuance primitive shared by all login paths
 * (password login, OAuth, magic link, passkey).  It performs the following
 * steps in order:
 *
 * 1. Invokes `hooks.postLogin` to collect custom JWT claims (errors are
 *    swallowed with a console warning — a broken hook must not block login).
 * 2. Strips JOSE-reserved claims (`exp`, `iat`, `sub`, `sid`, etc.) from any
 *    custom claims so a hook cannot override security-critical fields.
 * 3. Signs the JWT with the configured expiry (access token expiry when
 *    refresh tokens are enabled; absolute session timeout otherwise).
 * 4. Atomically creates the session via `atomicCreateSession`, evicting the
 *    oldest if `maxSessions` is exceeded.
 * 5. Computes and stores the session-binding fingerprint when binding fields
 *    (`ip`, `ua`) are derivable from `metadata` (avoids the window before the
 *    first authenticated request).
 * 6. Issues and stores a refresh token when `config.refreshToken` is set.
 * 7. Emits `security.auth.session.created`.
 *
 * @param userId - The authenticated user's ID.
 * @param sessionId - Pre-generated session UUID.
 * @param runtime - The active auth runtime context.
 * @param metadata - Optional IP address and user-agent from the login request.
 * @param hookContext - Optional request-scoped context forwarded to `postLogin`.
 * @returns An object with the signed `token`, optional `refreshToken`, and `sessionId`.
 */
async function createSessionWithRefreshToken(
  userId: string,
  sessionId: string,
  runtime: AuthRuntimeContext,
  metadata?: SessionMetadata,
  hookContext?: HookContext,
): Promise<{ token: string; refreshToken?: string; sessionId: string }> {
  const { config, eventBus } = runtime;
  const hooks = config.hooks;

  // Fire postLogin before signing the token so customClaims can be injected
  let customClaims: Record<string, unknown> | undefined;
  if (hooks.postLogin) {
    try {
      const result = await hooks.postLogin({ userId, sessionId, ...hookContext });
      if (result && typeof result === 'object' && result.customClaims) {
        customClaims = result.customClaims;
      }
    } catch (e) {
      console.error(
        '[lifecycle] postLogin hook error:',
        e instanceof Error ? e.message : String(e),
      );
    }
  }

  const rtConfig = config.refreshToken;
  // When refresh tokens are disabled the JWT is the sole credential, so it must carry an explicit
  // expiry. Tie it to the configured session absolute timeout so the two stay in sync; fall back
  // to 604 800 s (7 days) to preserve the historic default for deployments that haven't set
  // absoluteTimeout. Operators who want shorter-lived tokens should configure absoluteTimeout.
  const expirySeconds = rtConfig
    ? (rtConfig.accessTokenExpiry ?? 900)
    : (config.sessionPolicy.absoluteTimeout ?? 604800);
  // Strip JOSE-managed claims and the code-owned identity claims from customClaims so
  // that a postLogin hook returning { exp: 0 } or { sub: "attacker" } cannot override them.
  // The setter methods (setExpirationTime, setIssuedAt, setIssuer, setAudience) always win
  // at the jose level, but stripping here keeps the payload object trustworthy before signing.
  const RESERVED_CLAIMS = new Set(['exp', 'iat', 'nbf', 'iss', 'aud', 'jti', 'sub', 'sid']);
  const safeClaims = customClaims
    ? Object.fromEntries(Object.entries(customClaims).filter(([k]) => !RESERVED_CLAIMS.has(k)))
    : undefined;
  const claims: TokenClaims = { sub: userId, sid: sessionId, ...safeClaims };
  const token = await signToken(claims, expirySeconds, config, runtime.signing);

  const sessionRepo = runtime.repos.session;
  await sessionRepo.atomicCreateSession(
    userId,
    token,
    sessionId,
    config.maxSessions,
    metadata,
    config,
  );

  // Set session fingerprint at creation time to eliminate the window before the first authenticated request.
  // Only set when all configured binding fields are derivable from session metadata (accept-language
  // requires the live request and falls back to being captured on first authenticated use).
  const bindingCfg = runtime.signing?.sessionBinding;
  if (bindingCfg) {
    const opts = typeof bindingCfg === 'object' ? bindingCfg : {};
    const fields: Array<'ip' | 'ua' | 'accept-language'> = opts.fields ?? ['ip', 'ua'];
    if (fields.every(f => f === 'ip' || f === 'ua')) {
      const fingerprint = sha256(
        fields
          .map(f => (f === 'ip' ? (metadata?.ipAddress ?? '') : (metadata?.userAgent ?? '')))
          .join(':'),
      );
      bestEffort(
        sessionRepo.setSessionFingerprint(sessionId, fingerprint),
        '[session-fingerprint]',
      );
    }
  }

  let refreshToken: string | undefined;
  if (rtConfig) {
    refreshToken = generateSecureToken();
    await sessionRepo.setRefreshToken(sessionId, refreshToken, config);
  }

  eventBus.emit('security.auth.session.created', { userId, sessionId });

  return { token, refreshToken, sessionId };
}

/**
 * Creates a new authenticated session for a user.
 *
 * Generates a session ID, signs the JWT, atomically creates the session (evicting the
 * oldest if `maxSessions` is reached), optionally sets a refresh token, fires the
 * `postLogin` hook for custom claims injection, and sets the session fingerprint when
 * binding fields are available from session metadata.
 *
 * Used internally by the standard login/register routes and by dependent plugins
 * (OAuth, magic link, passkey) that need to issue a session after successful
 * authentication.
 *
 * @param userId - The authenticated user's ID.
 * @param runtime - The active auth runtime context.
 * @param metadata - Optional IP address and user-agent for fingerprinting and session listing.
 * @param hookContext - Optional request-scoped context forwarded to `postLogin`.
 * @returns An object containing the JWT `token`, optional `refreshToken`, and `sessionId`.
 *
 * @example
 * import { createSessionForUser } from '@lastshotlabs/slingshot-auth/plugin';
 *
 * const { token, refreshToken, sessionId } = await createSessionForUser(userId, runtime, {
 *   ipAddress: clientIp,
 *   userAgent: req.headers.get('user-agent') ?? undefined,
 * });
 */
export const createSessionForUser = async (
  userId: string,
  runtime: AuthRuntimeContext,
  metadata?: SessionMetadata,
  hookContext?: HookContext,
): Promise<{ token: string; refreshToken?: string; sessionId: string }> => {
  const sessionId = generateSecureToken();
  return createSessionWithRefreshToken(userId, sessionId, runtime, metadata, hookContext);
};

export interface RegisterOptions {
  metadata?: SessionMetadata;
  /** When true, skip session creation. Returns { userId } without a token. */
  skipSession?: boolean;
  hookContext?: HookContext;
}

export const register = async (
  identifier: string,
  password: string,
  runtime: AuthRuntimeContext,
  metadataOrOptions?: SessionMetadata | RegisterOptions,
): Promise<AuthResult> => {
  // Accept both old-style SessionMetadata and new RegisterOptions
  let metadata: SessionMetadata | undefined;
  let skipSession = false;
  let hookContext: HookContext | undefined;
  if (
    metadataOrOptions &&
    ('skipSession' in metadataOrOptions ||
      'metadata' in metadataOrOptions ||
      'hookContext' in metadataOrOptions)
  ) {
    const opts = metadataOrOptions;
    metadata = opts.metadata;
    skipSession = opts.skipSession ?? false;
    hookContext = opts.hookContext;
  } else {
    metadata = metadataOrOptions as SessionMetadata | undefined;
  }

  const { config, adapter, eventBus } = runtime;
  const hooks = config.hooks;
  if (hooks.preRegister) await hooks.preRegister({ identifier, ...hookContext });

  try {
    const hashed = await runtime.password.hash(password);
    const user = await adapter.create(identifier, hashed);
    const role = config.defaultRole;
    if (role && adapter.setRoles) await adapter.setRoles(user.id, [role]);

    let token = '';
    let refreshToken: string | undefined;
    const requiresVerificationBeforeSession =
      config.primaryField === 'email' && !!config.emailVerification?.required;

    if (!skipSession && !requiresVerificationBeforeSession) {
      const sessionId = generateSecureToken();
      const session = await createSessionWithRefreshToken(
        user.id,
        sessionId,
        runtime,
        metadata,
        hookContext,
      );
      token = session.token;
      refreshToken = session.refreshToken;
    }

    const evConfig = config.emailVerification;
    if (evConfig && config.primaryField === 'email') {
      try {
        const verificationToken = await createVerificationToken(
          runtime.repos.verificationToken,
          user.id,
          identifier,
          config,
        );
        eventBus.emit('auth:delivery.email_verification', {
          email: identifier,
          token: verificationToken,
          userId: user.id,
        });
        eventBus.emit('auth:delivery.welcome', { email: identifier, identifier });
      } catch (e) {
        console.error(
          '[email-verification] Failed to send verification email:',
          e instanceof Error ? e.message : String(e),
        );
      }
    }

    eventBus.emit('security.auth.register.success', { userId: user.id });
    eventBus.emit('auth:user.created', { userId: user.id, email: identifier });
    if (hooks.postRegister) {
      const postRegister = hooks.postRegister;
      Promise.resolve()
        .then(() => postRegister({ userId: user.id, identifier, ...hookContext }))
        .catch((e: unknown) =>
          console.error(
            '[lifecycle] postRegister hook error:',
            e instanceof Error ? e.message : String(e),
          ),
        );
    }
    return {
      token,
      userId: user.id,
      email: identifier,
      emailVerified:
        config.primaryField === 'email' && config.emailVerification ? false : undefined,
      refreshToken,
    };
  } catch (err) {
    eventBus.emit('security.auth.register.failure', {});
    throw err;
  }
};

/**
 * Creates a closure-scoped dummy password hash getter for timing-safe login protection.
 *
 * Returns a lazy getter that hashes a fixed placeholder string on first call and
 * caches the result within the closure. The cached hash is used during login when the
 * provided identifier does not match any user, ensuring that timing analysis cannot
 * distinguish between non-existent users and failed password verification.
 *
 * Each call produces an independent instance — no module-level state. This is the
 * factory pattern (Rule 3): each `bootstrapAuth()` call gets its own dummy hash.
 *
 * @param pw - The `RuntimePassword` instance to use for hashing (bcrypt or equivalent).
 * @returns An async getter `() => Promise<string>` that lazily computes and caches the dummy hash.
 *
 * @example
 * import { makeDummyHashGetter } from '@lastshotlabs/slingshot-auth/testing';
 *
 * // Pre-compute the dummy hash in test setup to avoid bcrypt overhead on every test run
 * const getDummyHash = makeDummyHashGetter(passwordRuntime);
 * const hash = await getDummyHash(); // computed once, subsequent calls return cached value
 */
export function makeDummyHashGetter(
  pw: import('@lastshotlabs/slingshot-core').RuntimePassword,
): () => Promise<string> {
  let dummyHash: string | null = null;
  return async function getDummyHash(): Promise<string> {
    if (dummyHash) return dummyHash;
    dummyHash = await pw.hash('dummy-timing-safe-placeholder');
    return dummyHash;
  };
}

/**
 * Enforces the configured email-verification gate for session-issuing login paths.
 *
 * When `emailVerification.required` is enabled for an email-primary app, every auth flow
 * that can mint or rotate user credentials must call this helper before returning success.
 * This keeps password, passkey, OAuth, SAML, and refresh behavior aligned.
 *
 * @param userId - The authenticated user ID that is about to receive fresh credentials.
 * @param runtime - Active auth runtime context used to read config and adapter state.
 * @throws {HttpError} 403 when the user must verify their email before signing in.
 */
export async function assertLoginEmailVerified(
  userId: string,
  runtime: AuthRuntimeContext,
): Promise<void> {
  const { config, adapter } = runtime;
  const evConfig = config.emailVerification;
  if (!evConfig || config.primaryField !== 'email' || !adapter.getEmailVerified) {
    return;
  }
  const verified = await adapter.getEmailVerified(userId);
  if (evConfig.required && !verified) {
    throw new HttpError(403, 'Email not verified');
  }
}

export const login = async (
  identifier: string,
  password: string,
  runtime: AuthRuntimeContext,
  metadata?: SessionMetadata,
  hookContext?: HookContext,
): Promise<AuthResult> => {
  const { config, adapter, eventBus } = runtime;
  await runPreLoginHook(identifier, runtime, hookContext);

  const user = await (adapter.findByIdentifier
    ? adapter.findByIdentifier(identifier)
    : adapter.findByEmail(identifier));

  // Always verify against a hash to prevent timing-based user enumeration.
  // Lockout check is intentionally AFTER bcrypt to prevent timing leaks —
  // locked accounts must take the same bcrypt time as non-existent users.
  const hashToVerify = user?.passwordHash ?? (await runtime.getDummyHash());
  const passwordValid = await runtime.password.verify(password, hashToVerify);

  // Check lockout after bcrypt so locked and non-existent users are indistinguishable by timing
  const lockoutSvc = runtime.lockout;
  if (user) {
    const lockoutDecision = await runtime.securityGate.lockoutCheck(user.id);
    if (!lockoutDecision.allowed) {
      eventBus.emit('security.auth.login.blocked', {
        userId: user.id,
        reason: 'lockout',
        meta: { reason: 'account_locked' },
      });
      // Return the same generic error as invalid credentials to prevent an attacker
      // from confirming that they have successfully locked a target account (DoS vector).
      // The `onLocked` callback and security events still fire for operator-side notification.
      throw new HttpError(401, 'Invalid credentials');
    }
  }

  if (!user || !passwordValid) {
    eventBus.emit('security.auth.login.failure', { identifier, meta: { identifier } });

    // Track failed attempts for lockout (only when user exists — can't lock unknown accounts)
    if (user && lockoutSvc) {
      const count = await lockoutSvc.recordFailedAttempt(user.id);
      if (count >= lockoutSvc.config.maxAttempts) {
        await lockoutSvc.lockAccount(user.id);
        eventBus.emit('security.auth.account.locked', {
          userId: user.id,
          meta: { identifier, attempts: count },
        });
        if (lockoutSvc.config.onLocked) {
          const onLocked = lockoutSvc.config.onLocked;
          Promise.resolve()
            .then(() => onLocked(user.id, identifier))
            .catch(() => {
              /* swallow — notification must never crash login */
            });
        }
      }
    }

    throw new HttpError(401, 'Invalid credentials');
  }

  // Check suspension
  const suspensionStatus = await getSuspended(adapter, user.id);
  if (suspensionStatus.suspended) {
    eventBus.emit('security.auth.login.blocked', {
      reason: 'suspended',
      meta: { reason: 'suspended' },
    });
    throw new HttpError(403, 'Account suspended', 'ACCOUNT_SUSPENDED');
  }

  // Check email verification before MFA to avoid leaking MFA status to unverified users
  const fullUser = adapter.getUser ? await adapter.getUser(user.id) : null;
  const googleLinked = fullUser?.providerIds?.some(id => id.startsWith('google:')) ?? false;

  await assertLoginEmailVerified(user.id, runtime);

  // Check MFA — if enabled, return challenge token instead of session
  if (config.mfa && adapter.isMfaEnabled && (await adapter.isMfaEnabled(user.id))) {
    const methods = adapter.getMfaMethods ? await adapter.getMfaMethods(user.id) : ['totp'];

    // Auto-send email OTP if enabled
    let emailOtpHash: string | undefined;
    const emailOtpConfig = config.mfa.emailOtp ?? null;
    if (methods.includes('emailOtp') && emailOtpConfig) {
      const { code, hash } = generateEmailOtpCode(runtime);
      emailOtpHash = hash;
      const email = fullUser?.email;
      if (email) eventBus.emit('auth:delivery.email_otp', { email, code });
    }

    // Generate WebAuthn authentication options if enabled
    let webauthnChallenge: string | undefined;
    let webauthnOptions: Record<string, unknown> | undefined;
    const webauthnConfig = config.mfa.webauthn ?? null;
    if (methods.includes('webauthn') && webauthnConfig && adapter.getWebAuthnCredentials) {
      const result = await generateWebAuthnAuthenticationOptions(user.id, runtime);
      if (result) {
        webauthnChallenge = result.challenge;
        webauthnOptions = result.options;
      }
    }

    const mfaToken = await createMfaChallenge(
      runtime.repos.mfaChallenge,
      user.id,
      { emailOtpHash, webauthnChallenge },
      config,
    );
    return {
      token: '',
      userId: user.id,
      mfaRequired: true,
      mfaToken,
      mfaMethods: methods,
      webauthnOptions,
    };
  }

  const sessionId = generateSecureToken();
  const { token, refreshToken } = await createSessionWithRefreshToken(
    user.id,
    sessionId,
    runtime,
    metadata,
    hookContext,
  );

  // Reset failure counter on successful login (opt-out via resetOnSuccess: false)
  if (lockoutSvc && lockoutSvc.config.resetOnSuccess !== false) {
    await lockoutSvc.resetFailureCount(user.id);
  }

  emitLoginSuccess(user.id, sessionId, runtime);

  if (config.emailVerification && config.primaryField === 'email' && adapter.getEmailVerified) {
    const verified = await adapter.getEmailVerified(user.id);
    return {
      token,
      userId: user.id,
      email: fullUser?.email,
      emailVerified: verified,
      googleLinked,
      refreshToken,
    };
  }

  return { token, userId: user.id, email: fullUser?.email, googleLinked, refreshToken };
};

/**
 * Exchanges a refresh token for a new access token and rotated refresh token.
 *
 * Validates the presented refresh token against the session store, enforces
 * session-binding fingerprint checks (when configured), atomically rotates
 * the token, and returns fresh credentials.
 *
 * @param refreshTokenValue - Plain-text refresh token presented by the client.
 * @param runtime - The active auth runtime context.
 * @param metadata - Optional request metadata (IP, user-agent) for session-binding
 *   fingerprint verification. When `signing.sessionBinding` is configured and metadata
 *   is provided, the refresh request's fingerprint is compared against the stored
 *   session fingerprint. A mismatch invalidates the session as a token-theft
 *   countermeasure.
 * @returns An object with the new `token`, rotated `refreshToken`, and `userId`.
 *
 * @throws {HttpError} 401 — Refresh token is invalid, expired, or fingerprint mismatch.
 */
export const refresh = async (
  refreshTokenValue: string,
  runtime: AuthRuntimeContext,
  metadata?: SessionMetadata,
): Promise<{ token: string; refreshToken: string; userId: string }> => {
  const sessionRepo = runtime.repos.session;
  const result = await sessionRepo.getSessionByRefreshToken(refreshTokenValue, runtime.config);
  if (!result) {
    throw new HttpError(401, 'Invalid or expired refresh token');
  }

  const { sessionId, userId } = result;

  const suspensionStatus = await getSuspended(runtime.adapter, userId);
  if (suspensionStatus.suspended) {
    throw new HttpError(403, 'Account suspended', 'ACCOUNT_SUSPENDED');
  }
  await assertLoginEmailVerified(userId, runtime);

  // Enforce session-binding fingerprint on refresh to prevent stolen refresh tokens
  // from being used on a different device/network.
  const bindingCfg = runtime.signing?.sessionBinding;
  if (bindingCfg && metadata) {
    const opts = typeof bindingCfg === 'object' ? bindingCfg : {};
    const fields: Array<'ip' | 'ua' | 'accept-language'> = opts.fields ?? ['ip', 'ua'];
    const storedFp = await sessionRepo.getSessionFingerprint(sessionId);
    if (storedFp) {
      const parts = fields.map(f => {
        if (f === 'ip') return metadata.ipAddress ?? '';
        if (f === 'ua') return metadata.userAgent ?? '';
        return '';
      });
      const currentFp = sha256(parts.join(':'));
      if (!timingSafeEqual(storedFp, currentFp)) {
        // Fingerprint mismatch on refresh — likely stolen token. Revoke the session.
        await sessionRepo.deleteSession(sessionId, runtime.config);
        runtime.eventBus.emit('security.auth.session.fingerprint_mismatch', {
          userId,
          sessionId,
          meta: { reason: 'refresh_fingerprint_mismatch' },
        });
        throw new HttpError(401, 'Invalid or expired refresh token');
      }
    }
  }

  // Always rotate: generate new refresh + access tokens.
  // Refresh tokens are stored as hashes — we can never return a stored plaintext token.
  // Even in the grace window case (old token used after rotation), we issue fresh tokens.
  // This is safe because the old token's hash was found in the prev slot, not the current slot,
  // so the session is valid and the client just missed the previous rotation response.
  const newRT = generateSecureToken();
  const newAccessToken = await signToken(
    { sub: userId, sid: sessionId },
    runtime.config.refreshToken?.accessTokenExpiry ?? 900,
    runtime.config,
    runtime.signing,
  );
  // Pass the presented token as the guard for normal rotations so concurrent requests
  // using the same token race-to-fail. For grace-window re-rotations the current slot
  // already holds a different token, so skip the guard (undefined = no guard).
  const rotated = await sessionRepo.rotateRefreshToken(
    sessionId,
    result.fromGrace ? undefined : refreshTokenValue,
    newRT,
    newAccessToken,
    runtime.config,
  );
  if (!rotated) {
    throw new HttpError(401, 'Invalid or expired refresh token');
  }
  await sessionRepo.updateSessionLastActive(sessionId, runtime.config);

  return { token: newAccessToken, refreshToken: newRT, userId };
};

export const deleteAccount = async (
  userId: string,
  runtime: AuthRuntimeContext,
  password?: string,
): Promise<void> => {
  const { adapter, config, eventBus } = runtime;
  const hooks = config.hooks;
  if (hooks.preDeleteAccount) await hooks.preDeleteAccount({ userId });

  if (!adapter.deleteUser) {
    throw new HttpError(501, 'Auth adapter does not support deleteUser');
  }

  // Verify password for credential accounts
  if (password) {
    const user = adapter.getUser ? await adapter.getUser(userId) : null;
    const email = user?.email;
    if (email) {
      const found = await (adapter.findByIdentifier
        ? adapter.findByIdentifier(email)
        : adapter.findByEmail(email));
      if (found && !(await runtime.password.verify(password, found.passwordHash))) {
        throw new HttpError(401, 'Invalid password');
      }
    }
  } else if (adapter.hasPassword && (await adapter.hasPassword(userId))) {
    throw new HttpError(400, 'Password is required to delete a credential account');
  }

  // Revoke all sessions
  const sessionRepo = runtime.repos.session;
  const sessions = await sessionRepo.getUserSessions(userId, config);
  await Promise.all(sessions.map(s => sessionRepo.deleteSession(s.sessionId, config)));

  // Delete the user
  await adapter.deleteUser(userId);

  eventBus.emit('security.auth.account.deleted', { userId });
  eventBus.emit('auth:user.deleted', { userId });
  if (hooks.postDeleteAccount) {
    const postDeleteAccount = hooks.postDeleteAccount;
    Promise.resolve()
      .then(() => postDeleteAccount({ userId }))
      .catch((e: unknown) =>
        console.error(
          '[lifecycle] postDeleteAccount hook error:',
          e instanceof Error ? e.message : String(e),
        ),
      );
  }
};

export const logout = async (token: string | null, runtime: AuthRuntimeContext) => {
  if (token) {
    const payload = await verifyToken(token, runtime.config, runtime.signing);
    const sessionId = payload.sid as string | undefined;
    const userId = payload.sub;
    if (sessionId) {
      await runtime.repos.session.deleteSession(sessionId, runtime.config);
      runtime.eventBus.emit('security.auth.logout', { sessionId, userId });
      if (userId) {
        runtime.eventBus.emit('auth:logout', { userId, sessionId });
      }
    }
  }
};

export const passkeyLogin = async (
  passkeyToken: string,
  assertionResponse: Record<string, unknown>,
  runtime: AuthRuntimeContext,
  metadata?: SessionMetadata,
  hookContext?: HookContext,
): Promise<AuthResult> => {
  const { adapter, config, eventBus } = runtime;
  if (!adapter.findUserByWebAuthnCredentialId || !adapter.getWebAuthnCredentials) {
    throw new HttpError(501, 'Auth adapter does not support passkey login');
  }

  const { consumePasskeyLoginChallenge } = await import('@auth/lib/mfaChallenge');
  const challengeData = await consumePasskeyLoginChallenge(
    runtime.repos.mfaChallenge,
    passkeyToken,
  );
  if (!challengeData) {
    throw new HttpError(401, 'Invalid or expired passkey token');
  }

  const credentialId = assertionResponse.id;
  if (
    !credentialId ||
    typeof credentialId !== 'string' ||
    credentialId.length === 0 ||
    credentialId.length > 2048
  ) {
    throw new HttpError(401, 'Invalid assertion response');
  }

  const userId = await adapter.findUserByWebAuthnCredentialId(credentialId);
  if (!userId) {
    throw new HttpError(401, 'Invalid credentials');
  }

  const { verifyWebAuthn } = await import('@auth/services/mfa');
  const verified = await verifyWebAuthn(
    userId,
    assertionResponse as unknown as import('@simplewebauthn/server').AuthenticationResponseJSON,
    challengeData.webauthnChallenge,
    runtime,
  );
  if (!verified) {
    throw new HttpError(401, 'WebAuthn verification failed');
  }

  const fullUser = adapter.getUser ? await adapter.getUser(userId) : null;
  await runPreLoginHook(fullUser?.email ?? userId, runtime, hookContext);

  // Check suspension
  const suspensionStatus = await getSuspended(adapter, userId);
  if (suspensionStatus.suspended) {
    throw new HttpError(403, 'Account suspended', 'ACCOUNT_SUSPENDED');
  }

  await assertLoginEmailVerified(userId, runtime);

  // passkeyMfaBypass=true (default): passkey with userVerification=required satisfies both factors
  const mfaBypass = config.mfa?.webauthn?.passkeyMfaBypass ?? true;
  if (!mfaBypass && config.mfa && adapter.isMfaEnabled && (await adapter.isMfaEnabled(userId))) {
    const methods = adapter.getMfaMethods ? await adapter.getMfaMethods(userId) : ['totp'];

    let emailOtpHash: string | undefined;
    const emailOtpConfig = config.mfa.emailOtp ?? null;
    if (methods.includes('emailOtp') && emailOtpConfig) {
      const { generateEmailOtpCode } = await import('@auth/services/mfa');
      const { code, hash } = generateEmailOtpCode(runtime);
      emailOtpHash = hash;
      const fullUser = adapter.getUser ? await adapter.getUser(userId) : null;
      if (fullUser?.email)
        eventBus.emit('auth:delivery.email_otp', { email: fullUser.email, code });
    }

    let webauthnChallenge2: string | undefined;
    let webauthnOptions: Record<string, unknown> | undefined;
    if (methods.includes('webauthn') && (config.mfa.webauthn ?? null)) {
      const { generateWebAuthnAuthenticationOptions } = await import('@auth/services/mfa');
      const result = await generateWebAuthnAuthenticationOptions(userId, runtime);
      if (result) {
        webauthnChallenge2 = result.challenge;
        webauthnOptions = result.options;
      }
    }

    const mfaToken = await createMfaChallenge(
      runtime.repos.mfaChallenge,
      userId,
      { emailOtpHash, webauthnChallenge: webauthnChallenge2 },
      config,
    );
    return { token: '', userId, mfaRequired: true, mfaToken, mfaMethods: methods, webauthnOptions };
  }

  const { token, refreshToken, sessionId } = await createSessionForUser(
    userId,
    runtime,
    metadata,
    hookContext,
  );
  emitLoginSuccess(userId, sessionId, runtime);
  return { token, userId, email: fullUser?.email, refreshToken };
};
