#!/usr/bin/env bun
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

export const EVENT_RELIABILITY_SUPPORT_PATH = resolve(
  import.meta.dir,
  '../packages/docs/src/content/docs/reference/event-reliability-support.mdx',
);

export function renderEventReliabilitySupport(): string {
  return `---
title: Event Reliability Support
description: Generated support matrix for transactional outbox and inbox delivery.
---

{/* Generated by scripts/generate-event-reliability-support.ts. Do not edit by hand. */}

| Store      | BullMQ outbox            | Kafka outbox             | Transactional inbox   |
| ---------- | ------------------------ | ------------------------ | --------------------- |
| PostgreSQL | Supported, live repeated | Supported, live repeated | Supported, live       |
| SQLite     | Supported, live repeated | Supported, live repeated | Supported             |
| Memory     | Rejected before I/O      | Rejected before I/O      | Rejected before I/O   |
| Redis      | Rejected before I/O      | Rejected before I/O      | Rejected before I/O   |
| MongoDB    | Reserved, unsupported    | Reserved, unsupported    | Reserved, unsupported |

In-process transport cannot satisfy acknowledged outbox delivery. It remains available for
ephemeral events and test-only inbox wrappers.

Release evidence is emitted as \`event-reliability-conformance.v2.json\`. CI rejects missing
live combinations, failed or manually skipped cases, delivered claims without acknowledged
receipt evidence, replay-version incompatibility, and operator authorization/audit failures.
`;
}

export function main(args = Bun.argv.slice(2)): number {
  const expected = renderEventReliabilitySupport();
  if (args.includes('--check')) {
    const actual = readFileSync(EVENT_RELIABILITY_SUPPORT_PATH, 'utf8');
    if (actual !== expected) {
      console.error('[event-reliability] generated support documentation is dirty.');
      return 1;
    }
    return 0;
  }
  writeFileSync(EVENT_RELIABILITY_SUPPORT_PATH, expected);
  return 0;
}

if (import.meta.main) process.exit(main());
