import type { GeneratedFile, PresetContext } from '../../../types/preset';

/**
 * Generate a GitHub Actions workflow file that deploys the ECS service via SST.
 *
 * The workflow triggers on pushes to `main` that touch the service path or any
 * `packages/` directory. It uses OIDC (`id-token: write`) to assume an AWS IAM
 * role specified in `secrets.AWS_ROLE_ARN`, then runs `bunx sst deploy --stage
 * <stageName>`. Optional `infra.overrides.gha.steps.before` / `.after` arrays
 * inject extra workflow steps around the SST deploy step.
 *
 * @param ctx - The current `PresetContext` with platform, stage, service, and infra config.
 * @returns A `GeneratedFile` with:
 *   - `path`: `.github/workflows/deploy-<serviceName>-<stageName>.yml`
 *   - `content`: the YAML workflow text.
 *   - `ephemeral: true`.
 */
export function generateEcsGhaWorkflow(ctx: PresetContext): GeneratedFile {
  const { platform, stageName, serviceName, service, infra } = ctx;
  const servicePath = service?.path ?? '.';

  const overrides = infra.overrides?.gha;
  const stepMap = isRecord(overrides) && isRecord(overrides.steps) ? overrides.steps : undefined;
  const beforeSteps = formatExtraSteps(stepMap, 'before');
  const afterSteps = formatExtraSteps(stepMap, 'after');

  const content = `# Generated by slingshot — do not commit
name: Deploy ${serviceName} to ${stageName}

on:
  push:
    branches: [main]
    paths:
      - '${servicePath}/**'
      - 'packages/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - run: bun install --frozen-lockfile

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: \${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${platform.region}
${beforeSteps}
      - name: Deploy with SST
        run: bunx sst deploy --stage ${stageName}
${afterSteps}
`;

  return {
    path: `.github/workflows/deploy-${serviceName}-${stageName}.yml`,
    content,
    ephemeral: true,
  };
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === 'object';
}

function formatExtraSteps(
  steps: Record<string, unknown> | undefined,
  phase: 'before' | 'after',
): string {
  if (!steps) return '';
  const phaseSteps = steps[phase];
  if (!Array.isArray(phaseSteps) || phaseSteps.length === 0) return '';
  const list = phaseSteps as Array<Partial<Record<'name' | 'run' | 'uses', string>>>;

  return (
    list
      .map(step => {
        const lines: string[] = [];
        lines.push(`      - name: ${step.name ?? 'Custom step'}`);
        if (step.run) lines.push(`        run: ${step.run}`);
        if (step.uses) lines.push(`        uses: ${step.uses}`);
        return lines.join('\n');
      })
      .join('\n') + '\n'
  );
}
