import type { DomainConfig, InfraLoggingConfig, ServiceDeclaration } from '../../../types/infra';
import { type InfraSize, SIZE_PRESETS } from '../../../types/infra';
import type { GeneratedFile, PresetContext } from '../../../types/preset';
import { getServiceEnv } from '../../../types/preset';
import { resolveDomain } from '../../resolveDomain';

interface SstServiceEntry {
  name: string;
  port: number;
  domain?: string;
  cpu: number | string;
  memory: number | string;
  minCount: number;
  maxCount: number;
  targetCpu: number;
  healthCheck: string;
  logRetention: number;
  logDriver: string;
  fluentdAddress?: string;
  fluentdTag?: string;
  env: Record<string, string>;
}

/**
 * Generate an `sst.config.ts` file for ECS (Fargate) deployments.
 *
 * Produces a complete SST v3 config that provisions a VPC, an ECS Cluster, and
 * one `cluster.addService()` call per included service. Each service block is
 * wrapped in `// --- section:service-<name> ---` markers for user override support.
 *
 * CPU and memory are derived from the service's `size` field via `SIZE_PRESETS`,
 * falling back to `'small'`. Scaling, domain, health check path, log retention,
 * and per-service environment variables are all resolved from the infra config and
 * injected into the generated TypeScript.
 *
 * @param ctx - The current `PresetContext` with platform, stage, stack, infra config,
 *   and resolved environment variables.
 * @returns A `GeneratedFile` with:
 *   - `path`: `'sst.config.ts'`
 *   - `content`: the generated TypeScript config file text.
 *   - `ephemeral: true`.
 *
 * @remarks
 * Special characters in environment variable values are escaped with
 * `escapeForTs()` before embedding. Log driver can be `'cloudwatch'` (default)
 * or `'fluentd'`; fluentd logging includes `fluentd-address` and `tag` options.
 */
export function generateSstConfig(ctx: PresetContext): GeneratedFile {
  const { platform, stackName } = ctx;
  const entries = resolveServiceEntries(ctx);

  const serviceBlocks = entries
    .map(entry => {
      const envLines = Object.entries(entry.env)
        .map(([k, v]) => `          ${k}: "${escapeForTs(v)}",`)
        .join('\n');

      const publicBlock = entry.domain
        ? `      public: {\n        domain: "${entry.domain}",\n        ports: [{ listen: "443/https", forward: "${entry.port}/http" }],\n      },`
        : '      public: { ports: [{ listen: "80/http" }] },';

      const loggingBlock =
        entry.logDriver === 'fluentd'
          ? `      logging: {
        driver: "fluentd",
        options: {
          "fluentd-address": "${entry.fluentdAddress ?? 'localhost:24224'}",
          "tag": "${entry.fluentdTag ?? `app.${entry.name}`}",
        },
      },`
          : `      logging: {
        retention: "${entry.logRetention} days",
      },`;

      return `    // --- section:service-${entry.name} ---
    cluster.addService("${entry.name}", {
      cpu: "${formatCpu(entry.cpu)}",
      memory: "${formatMemory(entry.memory)}",
      image: {
        dockerfile: "Dockerfile.${entry.name}",
        context: "${ctx.appRoot}",
      },
      scaling: {
        min: ${entry.minCount},
        max: ${entry.maxCount},
        cpuUtilization: ${entry.targetCpu},
      },
${publicBlock}
      health: {
        path: "${entry.healthCheck}",
        interval: "30 seconds",
      },
${loggingBlock}
      environment: {
${envLines}
      },
    });
    // --- end:service-${entry.name} ---`;
    })
    .join('\n\n');

  const content = `// Generated by slingshot — do not commit
/// <reference path="./.sst/platform/config.d.ts" />

export default $config({
  app(input) {
    return {
      name: "${platform.org}-${stackName}",
      home: "aws",
      providers: {
        aws: { region: "${platform.region}" },
      },
    };
  },
  async run() {
    // --- section:vpc ---
    const vpc = new sst.aws.Vpc("Vpc", {
      nat: "managed",
      az: 2,
    });
    // --- end:vpc ---

    // --- section:cluster ---
    const cluster = new sst.aws.Cluster("Cluster", { vpc });
    // --- end:cluster ---

${serviceBlocks}
  },
});
`;

  return {
    path: 'sst.config.ts',
    content,
    ephemeral: true,
  };
}

function resolveServiceEntries(ctx: PresetContext): SstServiceEntry[] {
  const { infra, stageName, stackName, stage } = ctx;
  const stageStacks = stage.stacks?.[stackName];
  const stageScaling = stageStacks?.scaling;

  if (infra.services) {
    return Object.entries(infra.services)
      .filter(([, svc]) => {
        const stacks = svc.stacks ?? infra.stacks ?? [];
        return stacks.includes(stackName);
      })
      .map(([name, svc]) =>
        buildEntry(name, svc, infra, stageScaling, getServiceEnv(ctx, name), stageName, stage),
      );
  }

  return [
    buildEntry(
      ctx.serviceName,
      ctx.service ?? { path: '.' },
      infra,
      stageScaling,
      getServiceEnv(ctx, ctx.serviceName),
      stageName,
      stage,
    ),
  ];
}

function buildEntry(
  name: string,
  svc: ServiceDeclaration | { path: string },
  infra: {
    size?: InfraSize;
    scaling?: {
      min?: number;
      max?: number;
      cpu?: number | string;
      memory?: number;
      targetCpuPercent?: number;
    };
    healthCheck?: string | { path: string };
    logging?: InfraLoggingConfig;
    domain?: string;
    domains?: Record<string, DomainConfig>;
    services?: Record<string, ServiceDeclaration>;
  },
  stageScaling: { min?: number; max?: number } | undefined,
  env: Record<string, string>,
  stageName: string,
  stage: import('../../../types/platform').StageConfig,
): SstServiceEntry {
  const fullSvc = svc as ServiceDeclaration;
  const size = fullSvc.size ?? infra.size ?? 'small';
  const sizePreset = SIZE_PRESETS[size];
  const scaling = fullSvc.scaling ?? infra.scaling ?? {};

  // Resolve domain with stage-specific mapping support
  const baseDomain = fullSvc.domain ?? (!infra.services ? infra.domain : undefined);
  const domainConfig = fullSvc.domains?.[name] ?? infra.domains?.[name];
  const domain = baseDomain ? resolveDomain(baseDomain, stageName, stage, domainConfig) : undefined;

  const logging = fullSvc.logging ?? infra.logging;
  const logDriver = logging?.driver ?? 'cloudwatch';

  return {
    name,
    port: fullSvc.port ?? 3000,
    domain,
    cpu: scaling.cpu ?? sizePreset.cpu,
    memory: scaling.memory ?? sizePreset.memory,
    minCount: stageScaling?.min ?? scaling.min ?? 1,
    maxCount: stageScaling?.max ?? scaling.max ?? 2,
    targetCpu: scaling.targetCpuPercent ?? 70,
    healthCheck: resolveHealthCheckPath(fullSvc.healthCheck ?? infra.healthCheck),
    logRetention: logging?.retentionDays ?? 30,
    logDriver,
    fluentdAddress: logging?.fluentd?.endpoint,
    fluentdTag: logging?.fluentd?.tagPrefix ? `${logging.fluentd.tagPrefix}.${name}` : undefined,
    env,
  };
}

function resolveHealthCheckPath(hc: string | { path: string } | undefined): string {
  if (!hc) return '/health';
  if (typeof hc === 'string') return hc;
  return hc.path;
}

function formatCpu(cpu: number | string): string {
  if (typeof cpu === 'string') return cpu;
  if (cpu <= 4) return `${cpu} vCPU`;
  return `${cpu / 1024} vCPU`;
}

function formatMemory(memory: number | string): string {
  if (typeof memory === 'string') return memory;
  if (memory >= 1024) return `${memory / 1024} GB`;
  return `${memory} MB`;
}

function escapeForTs(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}
